common/config/environment.go, datadog/agent/docker.go
Allow defining agent docker image path  from pulumi variables. This will allow environments with dev branch docker images, that are not published to docker hub
Docker image users
=> [docker] allow agent image path from pulumi variables

datadog/agent/docker.go
Expose opts in agent's Docker Installation.
agent.Docker
Motivation
----------
Allow to pass dependencies to agent's docker installation: in NDM docker compose up depends on some files that need to be uploaded
=> [agent] expose resource options in docker agent installation

aws/scenarios/vm/ec2VM/params.go, azure/compute/vm/params.go, common/agentinstall/install.go, common/agentinstall/params.go, common/vm/params.go, common/vm/vm.go
This PR provides small improvements:
- Don't use SemVer for the Agent version as custom build versions are not SemVer versions.
- Remove API key from `agentinstall.Params` and use config map instead.
Motivation
----------
=> Remove API key from agentinstall.Params

aws/environment.go, common/config/environment.go
Adds a helper to parse a comma separated string as a list of strings. This is used to parse security groups and subnets.
Motivation
----------
=> Parse security groups and subnets from string

aws/scenarios/microVMs/microvms/libvirt.go, aws/scenarios/microVMs/microvms/libvirt_fs.go, aws/scenarios/microVMs/microvms/resources/amd64.go, aws/scenarios/microVMs/microvms/resources/arm64.go, aws/scenarios/microVMs/microvms/resources/default.go, aws/scenarios/microVMs/microvms/resources/default/network.xls, aws/scenarios/microVMs/microvms/resources/default/pool.xml, aws/scenarios/microVMs/microvms/resources/default/volume.xml, aws/scenarios/microVMs/microvms/resources/distro.go, aws/scenarios/microVMs/microvms/resources/resources.go
This PR introduces the use of pulumi.Random to generate mac addresses for the microvm network devices.
As a consequence it also changes the way parameters for the resource XML are formatted into the templates.
This PR impacts the microVMs scenario only.
Motivation
----------
Without the use of pulumi.Random, pulumi falsely detects the network as having changed on each update, and therefore recreates all microVMs, since the network is a dependent resource for the domains (VMs).
=> Use pulumi.Random to generate Mac Addresses

.github/CODEOWNERS
Add repo owners
None
Motivation
----------
Allow split ownership on the repo
=> [owners] add codeowners

datadog/agent/ecs.go
This PR allows the EC2 ECS tasks to also allow remote execution (like the fargate ones).
It'll affect EC2 ECS agent deployments.
Motivation
----------
One might want to jump into the tasks for troubleshooting, inspection, or otherwise.
This is also consistent with the ECS Fargate deployments.
=> [ecs] agent: ec2 tasks should also enable execution

aws/scenarios/dockerVM/dockerVM/run.go, aws/scenarios/microVMs/microvms/provision.go, aws/scenarios/vm/ec2VM/ec2VM.go, aws/scenarios/vm/os/amazonLinux.go, aws/scenarios/vm/os/debian.go, aws/scenarios/vm/os/fedora.go, aws/scenarios/vm/os/packagemanager.go, aws/scenarios/vm/os/redhat.go, aws/scenarios/vm/os/suse.go, azure/compute/vm/azurevm.go, command/package.go, common/os/macos.go, common/os/os.go, common/os/packagemanager.go, common/os/ubuntu.go, common/os/unix.go, common/os/windows.go, common/vm/nixvm.go, common/vm/unixlikevm.go, common/vm/unixvm.go, common/vm/vm.go, datadog/agent/docker/agentDockerInstaller.go, kubernetes/kind.go
Add the package managers for Nix OSes.
This PR also introduces `NixVM` which is a Linux / Unix / MacOS VM. `NixVM` has extra features compared to a regular VM:
- FileManager (Not yet supported for Windows)
- PackageManager (Doesn't make a lot of sense for Windows Server)
- DockerManager (Not yet supported for Windows)
For tests that should be run for all OSes including Windows, the user should use `CreateXXVM` otherwise the user should use `CreateNixXXXVM`.
Reviewing commit by commit is recommended.
Motivation
----------
=> Add package managers for Nix OSes.

aws/scenarios/microVMs/microvms/run.go, command/filemanager.go, command/runner.go, command/utils.go, common/vm/vm.go, go.mod, go.sum
This PR provides support for adding a runner level option to set the user for all commands. It also extends `Args` to specify a specific `User` for individual command.
The priority level for deciding the user is: `sudo` -> `args.User` -> `runner.User`
This impacts all scenarios.
Motivation
----------
The microvms scenario is simplified by being able to set a user for running all the commands, rather than handling permissions on a case-by-case basis.
=> Add runner level user

aws/scenarios/microVMs/microvms/libvirt.go, aws/scenarios/microVMs/microvms/libvirt_fs.go, aws/scenarios/microVMs/microvms/provision.go, aws/scenarios/microVMs/microvms/run.go
This PR takes advantage of setting the runner-level user to run all comands as user `libvirt-qemu`.
Impacts microvms scenario.
Motivation
----------
=> Reorder commands to run with user 'libvirt-qemu'

common/config/environment.go
Enable the agent deployment by default.
This value was set at false because it was not possible to not install the Agent when creating a VM.
As now, the Agent installation is independent with the VM creation, this value can be set at true.
Motivation
----------
=> Enable the agent deployment by default

datadog/agent/ecs.go
This PR addresses an issue where the ECS deployments failed due to an incorrect network mode being defined for EC2-based ECS cluster tasks. 
ECS EC2(classic) based deployments
Motivation
----------
`bridge` mode was resulting in the following cluster/task instantiation error:
```
* creating ECS Service (<id>-ec2-linux-dd-agent): InvalidParameterException: Network Configuration is not valid for the given networkMode of this task definition.
```
Changing the mode to `awsvpc` seems to address the problem.
source: https://stackoverflow.com/questions/59678757/awsvpc-network-configuration-is-not-valid-for-the-given-networkmode-of-this-tas
=> [ecs] agent: network mode should be awsvpc for correct instantiation

command/filemanager.go, common/os/macos.go, common/os/os.go, common/os/unix.go, common/os/windows.go, common/utils/file.go, datadog/agent/install.go, datadog/agent/params.go
This PR adds the support for integrations. It also introduces `WithTelemetry` which provides the Agent telemetry (package `telemetry` and `go expvar`).
There is an issue when updating from `_, err = agent.NewInstaller(vm, agent.WithTelemetry())` to ` _, err = agent.NewInstaller(vm)`. Indeed, even with `pulumi.DeleteBeforeReplace(true)` on `restart-agent` resource, `restart-agent` is run before the integration files were removed. Any suggestions?
Motivation
----------
=> Allow to install Agent integration

aws/scenarios/dockerVM/run.go, aws/scenarios/vm/ec2VM/ec2VM.go
Expose internal aws environment on EC2 vms. 
unixvm
Motivation
----------
This is required to allow using the share a single aws environment in a scenario or test factory. Test setup using fakeintake will need this to initiate the fakeintake ec2 task
=> [ec2vm] expose aws env

.pre-commit-config.yaml
This change plus upgrading both `pre-commit` and `golangci-lint` dramatically improved performance on my local machine. 
Motivation
----------
precommit-hook became super slow recently. Could not find the root cause, but this couple of changes improved its performance
=> [golangci-lint] upgrade version and remove parallel runs

.github/workflows/lint.yml
* uses the recommended `--new` option for the CI 
* fix diff warning
* increase golangci-lint timeout to reduce faiures
You can see it slightly reduces linter time back under 6 min 
Motivation
----------
Linter action in the CI slowed down recently, causing timeout errors. The root cause is the go packages loading taking > 3 minutes. We could improve with a static cache\
```
level=info msg="[loader] Go packages loading at mode 575 (files|types_sizes|compiled_files|deps|exports_file|imports|name) took 3m14.498308796s"
```
=> [CI] slightly improve linter

command/docker.go, command/runner.go, command/unixOSCommand.go
Fix sudo command execution by properly formatting, handling separately `sudo` and `sudo -u`
dockerVM, all
Motivation
----------
https://github.com/DataDog/test-infra-definitions/pull/44 broke docker vm scenario and docker commands, as it prefixed command with `sudo bash -c '<command>'` instead of `sudo <command>`
This ended up in running subshell commands as `root` user instead of default user as we were expecting
```
ubuntu@ip:~$ sudo  bash -c 'echo $(whoami)'
root
ubuntu@ip:~$ bash -c 'sudo echo $(whoami)'
ubuntu
```
=> [unix] properly format linux command with sudo or user

common/utils/connection.go, common/utils/remoteServiceConnector.go, common/vm/vm.go
This PR adds `RemoteServiceConnector` which is a convenient struct to help implementing `GetClientDataDeserializer()`.
Here is an example of usage when you want to serialize a `Connection` and a `string`.
```go
type ClientData struct {
MyString   string
Connection utils.Connection
}
type MyRemoteService {
// This implement GetClientDataDeserializer() func(auto.UpResult) (*ClientData, error)
*RemoteServiceConnector[ClientData]
}
remoteServiceConnector := utils.NewRemoteServiceConnector(ctx, ClientData{})
remoteServiceConnector.Register(stackKey, "Connection", connection)
remoteServiceConnector.Register("test", "MyString", pulumi.String("Hello"))
return &MyRemoteService{
MyRemoteService: remoteServiceConnector
}
```
Which scenarios this will …
=> Add RemoteServiceConnector

datadog/agent/install.go
Skip agent config update on empty agent or no extra config
VM with agent install
Motivation
----------
This was breaking agent install `WithFakeintake` as extraconfig was not considered, and `agentConfig` was empty
=> [agent] skip agent config update on empty agent or extra config

command/osCommand.go, command/unixOSCommand.go, command/windowsOSCommand.go
* On delete remove directory only when it is empty
* Wrap create and delete commands for copy inline file in a separate shell 
VM
Motivation
----------
`CreateDirectory` configures a delete action that is execute when the directory resource is removed from the stack, for example when calling `pulumi down`. When `CreateDirectory` is called on an existing directory, the `create` command does nothing, but the delete command removes it. This is unexpected for users and can cause issues. As an example, if we create the agent config directory, removing the directory resource would delete the configuration directory and mess up with the agent install.
In this PR I suggest removing only empty …
=> [filemanager] fix create directory and copy inline file

tasks/destroy.py
Use 3.8 compatible `str[:-len(suffix)]` to remove stack name suffix instead of 3.9 `removesuffix`
Motivation
----------
`removesuffix` is available in 3.9 while Datadog Agent repo is based on 3.7+
Source: https://peps.python.org/pep-0616/
=> [invoke] use python 3.8 compatible remove suffix

aws/environment.go, aws/scenarios/dockerVM/run.go, aws/scenarios/vm/run.go, azure/environment.go, command/runner.go, common/config/environment.go, common/utils/random.go
Define one providers per environment instance
All
Motivation
----------
Default singleton providers are causing a bug when updating the environment, as pulumi keeps re-using the same instance of provider while creating a new environment instance
=>  [env] 🐛  define provider per common environment instance

tasks/__init__.py, tasks/config.py, tasks/deploy.py, tasks/doc.py, tasks/docker.py, tasks/eks.py, tasks/tool.py, tasks/vm.py
Add the invoke task `create-eks`.
Note: Installing the agent doesn't work.
```
Usage: inv[oke] [--core-opts] create-eks [--options] [other tasks here ...]
Docstring:
Create a new EKS environment. It lasts around 20 minutes.
Options:
--, --eks-bottlerocket-node-group   Install a bottlerocket node group (default False)
-a STRING, --agent-version=STRING   The container version of the Agent for example '7.45.0-rc.3' (default `latest`)'
-e, --[no-]eks-linux-node-group     Install a Linux node group (default True)
-i, --install-agent                 Install the Agent (default False).
-k, --eks-linux-arm-node-group      Install a Linux ARM node group (default False)
-s STRING, --stack-name=STRING      An optional name for the stack. This parameter is …
```
=> Add EKS invoke task

aws/scenarios/ecs/fakeintake.go
Have fakeintake helper accepting an ec2.VM instead of a unix vm
None
Motivation
----------
Fakeintake can work with any ec2 vm
=> [ecs] fakeintake needs an ec2vm

aws/scenarios/microVMs/config/config.go, aws/scenarios/microVMs/microvms/run.go, aws/scenarios/microVMs/sample-vm-config.json
This PR schedules an automatic shutdown of the EC2 instance created for the micro-vm scenario if the shutdown behavior of the EC2 instance is set to 'terminate'. It uses the configuration value if provided or sets it to 6 hours by default.
Motivation
----------
=> Schedule a shutdown if the shutdown behavior is set to 'terminate'

aws/scenarios/microVMs/microvms/domain.go, aws/scenarios/microVMs/microvms/libvirt.go, aws/scenarios/microVMs/microvms/resources/amd64/domain.xls, aws/scenarios/microVMs/microvms/resources/distro/domain-amd64.xls
This PR addresses the issue of spurious network updates, when updating the pulumi stack.
This was stemming from the fact that the network subnet was incorrectly being set to 169.254.0.1/24. This is wrong because the specified subnet implies the start of the address range to be 169.254.0.0. The libvirt sdk correctly derives the subnet from the provided one, but as a result on every update pulumi would detect a "change" from 169.254.0.1/24 => 169.254.0.0/24 as the subnet. This would result in an unnecessary network update, followed by a restart of all running VMs. 
This PR also add `host-passthrough` as the cpu mode for `amd64` VMs. This is an optimization. `host-passthrough` allows qemu to tell KVM to pass through to the host CPU without any …
=> Prevent unnecessary network update

scenarios/aws/microVMs/microvms/domain.go, scenarios/aws/microVMs/microvms/libvirt.go, scenarios/aws/microVMs/microvms/resources/distro.go, scenarios/aws/microVMs/microvms/resources/resources.go
Create a unique Nvram file for each arm64 distribution VM, using EFI to boot.
Motivation
----------
Sharing the Nvram file occasionally causes bugs when the initialization operation of each VM corrupts data.
=> Create unique Nvram file for each ARM64 distro VM.

components/datadog/agent/helm.go, go.mod, go.sum, scenarios/aws/eks/run.go
Make the Helm datadog agent deployment method also deploy the agent on Windows nodes.
* `aws/eks`
Motivation
----------
We want to be able to validate the Windows support.
=> Make the Helm agent deployment also deploy it on Windows nodes

components/command/filemanager.go, components/command/unixOSCommand.go, components/command/windowsOSCommand.go, components/datadog/agent/install.go
Fix integration install command, creating directory if it does not exist. The `CreateDirectory` creates a directory only if it does not exist, adding doc comment on top of them.
vm
Motivation
----------
This is preventing installing custom integrations
=> [install] create integration folder (if it does not exist)

components/datadog/apps/dogstatsd/k8s.go, components/datadog/apps/nginx/k8s.go, components/datadog/apps/prometheus/k8s.go, components/datadog/apps/redis/k8s.go
Make the kubernetes fake applications children of the kubernetes provider like it is already the case for the agent deployed with Helm.
* `aws/eks`
Motivation
----------
Fix dependencies and allow Pulumi to skip the deletion the kubernetes resources when it is deleting the kubernetes cluster.
=> Make the k8s fake apps children of the k8s provider like the k8s agent

components/command/osCommand.go, components/command/runner.go, components/command/unixOSCommand.go, components/command/windowsOSCommand.go
This PR adds a new parameter to `command.Args` which passes the `-S` flag to sudo. This allows us to pass the password for `sudo` from stdin.
Motivation
----------
The micro-vms scenario runs some commands locally with `sudo`. We need some way to pass the password.
=> Allow to pass sudo password from stdin.

common/config/environment.go, scenarios/aws/microVMs/microvms/run.go
This PR allows to add pipeline-id as a tag to an ec2 instance, if the appropriate environment variable is present.
It also makes the tags more consistent by always using dash ("-") instead of underscore ("_").
Motivation
----------
=> Add pipieline ID tag

components/datadog/agent/helm.go
Dual ship the data to the fakeintake not only from the node agents, but also from the cluster agent and the cluster checks workers.
All the ones based on the Helm deployment.
* `aws/eks`
Motivation
----------
We want to be able to test cluster checks.
=> Dual ship data also from the cluster agent and the cluster checks workers

.github/workflows/lint.yml, Pulumi.yaml, common/config/environment.go, common/config/providers.go, common/utils/random.go, components/command/runner.go, components/datadog/agent/ecs.go, components/datadog/agent/helm.go, components/datadog/fakeintake/ecsFargate.go, resources/aws/ec2/ami.go, resources/aws/ec2/asg.go, resources/aws/ec2/vm.go, resources/aws/ec2/vmtemplate.go, resources/aws/ecs/capacityProviders.go, resources/aws/ecs/cluster.go, resources/aws/ecs/fargateService.go, resources/aws/ecs/nodeGroups.go, resources/aws/eks/nodeGroups.go, resources/aws/eks/role.go, resources/aws/environment.go, resources/aws/iam/role.go, resources/azure/aks/cluster.go, resources/azure/compute/vm.go, resources/azure/environment.go, scenarios/aws/ecs/run.go, scenarios/aws/eks/run.go, scenarios/aws/kindvm/run.go, scenarios/aws/microVMs/microvms/run.go, tasks/deploy.py, tasks/eks.py
Fix UTF8 character in `Pulumi.yaml` that prevented `disable-default-providers` to work.
Provision providers lazily and provide helpers to set them in resources.
Use `invoke` runner to run commands instead of directly `subprocess`, make `debug` work for `eks`.
All.
Motivation
----------
=> Fix UTF8 char in disable default providers. Add Lazy instantiation of providers. Use invoke to run commands

Dockerfile
Adds `xsltproc` to the list of dependencies in the Dockerfile. `xsltproc` is used by the libvirt-sdk to modify the XML files defining the VM environment.
Motivation
----------
=> Add xsltproc to the list of dependencies in the Dockerfile

components/datadog/apps/nginx/k8s.go, components/datadog/apps/redis/k8s.go, scenarios/aws/eks/run.go
Make the `nginx` and `redis` apps depend on the agent deployment for the `DatadogMetric` `CRD`.
This CRD is setup by the agent Helm chart deployment and is needed for the HPA of those two apps.
* `aws/eks`
Motivation
----------
Fix the following errors when attempting to run the `aws/eks` scenario:
```
Diagnostics:
kubernetes:datadoghq.com/v1alpha1:DatadogMetric (nginx):
error: creation of resource workload-nginx/nginx failed because the Kubernetes API server reported that the apiVersion for this resource does not exist. Verify that any required CRDs have been created: no matches for kind "DatadogMetric" in version "datadoghq.com/v1alpha1"
kubernetes:datadoghq.com/v1alpha1:DatadogMetric …
```
=> Make the `nginx` and `redis` apps depend on the agent deployment

Pulumi.yaml
Disable all important default providers **except** AWS as it's used by `eks` plugin, which is broken until https://github.com/pulumi/pulumi-eks/pull/886 is merged.
Motivation
----------
=> Remove AWS from disable default providers until EKS plugin is fixed

components/datadog/agent/helm.go
Fix the following error in the agents:
```
=====================
Datadog Cluster Agent
=====================
- Could not detect the Datadog Cluster Agent's endpoint: temporary failure in clusterAgentClient, will retry later: cluster agent authentication token length must be greater than 32, curently: 20
- Could not retrieve the version of the Datadog Cluster Agent.
```
* `aws/eks`
Motivation
----------
Fix agent ⟷ cluster-agent communication
=> Fix the cluster agent authentication token length

tasks/deploy.py
Fix a typo with an uncalled function when using the invoke task from outside the repository.
None as this is specifically for the invoke task.
Motivation
----------
Being able to use the invoke task from outside the repository.
The `_get_root_path` function wasn't called in the argument list, which resulted in a corrupted command being executed, eg.
```
pulumi  -C <function _get_root_path at 0x1057d75e0> stack ls
```
which resulted in an error like
```
/bin/bash: function: No such file or directory
```
=> Fix error when using the invoke task from outside the repository

resources/aws/environment.go, scenarios/aws/microVMs/config/config.go, scenarios/aws/microVMs/microvms/libvirt.go, scenarios/aws/microVMs/microvms/network.go, scenarios/aws/microVMs/microvms/run.go
This PR uses `commonConfig`  if we are not setting up aws instances.
The microVM scenario is used to launch local VMs. We want to avoid forcing the user to perform MFA in this case.
Motivation
----------
=> Use commonConfig when aws env is not required

components/command/docker.go, components/command/filemanager.go, components/command/osCommand.go, components/command/unixOSCommand.go, components/command/windowsOSCommand.go
Install docker agent storing agent compose in home directory rather than in temporary directory
docker
Motivation
----------
Temporary folder is cleaned up at reboot. Thus after the reboot of an instance where we installed agent on docker, the compose file created at deployment time was gone, like the container. Saving the compose file on home has the advantage of 
* not needing sudo powers
* allowing persistency of the file after reboot
* being available cross-platform
The helper can be used elsewhere.
=> [docker] fix agent install not working after instance restart

common/config/environment.go, scenarios/aws/vm/run.go, tasks/doc.py, tasks/tool.py, tasks/vm.py
Add a new option in invoke task to pass an AMI id as input
Replaces #151 
Creation of AWS VM
Motivation
----------
Possibility to run on older distribution than the ones we get by default today, and reach even more distributions (rockylinux for instance)
Uses AMI ID today even is this should be generalized to other cloud providers
=> Add ami_id as input option of create_vm

components/datadog/apps/nginx/ecs.go, components/datadog/apps/redis/ecs.go, components/datadog/fakeintake/ecsFargate.go, go.mod, go.sum, resources/aws/ecs/fargateService.go, scenarios/aws/fakeintake.go
* Put a load balancer in front of the fake intake so that it keeps the same IP when it is OOM-killed.
* Use the `awsx` provider to define the other load balancers.
* all
Motivation
----------
Although I agree that the OOM kills of the fake intake should be addressed independently of this workaround, I think there is a value to guarantee a stable IP to target the fake intake.
It will keep on working (although the data will vanish) when the fake intake will restart either involuntarily (in case of OOM kill or crash) or voluntarily (in case of deployment of a new dev version for ex.) without requiring a full rollout of the agents to update their config.
It has the side effect of removing the …
=> Put a load balancer in front of the fake intake

scenarios/aws/microVMs/microvms/domain.go, scenarios/aws/microVMs/microvms/libvirt.go, scenarios/aws/microVMs/microvms/libvirt_fs.go, scenarios/aws/microVMs/microvms/resources/default.go, scenarios/aws/microVMs/microvms/resources/default/volume.xml, scenarios/aws/microVMs/microvms/resources/resources.go, scenarios/aws/microVMs/vmconfig/config.go
This PR performs various optimizations to improve the setup time of the libvirt pools and volumes. These optimizations are done to improve the performance of the setup environment job as the number of VMs in `vmsets` increase.
The PR performs 3 main optimizations.
1. Download `qcow2` images from S3, rather than using the images already 'present' in the AMI.
2. Deduplicate the base images used to build the volumes, so that download and setup steps are not repeated when the same base volume is used to setup a VM.
3. When creating volumes specify the base image as a backing store, to avoid the expensive step of uploading the base image into the libvirt volume.
- Base image: The bootable `qcow2` image used to build the libvirt volumes.
- Libvirt …
=> Optimize libvirt filesystem setup.

scenarios/aws/vm/ec2os/centos.go, scenarios/aws/vm/ec2os/os.go, scenarios/aws/vm/run.go, tasks/tool.py
Add support for CentOS 7
VM
Motivation
----------
We frequently have to test CentOS 7 in QA as it is one of the supported Agent OS, the image is added to both `sandbox` and `agent-sandbox` public available AMI
=> [vm] add centos aws os type support

tasks/deploy.py, tasks/docker.py, tasks/ecs.py, tasks/eks.py, tasks/tool.py, tasks/vm.py
Fix a bug preventing using the invoke task from outside the directory.
It also uses the task's `Context` to run a command which was ran with `subprocess` previously.
None as this is only related to the invoke task.
Motivation
----------
Being able to use the invoke task from outside the directory without having a crash.
The logic is very similar to what is done in `deploy.py`.
I believe this bug started when I updated pulumi to 1.74 but I'm not 100% sure.
To reproduce the bug, run
`inv -r ~/dd/test-infra-definitions create-vm --no-install-agent --no-use-fakeintake` from outside the `test-infra-definitions` directory.
The root error is 
```error: if you're …
```
=> Fix running the invoke task from outside the directory

components/datadog/fakeintake/ecsFargate.go
Let pulumi assign LB name itself.
* all
Motivation
----------
Our current logic to build smart resource names can exceed the maximum name size allowed.
This PR will generate LB named like this:
=> Let pulumi assign LB name itself to avoid name too long error

components/datadog/apps/nginx/ecs.go, components/datadog/apps/redis/ecs.go, components/datadog/fakeintake/ecsFargate.go, resources/aws/ec2/vm.go, resources/aws/ec2/vmtemplate.go, resources/aws/ecs/fargateService.go, resources/aws/environment.go, scenarios/aws/eks/run.go, scenarios/aws/microVMs/microvms/run.go
Make a better use of the IP available in the subnets in order to avoid premature exhaustion of IP.
| Before | After |
|--------|--------|
| All single VM use-cases were spawning the VM always on the same first subnet. This could lead to exhaustion of available IP in the first subnet whereas the other two subnets were barely used. | Single VM use-cases are now spawning the VM on a subnet randomly chosen among the 3 available ones. It spreads the usage on all 3 subnets. |
| Load balancers were consuming 3 IP, one per subnet in which they were present. | It’s not possible to have a load balancer inside a single availability zone. But, instead of putting them in all 3 zones, we now put them only in 2 zones randomly chosen among the 3 available ones. …
=> Reduce the number of IP needed per LB and better spread VM on subnets

resources/aws/ecs/fargateService.go
Remove unused constants to fix golangci-lint warnings.
None.
Motivation
----------
The CI appeared red when I merged a PR.
The issue seems to come from https://github.com/DataDog/test-infra-definitions/pull/225 but the linter didn't warn anything on that PR...
=> Remove unused constants to fix go lint warnings

scenarios/aws/microVMs/microvms/libvirt_fs.go
Motivation
----------
The custom filesystem was not being marked as local, which was causing it to traverse the remote deployment path when the stack was launch locally.
=> Mark custom filesystem as `Local` if required

tasks/ecs.py, tasks/eks.py
Use account from local profile to build the helper command to reach eks and ecs infrastructures after an environment is created on an account. 
eks, ecs
Motivation
----------
The current command copied to the clipboard is using `sandbox` hardcoded account
=> [task] use account wrapper in output commands in ecs and eks

.test_infra_config.yaml.example, tasks/setup.py
Improve team tag instructions in setup team, suggesting using github team name
All
Motivation
----------
Feedback to have more guidelines on which name we should use. At DD we have different team name sources:
* workday
* github
* slack channel
Using agent guidelines and keep using github team name. Some devs might have more than one team (ex squad plus team), they can select their main team name
=> [task] Improve team tag instructions

common/namer/namer.go, common/namer/namer_test.go
#240 aimed at fairly truncating all the parts that are concatenated by `Namer` in order to generate names that fit inside the length-limited `name` field of cloud providers objects.
In order to do that, it needs to do a discrete linear interpolation.
This PR replaces the naive algorithm by the optimal one.
Motivation
----------
The Bresenham’s algorithm is iterative and compute all the pixels between two points.
In our use case, we don’t need all the points, but only the ones corresponding to tokens boundaries.
I initially thought that the inefficiency of the naive algorithm due to the division operation would be balanced by the fact that not all points needed to be computed.
The expected …
=> Follow up #240: AETT-186 Ensure namer.DisplayName doesn’t generate a name exceeding a maximum

Dockerfile
Pin cython under 3.0.0 to fix PyYAML wheel build error.
None
Motivation
----------
Since `cython==3.0.0` release `PyYAML==5.4.1` installation fails
https://github.com/yaml/pyyaml/issues/724#issuecomment-1638636728
`PyYAML==6.0.1` was released with a fix pinning `cython<3.0.0`, there is no backporting yet on `PyYAML=5.4`, so we are fixing this with a workaround. 
`PyYAML` wheel is built because there is no pre-build package for python 3.10. 
We need to explicit install `PyYAML` as it will be removed from `datadog-agent-build-image` requirements in https://github.com/DataDog/datadog-agent-buildimages/pull/419
We could also downgrade the base image to …
=> [runner] pin cython < 3.0.0

scenarios/aws/vm/ec2os/fedora.go
Change the AMI used for creating a Fedora VM
VM scenario
Motivation
----------
Be able to create Fedora VM
=> Use newer Fedora AMI that works

tasks/vm.py
This PR disables by default the creation of the fake intake when creating a vm.
Motivation
----------
Most of the time the user doesn't need the fake intake when creating a VM.
=> When creating a VM disable the fake intake by default

common/config/environment.go
It includes `CI_PIPELINE_ID` in the list of env var that will be used as tags for resources. So resources are automatically tagged when running in CI.
Motivation
----------
To be able to link resources with CI pipelines. Which is convenient to create a clean up job for example
=> Add CI_PIPELINE_ID in env var tags, to automatically tags re sources with pipeline id

components/datadog/agent/install.go
Restart the agent when having an empty config. This fixes the following code where using `""` as config doesn't restart the agent.
```go
v.UpdateEnv(e2e.AgentStackDef(nil, agentparams.WithAgentConfig("log_level: debug")))
v.UpdateEnv(e2e.AgentStackDef(nil, agentparams.WithAgentConfig(""))) // Agent not restart
```
=> Restart the agent when having a empty config

tasks/eks.py
Show the correct path for KUBECONFIG when creating a EKS cluster introduced by https://github.com/DataDog/test-infra-definitions/pull/245/files.
Motivation
----------
=> Show the correct path for KUBECONFIG when creating a EKS cluster

go.mod
Bumps the go version in go.mod to 1.20 due to [failures installing golangci on ci](https://github.com/DataDog/test-infra-definitions/actions/runs/5930254863/job/16082089060)
Motivation
----------
=> golangci needs go version of at least 1.20

integration-tests/invoke_test.go
Temp fix to avoid overwriting local config when running go test locally
Motivation
----------
Not break config while the issue is fixed with a proper fix
=> Temporarly disable integration test locally to avoid overwritting local config

integration-tests/invoke_test.go, tasks/config.py, tasks/deploy.py, tasks/destroy.py, tasks/doc.py, tasks/docker.py, tasks/ecs.py, tasks/eks.py, tasks/setup.py, tasks/vm.py
Add --config-path option to all invoke task, to specify a custom location for the config file
All
Motivation
----------
It can be useful if user wants to manage several config file. It is also useful to fix integration tests, to be able to use a temporary configuration file, to not break local config file of user running go test
Another solution could be to use an env variable `TEST-INFRA-CONFIG_FILE` and to check for this variable in the `get_full_profile_path` function
=> Config file path can now be configured, also fixes integration tests ran locally

.gitlab-ci.yml
Migrate the `build-runner-image` GitLab job to Kubernetes runners.
Only the build of the test image.
Motivation
----------
CI/CD evolution
`runner:docker` is deprecated.
https://datadoghq.atlassian.net/wiki/spaces/DEVX/pages/2411528655/Onboarding+To+Gitlab+CI#Gitlab-runner-tags
=> Migrate to Kubernetes GitLab runners

components/datadog/agent/install.go, components/datadog/agentparams/params.go
This PR adds the ability to set configurations for system-probe and the security-agent using `WithSystemProbeConfig` and `WithSecurityAgentConfig`
=> Add system-probe and security-agent config

components/os/unix.go
fix apttesting.datad0g.com as the path is prefixed with /dists/
dists/pipeline-xxxxx-a7
Motivation
----------
=> fix apttesting.datad0g.com

Dockerfile
Install helm in pulumi-runner image using binaries instead of the script fetched from github
None 
Motivation
----------
This will prevent the github error rate we get when installing using the install script. It also prevents flakiness pinning helm version
=> [dockerfile] install helm from binaries

.github/workflows/lint.yml, Dockerfile, common/utils/remote.go
With `Command` plugin bumped to `0.9` we can finally control the `Dial` timeout, meaning that we won't get stuck for 2-3 minutes (OS timeout) before retrying SSH connection if the first attempt is made while SSH server is not yet ready.
Motivation
----------
=> Use timeout options added to Command plugin

.gitlab-ci.yml, Dockerfile
* Use e2e requirements from [buildimages](https://github.com/DataDog/datadog-agent-buildimages/blob/main/requirements/e2e.txt)
* Build the image and publish to a test repo, run integration tests on the test version, push to stable runner on main after tests success
None
Motivation
----------
Use e2e python requirements to keep in sync with other agent python requirements, since the image is used by `datadog-agent` pipeline
Run tests on the pipeline image to ensure the image runs fine
=> [dockerfile] update requirements and jobs order

resources/aws/ecs/fargateService.go
Fix a panic 💣 in `resources/aws/ecs.FargateTaskDefinitionWithAgent`:
```
Diagnostics:
pulumi:pulumi:Stack (dd-lenaic-ecs):
panic: reflect: call of reflect.Value.Elem on string Value
goroutine 1 [running]:
reflect.Value.Elem({0x380b7c0?, 0x46def50?, 0x40fa07?})
/home/lenaic/.local/go/src/reflect/value.go:1261 +0x1a5
github.com/DataDog/test-infra-definitions/resources/aws/ecs.FargateTaskDefinitionWithAgent({0xc0004901c0, {0xc000171760, {0xc0006147c0, 0x1, 0x1}}, 0xc000318600, {{{0x433d3f6, 0x9}}, {{0x434a34e, 0x15}, ...}}, ...}, ...)
/home/lenaic/doc/devel/DataDog/test-infra-definitions/resources/aws/ecs/fargateService.go:37 +0x16e
github.com/DataDog/test-infra-definitions/scenarios/aws/ecs.Run(0xc000171760) …
```
=> Fix a panic in `resources/aws/ecs.FargateTaskDefinitionWithAgent`

go.mod, go.sum, tasks/doc.py, tasks/eks.py, tasks/tool.py
`random 4.14` requires `Go 1.21`, which we are not using yet, making `go mod tidy` unhappy.
Motivation
----------
=> Fallback random version, add install workload parameter for EKS

common/config/environment.go, components/datadog/agent/helm.go
Add new parameters
* `ddagent:imagePullRegistry`
* `ddagent:imagePullUsername`
* `ddagent:imagePullPassword`
to set docker registry credentials.
Those based on Helm deployment.
Motivation
----------
Whereas EKS nodes have, by default and out of the box, the credentials to fetch the docker images from the private ECR of the same AWS project, it’s not the case for the kind setup.
The kind testcase is currently failing because all the pods remain in `ImagePullBackoff` because they miss the credentials to fetch the agent docker images from the private ECR registry.
https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
=> Add parameters to set docker registry credentials

scenarios/aws/ecs/run.go, scenarios/aws/eks/run.go, scenarios/aws/kindvm/run.go
Ensure stacks output have the ECS or Kubernetes cluster name.
ECS, EKS, Kind
Motivation
----------
In the `datadog-agent` CI, I’d like to be able to build URLs to the [E2e tests — containers — ECS](https://dddev.datadoghq.com/dashboard/mnw-tdr-jd8/e2e-tests-containers-ecs) and [E2e tests — containers — K8s](https://dddev.datadoghq.com/dashboard/qcp-brm-ysc/e2e-tests-containers-k8s) dashboards with the template variables  (`ecs_cluster_name` and `kube_cluster_name`) already pre-filled so that the link is “ready-to-click”.
=> Ensure stacks output have the ECS or K8S cluster name

.gitlab-ci.yml
Fix the `release-runner-image` CI job which is currently failing with this error:
```
$ docker pull ${CI_REGISTRY_IMAGE_TEST}:${CI_COMMIT_SHORT_SHA}
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```
Motivation
----------
The job is currently broken because the docker socket isn’t accessible from a Kubernetes runner.
Using `crane` is also more efficient as we don’t need to complete the download of the full image locally before starting to upload it to its new name.
This PR depends on a new image that needs to be mirrored thanks to ~~DataDog/images#4565~~ ~~DataDog/images#4568~~.
=> Fix the `release-runner-image` CI job and use `crane` instead `docker pull/push`

components/datadog/apps/fakeintake/fargateFakeintakeService.go
Increase the amount of memory granted to the fake intake.
Motivation
----------
On the EKS scenario, the fake intake is almost always close to 100% of memory usage and is OOM killed every 10 or 15 minutes.
=> [CONTINT-3310] Increase the memory for the fake intake to avoid OOM kill

components/datadog/apps/fakeintake/fargateFakeintakeService.go
Set `GOMEMLIMIT` to the fake intake to ¾ of its memory limit.
As `GOMEMLIMIT` is a “soft” memory limit, it’s safer to take a security margin.
Motivation
----------
Without it, the memory is never released. The memory consumed by the fake intake keeps on increasing forever until it is OOM killed.
=> [CONTINT-3310] Set GOMEMLIMIT to the fake intake

scenarios/aws/vm/ec2vm/ec2VM.go
Use InstanceName for instance name instead of ImageName
Motivation
----------
The name was based off ImageName so creating two VMs from the same AMI resulted a name collision
=> Use InstanceName for instance name instead of ImageName

.gitignore, components/command/runner.go, scenarios/aws/microVMs/microvms/domain.go, scenarios/aws/microVMs/microvms/libvirt.go, scenarios/aws/microVMs/microvms/network.go, scenarios/aws/microVMs/microvms/provision.go, scenarios/aws/microVMs/microvms/proxy.go, scenarios/aws/microVMs/microvms/run.go
Adds SSH config to microvm provisioning:
- Add `AcceptEnv DD_API_KEY` to `sshd_config`
- Setup SSH config files
microVMs
Motivation
----------
- Ability to send metrics from metal instances and micro vms.
- Prevent repeating of SSH options
- Easier SSH to metal instance and microvm from commands
https://datadoghq.atlassian.net/browse/EBPF-237
=> Adds SSH config to microvm provisioning

components/datadog/agentparams/params.go
Change `if` order so that agent version defined by `E2E_VERSION` has more priority than `E2E_PIPELINE_ID`
`E2E_PIPELINE_ID` is [set](https://github.com/DataDog/datadog-agent/blob/f3a8e91bda24d892bc898f3c3e6cdd78bde7d861/.gitlab/e2e.yml#L145) in the Agent which means that whenever we want to use a stable version we need to set both `E2E_VERSION=<version>` and `E2E_PIPELINE_ID=""`
With this change, we'll always take `E2E_VERSION` if set, or `E2E_PIPELINE_ID` otherwise
QQ: are there others scenarios where we absolutely need `E2E_PIPELINE_ID` to have priority ?
Motivation
----------
Allow to use a stable version in the CI with a more straightforward way (1 variable to set VS 1 set + 1 unset) …
=> Give more priority to E2E_VERSION than E2E_PIPELINE_ID

components/datadog/apps/nginx/k8s.go, components/datadog/apps/redis/k8s.go
Make the `nginx` and `redis` Kubernetes deployments scale up and down faster.
* `kind` and
* `eks`
Motivation
----------
The tests that are validating that the Kubernetes HPA is properly scaling up and down are sometimes failing because they don’t wait long enough.
Here is an example of such a job: https://gitlab.ddbuild.io/DataDog/datadog-agent/-/jobs/353184628
The error is:
```
=== Failed
=== FAIL: tests/containers TestKindSuite/TestNginx/kubernetes_state.deployment.replicas_available{kube_namespace:workload-nginx,kube_deployment:nginx} (1200.00s)
k8s_test.go:361: No scale down detected
k8s_test.go:361: 
Error Trace:	/go/src/github.com/DataDog/datadog-agent/test/new-e2e/tests/containers/k8s_ …
```
=> [CONS-3310, CONS-3314] Make the Nginx and Redis deployments scale faster

components/datadog/apps/fakeintake/fargateFakeintakeService.go, components/datadog/fakeintake/connectionExporter.go, scenarios/aws/fakeintake.go
Enable running several Fakeintakes (and their load balancers) in the same test. 
AWS Fakeintake 
Motivation
----------
I need to run two Fakeintakes for a test of the agent. 
This PR builds on top of https://github.com/DataDog/test-infra-definitions/pull/403 so it shouldn't merged before it.
This change was tested by writing https://github.com/DataDog/datadog-agent/pull/20167.
=> [ASCII-749][APL-2241] Allow multiple Fakeintakes

scenarios/aws/microVMs/microvms/domain.go, scenarios/aws/microVMs/microvms/err.go, scenarios/aws/microVMs/microvms/libvirt.go, scenarios/aws/microVMs/microvms/libvirt_fs.go, scenarios/aws/microVMs/microvms/network.go, scenarios/aws/microVMs/microvms/pool.go, scenarios/aws/microVMs/microvms/provision.go, scenarios/aws/microVMs/microvms/resources/amd64.go, scenarios/aws/microVMs/microvms/resources/amd64/domain.xls, scenarios/aws/microVMs/microvms/resources/arm64.go, scenarios/aws/microVMs/microvms/resources/arm64/domain.xls, scenarios/aws/microVMs/microvms/resources/default.go, scenarios/aws/microVMs/microvms/resources/default/raw_volume.xml, scenarios/aws/microVMs/microvms/resources/default/volume.xml, scenarios/aws/microVMs/microvms/resources/distro.go, scenarios/aws/microVMs/microvms/resources/distro/domain-amd64.xls, scenarios/aws/microVMs/microvms/resources/distro/domain-arm64.xls, scenarios/aws/microVMs/microvms/resources/resources.go, scenarios/aws/microVMs/microvms/run.go, scenarios/aws/microVMs/microvms/volume.go, scenarios/aws/microVMs/vmconfig/config.go
This PR allows the user to specify multiple disks to boot a VM from.
This PR also adds support for attaching a ram-backed file as a block device to a VM.
This facility will be used to share dependencies with the mircovms.
It has an advantage over baking the dependencies directly in the microvm, since it keeps the size of the microvms small which allows faster downloads. The dependency disk is also downloaded only once and shared with the VMs using a COW overlay.
When used in the datadog-agent CI, this approach should help eliminate the expensive step of downloading docker images into each microvm.
https://datadoghq.atlassian.net/browse/EBPF-243
Motivation
---------- …
=> Allow VM to boot with multiple disks

.github/workflows/build.yml
Update GO to 1.20 in the GitHub workflow.
Motivation
----------
Since #305, the `go.mod` says that this project needs GO 1.20: https://github.com/DataDog/test-infra-definitions/blob/d08836e5ac08530051cc43c91f7bbf6bc1d8a29a/go.mod#L3
So, we need the CI build to use GO 1.20 as well.
Still using GO 1.19 is actually breaking some dependabot :dependabot: PRs:
#406 [fails with this error](https://github.com/DataDog/test-infra-definitions/actions/runs/6629940242/job/18010292295?pr=406):
```
Error: ../../../go/pkg/mod/github.com/pulumi/esc@v0.5.6/schema/schema.go:306:25: undefined: strings.CutPrefix
note: module requires Go 1.20
Error: Process completed with exit code 1.
``` …
=> Update GO to 1.20 in the GitHub workflow

components/datadog/agentparams/params.go, components/datadog/apps/fakeintake/fargateFakeintakeService.go
Add event platform endpoints to the Agent config when using the fake intake.
I'm currently testing the diagnose command and the command is failing because the Agent is sending request to the real backend with a dummy API Key.
Motivation
----------
=> Add event platform endpoints to Agent config when using Fake Intake

components/datadog/agentparams/params.go
Add a `WithIntakeHostname` agent option.
Agent using a Fakeintake, although the change should be transparent (backward compatible).
Motivation
----------
Use a custom intake name in a test, without copy pasting the implementation of `WithFakeintake`.
Implementation is exactly the same as `WithFakeintake`.
=> [ASCII-749] Add WithIntakeHostname

.github/CODEOWNERS
remove e2e from codeowners for microvms
Motivation
----------
=> remove e2e from codeowners for microvms

common/config/environment.go, components/datadog/apps/dogstatsd/k8s.go, components/datadog/dogstatsd-standalone/k8s.go, scenarios/aws/eks/run.go, scenarios/aws/kindvm/run.go
This PR adds the option to deploy standalone dogstatsd in the `aws/kind` scenario.
The dogstatsd clients already defined in `components/datadog/apps/dogstatsd` can be used to test it.
=> [scenarios/aws/{kindvm,eks}] Add option to deploy standalone dogstatsd

components/datadog/dogstatsd-standalone/k8s.go, scenarios/aws/eks/run.go, scenarios/aws/kindvm/run.go
Sets `DD_CLUSTER_NAME` in the dogstatsd-standalone deployment.
It follows the same pattern as the agent, sets the cluster name when running on Kind and doesn't when running on EKS.
=> [components/datadog/dogstatsd-standalone] Set DD_CLUSTER_NAME

components/datadog/dogstatsd-standalone/k8s.go
To be consistent with the tag cardinality configured in the agent.
This will allow us to reuse the same tests.
=> [components/datadog/dogstatsd-standalone] Set tag cardinality to "high"

components/datadog/dogstatsd-standalone/k8s.go
Mounts the container runtime socket in the dogstatsd-standalone daemonset.
The majority of features were working because it had access to the Kubelet, but it was missing some tags that are only available when it has access to the container runtime socket.
The scenarios where dogstatsd-standalone is deployed use containerd, that's why I've hardcoded the containerd socket path. We can change this later if needed.
=> [components/datadog/dogstatsd-standalone] Mount container runtime socket

components/datadog/agent/helm.go, components/datadog/agent/secrets.go, components/datadog/dogstatsd-standalone/k8s.go
Creates the image pull secret when it's needed in the dogstats-standalone daemonset.
=> [components/datadog/dogstatsd-standalone] Create image pull secret if needed

components/datadog/apps/cpustress/ecs.go, components/datadog/apps/cpustress/k8s.go, scenarios/aws/ecs/run.go, scenarios/aws/eks/run.go, scenarios/aws/kindvm/run.go
Add a `cpustress` testing workload.
* `EKS`
* `Kind`
* `ECS`
Motivation
----------
Port to the new-e2e tests framework the legacy `cpu-stress` tests: https://github.com/DataDog/datadog-agent/blob/main/test/e2e/argo-workflows/templates/cpu-stress.yaml
=> [CONTINT-258] Add `stress-ng` test workload

common/config/environment.go, components/datadog/agentparams/params.go, components/datadog/agentparams/params_test.go, components/os/os.go, components/os/unix.go
To fix an issue we have on Datadog-agent kitchen/new-e2e-tests install script tests, due to concurrent update on deb package repository by ARM and X86_64 jobs , we created two dfiferent repo `pipeline-<pipeline-id>-arm64' and `pipeline-<pipeline-id>-x86_64'
This PR update the `WithPipeline` option to match with these two new repository on apt repository
Required for PR: https://github.com/DataDog/datadog-agent/pull/20532
Motivation
----------
=> Change WithPipeline to work with new arm64 and x86 repo for deb on datadog-agent

components/datadog/agent/ecs.go
Increase the CPU allocated to the agent on ECS.
* `ECS`
Motivation
----------
We regularly have ECS flaky tests.
The symptom is random ECS test failing because of missing ECS specific tags.
It turns out that the tags used to be on the metric. But at some point, they disappear.
Investigation shown that the ECS tags disappear because the agent restarts. We can see its `task_arn` changing.
Ex. of notebook showing this: https://dddev.datadoghq.com/notebook/6891346/l%C3%A9na%C3%AFc-nov-07-2023-22-59?view=view-mode
The reason why only ECS tags are missing is because those ones are polled. So, it takes more time to get those ones than tags relying on watch mechanisms.
The agent is killed because the …
=> Increase the CPU for the ECS agent

Dockerfile
Skip Pulumi upgrade warning when running on test-infra build image.
None
Motivation
----------
Pulumi prints a default warning message when running on a non up-to-date version. This is annoying when running on the CI, as it [adds noise](https://github.com/DataDog/test-infra-definitions/compare/pducolin/APL-2195-skip-pulumi-update-warning?expand=1)
Skip update check on the CI
=> [docker] skip pulumi update warning

.awsconfig, Dockerfile
Set default awsconfig, used at startup by test-infra image.
None
Motivation
----------
Reduce flakiness in e2e tests due to connection issues at first `aws ssm` call. We will need to update the retries configuration on all `awsconfig` downloaded from ssm.
=> [docker] increase max attempts for calls to aws ssm

components/datadog/apps/fakeintake/fargateFakeintakeService.go
Use `time.Second` for `time.Duration`.
Here we add an `int` with value `1000` which is interpreted as `1000` ns
Motivation
----------
Fix some flakiness in tests
=> Use time.Second to define sleep interval

Dockerfile
This PR adds `jq` to the Dockerfile. 
Motivation
----------
Used for parsing aws-cli output as a json. It is neater to parse aws-cli output as json than text.
=> Add jq to Dockerfile

components/datadog/apps/fakeintake/fargateFakeintakeService.go
- enforce fakeintake health during deployment, have pulumi fail if fakeintake is not healthy
- define health check command of the fakeintake task in AWS
Fakeintake
Motivation
----------
Test could start before the fakeintake was healthy, we want to be able to
1. fail the deployment if the fakeintake was not healthy after some time
2. as a bonus, see from the AWS interface whether a fakeintake is healthy
Noticed that the definition of the fakeintake service was duplicated so factored that.
The health check in AWS uses `curl`, so this PR depends on https://github.com/DataDog/datadog-agent/pull/20940 which adds `curl` to the container.
=> Define fakeintake healthcheck, enforce fakeintake health during deployment

tasks/doc.py, tasks/ecs.py
Activate Bottlerocket node group by default with Invoke.
This impact the ECS scenario.
Motivation
----------
Without this, the `create-ecs` fails by default because of a Redis port collision.
Replaces https://github.com/DataDog/test-infra-definitions/pull/465
=> [ecs] Create Bottlerocket node group by default with Invoke

scenarios/aws/microVMs/microvms/pool.go, scenarios/aws/microVMs/microvms/volume.go
This PR shortens the URNs generated for some libvirt resources. It was observed that the URNs were going beyond the 255 character limit in come cases.
Motivation
----------
=> Shorten Libvirt Volume and Pool URNs

scenarios/aws/vm/ec2vm/ec2VM.go
- The full package name is required to install sshd on Windows
Updates the PowerShell install script to include the full specification for the OpenSSH server package.
All Windows.
Motivation
----------
When attempting to use the `inv create-vm` tool, with an AMI for Windows 2019, the SSH setup step silently failed and the sshd service wasn't installed. This prevented any SSH connections.
This is a quick fix for Windows servers, however, there is a slightly better option we should consider in the long run that installs openssh from a known Github MSI package. Right now, an example of that exists in dev branch in a file within datadog-agent. A future PR should …
=> Fix Windows SSH service installation

resources/aws/ecs/fargateService.go
Changes the version of ecs
ECS e2e testing and test infra definition.
Motivation
----------
Latest is not stable and does not work with `pidMode` set as `task`. It is useful for orchestrator explorer.
=> Use stable version for fluent-for-bits on ecs

components/datadog/apps/fakeintake/fargateFakeintakeService.go
Remove the health check command from the fakeintake task definition.
Fakeintake
Motivation
----------
When performing an `UpdateEnv`, pulumi redeploys the fakeintake (which shouldn't have changed), so the one the agent is using doesn't exist anymore.
It is not clear why but removing the health command removes this issue.
=> fix: remove health check command which breaks updateEnv

Pulumi.yaml, components/datadog/apps/fakeintake/fargateFakeintakeService.go, resources/aws/environment.go
This reverts commit 14270eb9af59b78b88743bdc76320e4c7b3227e2.
Revert a temporary workaround for a bug in `pulumi-eks` which has now been fixed.
Motivation
----------
https://github.com/pulumi/pulumi-eks/pull/886 has been merged.
It has been released in `v1.0.4`: https://github.com/pulumi/pulumi-eks/compare/v1.0.3...v1.0.4
And we’ve upgraded to `pulumi/pulumi-eks:v1.0.4`: https://github.com/DataDog/test-infra-definitions/pull/400
=> Revert "Remove AWS from disable default providers until EKS plugin is fixed"

scenarios/aws/microVMs/microvms/pool.go
This PR fixes a regression introduced by https://github.com/DataDog/test-infra-definitions/pull/469.
Pool name needs to be deduplicated when we are setting up multiple stacks, which is the case in the local dev scenario.
Motivation
----------
=> Prepend stack name to poolname

.gitlab-ci.yml, integration-tests/invoke_test.go, integration-tests/testfixture/config.yaml, tasks/doc.py, tasks/setup.py
Install pulumi plugins at `inv setup` time
None
Motivation
----------
E2E tests in `datadog-agent` do not run invoke tasks to create resources, so do not install plugins out of the box. Adding explicit plugin install from the setup script, that can be safely re-executed as it reloads a existing local profile, plus it can be interrupted after all install steps are executed
=> [task] 🤖 install pulumi plugins at setup

components/datadog/apps/fakeintake/fargateFakeintakeService.go
Fix the following pulumi error:
```
Diagnostics:
aws:ssm:Parameter (aws-agent-apikey):
error: 1 error occurred:
* creating SSM Parameter (lenaic-ecs-agent-apikey): ParameterAlreadyExists: The parameter already exists. To overwrite this value, set the overwrite option in the request to true.
pulumi:pulumi:Stack (dd-lenaic-ecs):
error: update failed
```
* `aws/ecs` only.
Motivation
----------
The `ecs` scenario was already defining an SSM parameter with that name: https://github.com/DataDog/test-infra-definitions/blob/894572ece376dd9ac5d1bede114e8995272bde3f/scenarios/aws/ecs/run.go#L96-L99
As the fake intake can be deployed in any scenario, it’s best to have a …
=> [APL-2554] Fix SSM parameters name collision

components/datadog/apps/fakeintake/fargateFakeintakeService.go, resources/aws/ecs/fargateService.go, scenarios/aws/ecs/run.go
Increase the memory for the fake intake.
Motivation
----------
Fake intake is OOM killed in the middle of tests.
See for ex [this dashboard](https://dddev.datadoghq.com/dashboard/qcp-brm-ysc/e2e-tests-containers-k8s?refresh_mode=paused&tpl_var_fake_intake_task_family%5B0%5D=ci-24080255-4670-kind-cluster-fakeintake-ecs&tpl_var_kube_cluster_name%5B0%5D=ci-24080255-4670-kind-cluster&from_ts=1701688436218&to_ts=1701689956524&live=false) and scroll down to the `Fake intake` group.
We can see that the fake intake `Memory usage` is plateaued by `GOMEMLIMIT` while the `Number of payloads collected` keeps on growing.
Just before being killed we see a CPU spike caused by the GC. …
=> [CONTINT-3310] Increase the fake intake memory

components/datadog/apps/redis/k8s.go
Increase the `redis` application verbosity.
* `aws/eks`
* `aws/kind`
Motivation
----------
With the default log level, redis logs things only at startup and not at each request.
The problem is that, if the fake intake restarts in the middle of the tests, after redis pods have started, the tests will never find any redis logs from the fake intake client anymore.
In order to be more resilient to fake intake restarts, it’s better to be sure that the source of logs that are asserted are producing a continuous flow of logs.
=> [CONTINT-3310] Increase the Redis app verbosity

tasks/destroy.py
Rerun the pulumi destroy command with refresh in case of failure, to prevent issue when the managed resources are already destroyed
Motivation
----------
=> Rerun destroy with refresh on failure

components/datadog/apps/cpustress/ecs.go, components/datadog/apps/cpustress/k8s.go
Increase the amount of memory granted to the `cpustress` fake application using the `ghcr.io/colinianking/stress-ng:latest` image.
* `aws/ecs`
* `aws/eks`
* `aws/kind`
Motivation
----------
The `ghcr.io/colinianking/stress-ng:latest` image has recently been upgraded.
Whereas it used to consume 3 MB of memory, it is now consuming 42 MB.
=> Increase the amount of memory granted to `stress-ng`

components/os/unix.go
Remove the usage of `install_script.sh` which should not be used anymore, I guess
All scenarios where the agent is installed
Motivation
----------
Maintenance
=> Use last version of install_script on all cases

components/datadog/agent/ecsFargate.go, resources/aws/ecs/fargateService.go
Change image used for the agent monitoring fake intake to latest agent image
Since the agent deployed next to the fakeintake is supposed to help to monitor the fakeintake it is better to rely on a stable version of the agent
Motivation
----------
=> Use latest version of the agent to monitor fakeintake

scenarios/aws/kindvm/run.go
Start the agent with host network on `kind`.
* `aws/kind`
Motivation
----------
Fix the kubernetes control plane checks `kube_apiserver_metrics`, `kube_controller_manager` and `kube_scheduler`.
Kubernetes control planes components are binding their OpenMetrics endpoint to the loopback interface by default, so that the agent needs host network to be able to connect to them.
=> [CONTINT-52] Start the agent with host network on kind

scenarios/aws/microVMs/microvms/run.go
Removes the `unattended-upgrades` package on boot of the metal instances during the microvm scenario.
`aws/microVMs`
Motivation
----------
A failure installing packages due to `unattended-upgrades` already holding the `dpkg` lock.
https://datadoghq.atlassian.net/browse/EBPF-358
=> remove unattended-upgrades on microvm instances

components/datadog/apps/fakeintake/fargateFakeintakeService.go, resources/aws/ecs/fargateService.go
Make Pulumi wait for Fargate tasks to be ready before considering the service as being successfully created.
* `aws/ecs`
* `fakeintake`
Motivation
----------
I’ve seen some tests starting with a waiting loop for the fake intake to become healthy.
https://github.com/DataDog/datadog-agent/blob/f665d31db13044ae4ad2f113faef7aaebfab9be9/test/new-e2e/tests/agent-subcommands/diagnose_test.go#L50-L52
https://github.com/DataDog/datadog-agent/blob/f665d31db13044ae4ad2f113faef7aaebfab9be9/test/new-e2e/tests/agent-subcommands/flare/flare_common_test.go#L43-L46
This should normally not be needed if Pulumi is correctly waiting for resources to be fully created.
=> Make Pulumi wait for Fargate tasks to be ready

components/datadog/dogstatsd-standalone/k8s.go
Disable host metadata collection on dogstatsd standalone.
* `aws/eks`
* `aws/kind`
Motivation
----------
Host metadata are already sent by the agent running on the same nodes.
=> Disable host metadata collection on dogstatsd standalone

scenarios/aws/dockerVM/run.go, scenarios/aws/ecs/run.go, scenarios/aws/eks/run.go, scenarios/aws/fakeintake/fakeintakeparams/params.go, scenarios/aws/kindvm/run.go, scenarios/aws/vm/run.go
Set the `LoadBalancerEnabled` to `false` by default. Adding `WithLoadBalancer` method to enable the loadbalancer.
Motivation
----------
Modifying existing tests to work with these changes on [PR#21535](https://github.com/DataDog/datadog-agent/pull/21535)
=> Default deploy fakeintake without LB on VM stack

components/datadog/agent/ecsFargate.go, components/datadog/apps/nginx/ecs.go, components/datadog/apps/nginx/ecsFargate.go, components/datadog/apps/redis/ecs.go, components/datadog/apps/redis/ecsFargate.go
Fix some objects naming.
* `aws/ecs`
Motivation
----------
* Use `namer.ResourceName(…)` for naming Pulumi resources
* Use `e.CommonNamer.DisplayName(…)` for naming AWS resources
Here it how resources are now named:
=> [CONTINT-3399] Fix some objects naming

components/datadog/agent/helm.go
Configures the agent helm chart to include the config in order to send proc and orch payloads to the fake intake
=> add proc and orch additional endpoints in fakeintake helm chart

components/datadog/agent/helm.go
Use HTTP instead of HTTPS for process and orchestrator additional endpoints. This is necessary because the fake intake only listens on port 80, and does not accept TLS payloads.
EKS, Kind VM
Motivation
----------
Fix fake intake for process and orchestrator payloads
Additional endpoints originally added in https://github.com/DataDog/test-infra-definitions/pull/531.
Tests that use this functionality added in https://github.com/DataDog/datadog-agent/pull/21802
=> Use HTTP for process and orchestrator additional endpoints

components/datadog/agent/helm.go
Configure the agent on Kubernetes to dual-ship `container image`, `container lifecycle events` and `SBOM` payloads to the fake intake.
* `aws/eks`
* `aws/kind`
Motivation
----------
Allow to write e2e tests for the
* `containerimage`
* `contlcycle`
* `sbom`
checks.
The fakeintake client has been updated to support those new payloads in DataDog/datadog-agent#21742.
=> Dual-ship `contimage`, `contlcycle` and `sbom` payloads to the fakeintake

.github/workflows/build.yml, .gitlab-ci.yml, Dockerfile, components/datadog/apps/dogstatsd/images/dogstatsd/Dockerfile, components/datadog/apps/dogstatsd/images/dogstatsd/go.mod, components/datadog/apps/nginx/images/http-client/Dockerfile, components/datadog/apps/nginx/images/http-client/go.mod, components/datadog/apps/prometheus/images/prometheus/Dockerfile, components/datadog/apps/prometheus/images/prometheus/go.mod, components/datadog/apps/redis/images/redis-client/Dockerfile, components/datadog/apps/redis/images/redis-client/go.mod, go.mod, go.sum
- Bump Go version to `1.21`
- Align dev/release tag of `runner` image.
Motivation
----------
=> Bump Go version and align dev/release image tags

tasks/vm.py
As a consequence, --no-install-agent and --use-fakeintake are currently incompatible
Add a warning when using incompatible options
VM
Motivation
----------
Sanity
=> feat(logging): fakeintake is an agent option in VM scenario. 

resources/azure/aks/cluster.go, resources/azure/environment.go, resources/azure/environmentDefaults.go
This PR adds support of kata-enabled AKS clusters. It creates a new nodepool for kata runtimes.
az/aks
Motivation
----------
We would like to add e2e tests for kata enabled runtime
=> [CONTINT-3593] Support creating kata-enabled AKS cluster

components/kubernetes/kind_versions.go
Support newer kubernetes versions (1.28 and 1.29) when creating kind clusters.
kindvm
Motivation
----------
Being able to run E2E on newer k8s versions.
Testing
----------
The cluster is created correctly when tested with E2E:
```
@ updating.....
+  command:remote:Command remote-vm-connection-cmd-kind-create-cluster-kind creating (1s) Creating cluster "kind" ...
+  command:remote:Command remote-vm-connection-cmd-kind-create-cluster-kind creating (1s)  • Ensuring node image (kindest/node:v1.29.0) 🖼  ...
@ updating....................
+  command:remote:Command remote-vm-connection-cmd-kind-create-cluster-kind creating (18s)  ✓ Ensuring node image (kindest/node:v1.29.0) 🖼
+ …
```
=> [CONTINT-3600] Support k8s versions 1.28 and 1.29 in kind

scenarios/aws/microVMs/microvms/domain.go, scenarios/aws/microVMs/microvms/provision.go, scenarios/aws/microVMs/microvms/resources/amd64.go, scenarios/aws/microVMs/microvms/resources/arm64.go, scenarios/aws/microVMs/microvms/resources/distro.go, scenarios/aws/microVMs/microvms/resources/resources.go, scenarios/aws/microVMs/microvms/run.go
This PR
- adds support to provision local microvms. This allows us to attach docker disks for VMs launched locally as well.
- attaches all disks as volumes with two layers of overlays: base -> overlay-1 -> overlay-2. This is different behavior from before where disks other than the root filesystem were attached as files, with a single overlay. Overlay-1 is a libvirt volume backed by the base file. Overlay-2 is a unique writable volume shared with each microvm.
Motivation
----------
https://datadoghq.atlassian.net/browse/EBPF-372
=> Provision local microvms

scenarios/aws/microVMs/microvms/domain.go, scenarios/aws/microVMs/microvms/run.go
This PR adds support to emit a structured json object as the stack output of the microvms scenario. This structured output is easier to consume, and contains more information about the stack.
scenarios/aws/microVMs
Motivation
----------
https://datadoghq.atlassian.net/browse/EBPF-380
=> Emit structured stack output for KMT

scenarios/aws/eks/run.go
Setting `pulumi.com/patchForce` allows to update and own back the field
Motivation
----------
=> Change patching of amazon-vpc-cni CM as now the fields are created and owned by amazon-vpc-cni Helm chart

components/datadog/agent/host_linuxos.go, components/datadog/agent/host_windowsos.go
Adds a retry on both Linux and Windows when trying to download the agent install script from S3 bucket, this should solve this issue that happens sometimes
```
curl: (35) OpenSSL SSL_connect: SSL_ERROR_ZERO_RETURN in connection to s3.amazonaws.com:443
```
On linux we also add a retry on the execution of the install script itself since we know this is safe and could help to fix some issues encounter within the install script
It also fixes an issue with a `-1` suffix added to Windows version
None
Motivation
----------
Pulumi does not allow to retry resources on failure, to handle this we use bash/powershell scripting in the Pulumi Command
=> Add retry on install errors in Pulumi install, fix -1 suffix issue with Windows

common/config/environment.go, components/datadog/updater/install.go, components/datadog/updater/install_script.sh, scenarios/aws/ec2/vm_run.go, tasks/deploy.py, tasks/doc.py, tasks/vm.py
Add installation of the Updater component.
When we move the updater installation to the s3 agent install script, the light `install_script.sh` and the updater installation will be removed
Requirement
- merge https://github.com/DataDog/datadog-agent/pull/21681
Follow ups
- updater package e2e tests
- when the new agent is available, add agent config + use injected api key
This will be used in future scenarios on the impact. Confirmed that it's working by running the following commands on a [pipeline where the updater is packaged](https://gitlab.ddbuild.io/DataDog/datadog-agent/-/jobs/406498780)
```
test-infra-definitions $ invoke create-vm -i -o=ubuntu --install-updater --pipeline-id=26350333 …
```
=> Add updater install

components/kubernetes/kind.go, scenarios/aws/kindvm/run.go
Fix the link to the [e2e dashboard](https://dddev.datadoghq.com/dashboard/qcp-brm-ysc/e2e-tests-containers-k8s) displayed at the end of the tests run.
Currently, the tests are printing a link to [an empty dashboard](https://dddev.datadoghq.com/dashboard/qcp-brm-ysc/e2e-tests-containers-k8s?refresh_mode=paused&tpl_var_kube_cluster_name%5B0%5D=kind&tpl_var_fake_intake_task_family%5B0%5D=kind-fakeintake-ecs&from_ts=1705638423430&to_ts=1705639015684&live=false).
Here is an example.
This CI job: https://gitlab.ddbuild.io/DataDog/datadog-agent/-/jobs/412702092
gave this link: https://dddev.datadoghq.com/dashboard/qcp-brm-ysc/e2e-tests-containers-k8s?refresh_mode=paused&tpl_var_kube_cluster_name%5B0%5D=kind&tpl_var_fake_intake_task_family%5B0%5D=kind-fa …
=> Fix Kind cluster name

components/datadog/agent/kubernetes_helm.go
Enable `datadog.sbom.containerImage.uncompressedLayersSupport` when deploying the agent.
Kubernetes ones:
* `aws/kind`
* `aws/eks`
Motivation
----------
Without this option, SBOM scans just doesn’t work on kind.
=> Enable support of container image uncompressed layers for SBOM scans

components/datadog/agent/docker.go, components/datadog/agent/ecs.go
Make the trace-agent reachable in docker and ecs
Motivation
----------
=> components/datadog/agent: add apm port mapping in docker & ecs

scenarios/aws/ec2/vm_run.go
Fix invoke create-docker task
It was broken because the way it was rewritten assume the dogstatsd manifest can be applied alone, however the dogstatsd manifest must be applied together with the agent manifest to work and override some variables
Motivation
----------
=> Fix create-docker invoke task

components/datadog/agent/docker.go, components/docker/compose.go
Run docker agent in privileged mode, it's required to run system-probe properly
mount /sys/kernel/tracing from the host to the container as well
Motivation
----------
=> docker agent compose up running in privileged, required by system-probe

components/datadog/agent/ecs.go, components/datadog/agent/ecsFargate.go, components/datadog/agent/kubernetes_helm.go
Collect the agent telemetry data during the e2e tests.
`aws/ecs`
`aws/eks`
`aws/kind`
Motivation
----------
Telemetry data can help better understanding why a flaky test failed.
=> Collect agent telemetry

components/datadog/agent/ecs.go, components/datadog/agent/kubernetes_helm.go, components/datadog/dockeragentparams/params.go
Set `remote_configuration.no_tls_validation` to `true` when `skip_ssl_validation` is also set to `true`.
* `aws/ecs`
* `aws/eks`
* `aws/kind`
Motivation
----------
Fix the agent in `CrashLoopBackOff` in e2e tests because of this error:
```
Error: unable to create remote-config service: remote Configuration does not allow skipping TLS validation by default (currently skipped because `skip_ssl_validation` is set to true). While it is not advised, the `remote_configuration.no_tls_validation` config option can be set to `true` to disable this protection
```
`skip_ssl_validation: true` is needed to have the agent able to send payloads to the fake intake, which …
=> Set remote_configuration.no_tls_validation to true

scenarios/aws/eks/run.go, scenarios/aws/fakeintake/fakeintake.go, scenarios/aws/fakeintake/params.go, scenarios/aws/kindvm/run.go
Bump the memory of the fake intake to avoid OOM kill on the EKS and Kind scenarios.
Reduce the memory of the fake intake to save money on other scenarios.
* all
Motivation
----------
I was looking at some flaky e2e tests and some of the failures are pointing towards the fake intake.
Ex.:
* [fake intake returns 504 error](https://app.datadoghq.com/ci/test-runs?query=test_level%3Atest%20%40test.service%3Adatadog-agent%20%40git.branch%3Amain%20%40test.suite%3A%22github.com%2FDataDog%2Fdatadog-agent%2Ftest%2Fnew-e2e%2Ftests%2Fcontainers%22%20%40test.status%3Afail&citest_explorer_sort=time%2Cdesc&currentTab=overview&eventStack=AgAAAY1P4T3aaWxAuwAAAAAAAAAYAAAAAEFZMVA0VDNhQUFCSXVaSXFhQ0xkTmNfTQAAACQA …
=> [CONTINT-3706] Increase the fake intake memory

components/docker/docker.go, resources/aws/ec2/vm.go, resources/aws/environment.go, resources/aws/environmentDefaults.go, scenarios/aws/ec2/vm.go, scenarios/aws/ec2/vm_run.go, scenarios/aws/ec2/vmargs.go
Configure docker scenario to add an Instance Profile that allows pulling docker image from QA env ECR. Also configures the aws-ecr-credentials-helper
Related PR on `test-infra-cleaner`: https://github.com/DataDog/test-infra-cleaner/pull/16
Related PR on `datadog-agent`: https://github.com/DataDog/datadog-agent/pull/22373
Motivation
----------
=> Add instance profile and configure creds helper to authorize pulling docker images from ECR

.github/CODEOWNERS, components/datadog/apps/tracegen/images/tracegen/go.mod, components/datadog/apps/tracegen/images/tracegen/go.sum
- Define codeowners for `/components/datadog/apps/tracegen`
- Bump the version of dd-trace-go
APM
Motivation
----------
The new dd-trace-go version will allow us to test container tagging on cgroupv2 using TCP
AIT-9392
=> tracegen: bump dd trace go and define owners

common/config/environment.go, components/datadog/agent/docker.go, components/datadog/agent/docker_image.go, components/datadog/dockeragentparams/params.go, components/datadog/dogstatsd-standalone/docker_image.go, components/datadog/dogstatsd-standalone/k8s.go, resources/aws/const.go
Automatically uses the image built in the pipeline if PipelineID and CommitSHA are defined
Linked with: https://github.com/DataDog/datadog-agent/pull/22636
docker,ecs,kubernetes
Motivation
----------
=> APL-2848 Handle pipeline id and commit sha to set docker image

components/command/windowsOSCommand.go
Use `-Force` flag when creating a folder on Windows
We have issues when we use `WithIntegration` for the same integration in different tests on Windows. For instance, a first test creates the folder, and when the second test creates the folder again it fails with a `ResourceExists` error.
Motivation
----------
=> Use -Force when creating Windows folder to avoid ResourceExists error

components/os/descriptor.go, scenarios/aws/ec2/vm_run.go, scenarios/azure/compute/vm_run.go
Default descriptor to a valid descriptor instead of to an os flavor
docker and vm
Motivation
----------
The docker run function is currently broken, as it panics if a valid os descriptor is not defined on the config map
=> [os] descriptor from string defaults to default descriptor

scenarios/aws/ec2/vm_run.go
This PR exports the fakeintake when created in the docker vm.
- `aws/dockervm`
Motivation
----------
Currently, when a fakeintake is created within a dockervm scenario, it is not exported in the outputs of the stack. Exporting it is required because we need the fakeintake endpoint to initialize the fakeintake client in the e2e tests.
=> export fakeintake when created within dockervm

components/datadog/agent/host_linuxos.go
Increase `curl` retries to fetch the installer script from 3 to 10 
Linux Host
Motivation
----------
We are seeing flakiness doe to an `SSL_ERROR_ZERO_RETURN` on curl on tests using this resource
=> [host] increase agent installer curl retry

Dockerfile
This PR adds the [Pulumi time resource](https://www.pulumi.com/registry/packages/time/installation-configuration/), necessary for Windows Domain Controllers creation.
Windows Domain Controllers.
Motivation
----------
Working Windows Domain Controllers scenarios.
Since this is not directly used by this repository, I added it as a `pulumi plugin install` command instead of an entry in the `go.mod` file, to prevent it from being removed by `go mod tidy`.
=> Add pulumi time resource

.github/workflows/docker-publish.yml, components/datadog/apps/npm-tools/images/go-httpbin/Dockerfile
fix docker publish workflow
seems dd-merge-queue doesn't care about the main name of the workflow and build job conflict with the main job and didn't publish previous images from [PR](https://github.com/DataDog/test-infra-definitions/pull/612)
Motivation
----------
=> fix docker publish workflow

scenarios/aws/microVMs/microvms/libvirt.go, scenarios/aws/microVMs/microvms/network.go, scenarios/aws/microVMs/microvms/provision.go, scenarios/aws/microVMs/microvms/run.go, scenarios/aws/microVMs/vmconfig/config.go
This PR uses a separate network bridge for each VM set.
It also set the MTU size of the network bridge to 9000.
[This PR](https://github.com/DataDog/ami-builder/pull/157) in ami-builder sets the corresponding MTUs of the VM interfaces to match this.
`aws/microvms` only
Motivation
----------
We noticed the network read path to the NFS server experiencing latency causing problem with tests in KMT.
One possible culprit in this path is the shared network bridge between all the VMs and the host. This PR tries to alleviate pressure on the bridge by a assigning each vmset a different one.
=> Use separate network bridge for each VM set.

.github/jwt.sh, .gitlab-ci.yml
Remove private key after we're done using it
None
Motivation
----------
Limit life of private key on the CI
Could not find a way to generate the digest from the key content in memory, rather than stored in a file. Open to suggestions!
=> [gitlab] store private key in memory

components/datadog/apps/redis/ecs.go, components/datadog/apps/redis/ecsFargate.go, components/datadog/apps/redis/k8s.go
Update the redis container image from dockerhub `redis:latest` to `public.ecr.aws/docker/library/redis:latest`
tests that use the redis container images.
on the datadog-agent repo I found 1 test `TestRedisECS` that will fail after merging this PR. We will need to update the expected tags here:
* https://github.com/DataDog/datadog-agent/blob/d3c07fce4a0dc7eea2a79b9dd168c73c718f4cba/test/new-e2e/tests/containers/ecs_test.go#L252
* https://github.com/DataDog/datadog-agent/blob/d3c07fce4a0dc7eea2a79b9dd168c73c718f4cba/test/new-e2e/tests/containers/ecs_test.go#L281
Motivation
----------
avoid getting image pull backoff during end2end test. We recently seen several rate limit occurences in the …
=> Use public.ecr.aws redis image to avoid rate limit

tasks/config.py, tasks/setup.py
Add more checks to `inv setup.debug`
- Ensures pulumi is logged in
- if `privateKeyPath` is configured, ensures it is not encrypted or a proper `privateKeyPassword` is provided
Fail `inv.setup` if `pulumi` cannot be executed, e.g. not on PATH
Motivation
----------
=> Add checks for encrypted keys and pulumi creds to setup.debug

Dockerfile
Add the standalone ci-uploader to the test-infra-
definitions image
ec2
Motivation
----------
This is to remove dedicated upload jobs on datadog-agent repo, and upload tests alongside test execution
=> Add standalone uploader to upload tests at the end of test run

components/datadog/apps/tracegen/k8s.go, resources/aws/eks/nodeGroups.go, scenarios/aws/eks/run.go, scenarios/aws/kindvm/run.go, tasks/eks.py
This PR adds a workload sending traces from both cgroupv1 and cgroupv2 nodes in the aws/eks scenario
aws/eks, aws/kind
Motivation
----------
We would like to add e2e tests to make sure container id is retrieved for apm traces on both cgroupv1 and cgroupv2. 
Example: https://dddev.datadoghq.com/apm/traces?query=%40_top_level%3A1%20kube_cluster_name%3Aali-benabdallah-aws-eks%20kube_namespace%3Aworkload-tracegen-cgroupv2%20kube_deployment%3Atracegen-udp&cols=core_service%2Ccore_resource_name%2Clog_duration%2Clog_http.method%2Clog_http.status_code&historicalData=true&messageDisplay=inline&query_translation_version=v0&sort=desc&spanType=service-entry&traceQuery=&vi …
=> [CONTINT-3783] Add tracegen app to eks and kind scenarios

.pre-commit-config.yaml, pyproject.toml
Adds pre-commit config matching the linters found in workflows
None, only tooling
Motivation
----------
Detect linter failures before without requiring CI runs.
Due to how pre-commit works, we cannot install the modules from `requirements.txt` in the virtualenv, which means that `pyright` does not detect them and therefore fails (see https://github.com/pre-commit/pre-commit/issues/730 for a discussion on this problem). The solution is to revert to using the pyright program installed in the system, without the internal virtualenv that pre-commit creates.
=> Add pre-commit hooks corresponding to GitHub workflows

common/config/environment.go, resources/aws/environment.go, resources/aws/environmentDefaults.go, resources/azure/environment.go, resources/hyperv/environment.go, scenarios/aws/microVMs/microvms/run.go
Provide way to have parameter that exists on all provider with different values for each provider.
Motivation
----------
=> Create interface for parameter cross cloud providers

components/datadog/agent/kubernetes.go, components/datadog/agent/kubernetes_helm.go, components/datadog/kubernetesagentparams/params.go
Create KubernetesAgent component to install the agent on Kubernetes with Helm
Motivation
----------
Give a component to install the Agent in Kubernetes for the KindVM provider
=> APL-2847 Create KubernetesAgent component to install the agent in Kubernetes

components/datadog/agent/kubernetes_helm.go, components/datadog/fakeintake/component.go, resources/aws/environment.go, resources/aws/environmentDefaults.go, scenarios/aws/fakeintake/fakeintake.go
Use a permanent LB for FI in `agent-sandbox` and `agent-qa`, reducing IP usage, speeding up creation.
Agent routing is based on `Host` header in ALB: `<hash>.lbX.fi.<sandbox|qa>.dda-testing.com`.
A wildcard CNAME entry in Route53 allows to route `*.fi.<env>.dda-testing.com` to the LB. If we add more in the future we'll need records for `*.lbX.fi` instead.
The ALB does TLS termination and has a signed SSL cert as we have a public DNS.
Motivation
----------
=> Implement fakeintake single LB for agent-sandbox|qa

scenarios/aws/microVMs/microvms/libvirt_fs.go
This PR uses curl to download VM images instead of aria2c.
Motivation
----------
Aria2c has an [issue](https://github.com/aria2/aria2/issues/1344) when servers return range headers in a particular way, which is effecting us causing jobs in the agent CI to fail intermittently.
=> Download VM images with curl

components/datadog/apps/tracegen/images/tracegen/main.go
This PR will print the content of ECS_METADATA file on panic
aws/ecs, aws/eks
Motivation
----------
Ease debugging if needed
=> In tracegen, print ECS_METADATA_FILE on panic

components/datadog/apps/tracegen/k8s.go, scenarios/aws/eks/run.go, scenarios/aws/kindvm/run.go
This PR removes nodeselectors from tracegen. They are not necessary to schedule the pods. Originally we introduced them to schedule the workloads on identified cgroupv1 / cgroupv2 nodes but now we prefer to run all the tests on kind with either cgroupv1 or cgroupv2 AMI.
aws/eks, aws/kind
Motivation
----------
Simplify the e2e tests
=> [CONTINT-3858] Remove nodeselectors from tracegen

components/datadog/agent/ecs.go, components/datadog/apps/tracegen/ecs.go, scenarios/aws/ecs/run.go
This PR adds a tracegen to the AWS/ECS scenario. The task has placement constraints to get scheduled on either bottlerocket (cgroupv1) or linux (cgroupv2) nodegroups.
aws/ecs
Motivation
----------
We would like to test that traces and origin detection are working on ECS.
=> [CONTINT-3558 ] Add tracegen to the ECS scenario

scenarios/aws/kindvm/run.go
This PR allows us to set the OS version in kindvm scenario
aws/kind
Motivation
----------
We would like to perform e2e test on both Ubuntu-22.04 and Ubuntu-20.04
=> [CONTINT-3557] set os in kindvm scenario

Dockerfile
This PR fixes an issue that blocks building images. Downloading azure-cli will cause the error:
```
#24 0.775 Reading package lists...
#24 1.316 E: The repository 'http://apt.kubernetes.io/ kubernetes-xenial Release' does not have a Release file.
```
It is caused by the fact that this repo was deprecated yesterday.
https://forum.linuxfoundation.org/discussion/864693/the-repository-http-apt-kubernetes-io-kubernetes-xenial-release-does-not-have-a-release-file
Motivation
----------
=> Fix deprecated kubernetes repository

components/datadog/agent/host_linuxos.go, components/docker/docker.go, components/kubernetes/kind.go
Add `-fsS --retry 10` options to curl command
host, docker, kind
Motivation
----------
We see weird failures at agent install, failing at the create config file step, while curl reports "empty server response". I suspect the command does not return an error code. Adding these options everywhere to have more infos in logs and to uniform curl usage.
=> Add silent, show-error, fail and retries to curl commands

components/datadog/apps/nginx/ecs.go, components/datadog/apps/nginx/ecsFargate.go, components/datadog/apps/redis/ecs.go, components/datadog/apps/redis/ecsFargate.go
Remove LBs from `nginx` and `redis` on ECS/Fargate.
On ECS EC2 it's replaced by `links`.
On ECS Fargate we share network namespace, so localhost.
Motivation
----------
=> ECS nginx/redis without LBs

components/datadog/agent/ecs.go, components/datadog/apps/dogstatsd/ecs.go, components/datadog/apps/dogstatsd/images/dogstatsd/go.mod, components/datadog/apps/dogstatsd/images/dogstatsd/go.sum, components/datadog/apps/dogstatsd/images/dogstatsd/main.go, components/datadog/apps/dogstatsd/k8s.go
This PR:
- Adds dogstatsd in the k8s scenario without DD_ENTITY_ID
- Adds dogstatsd in the ECS scenario
- Changes the statsd library used by dogstatsd to include the origin detection bugfix
aws/eks aws/kind aws/ecs azure/aks
Motivation
----------
=> [CONTINT-3906] Add workloads for dogstatsd origin detection

components/datadog/dockeragentparams/params.go
Configure agent to use http and / or skip ssl validation based on the fakeintake scheme
Docker
Motivation
----------
In inicident-25877 we introduced a bug as we considered using fakeintake with https schema only. Fakeintake can have either an http or https schema, based on how it is deployed. For high throughput scenarios we use a LB in front of the fakeintake to handle OOM. This issue was first introduced by  https://github.com/DataDog/test-infra-definitions/pull/661#pullrequestreview-1916434855 
=> [docker] enforce http on fakeintake with http scheme

components/datadog/agent/host.go, components/datadog/agent/host_linuxos.go, components/datadog/agent/host_os.go, components/datadog/agent/host_windowsos.go, components/datadog/agentparams/msi/install_params.go, components/datadog/agentparams/params.go
This PR adds a parameter to the `getInstallCommand` function that allows the caller to pass additional, installer/platform specific parameters.
For now, only the Windows (and more specifically, the Windows Domain) tests.
Motivation
----------
It's not possible to install the Agent on a Domain Controller without specifying the `DDAGENTUSER_NAME` and `DDAGENTUSER_PASSWORD` parameters to the MSI.
=> Allow passing additional parameters to the installer

components/datadog/agent/host_linuxos.go
Using `--retry` with curl only retries errors that `curl` consider as transient. Only timeouts and 5xx errors.
We want to retry more error than that to avoid flakes. For example the `SSL_ERROR_ZERO_RETURN` error
Motivation
----------
=> fix(install-script): Fix curl retry to reduce flakiness

components/kubernetes/kind.go, integration-tests/invoke_test.go, integration-tests/testfixture/config.yaml, scenarios/aws/kindvm/run.go, tasks/__init__.py, tasks/kind.py
* fix kind install command
* use AmazonECS family OS by default for Kind
* adds inv create-kind task
* adds integration test for kind
kind
Motivation
----------
I broke kind install command with https://github.com/DataDog/test-infra-definitions/pull/671, this PR fixes it and adds an integration test for kind vm
I tried to run tests in parallel with `t.Parallel` in subtests, but it failed, might race on config file. To be investigated.
=> [kind] fix kind deployment

components/datadog/agentparams/params.go, components/datadog/dockeragentparams/params.go, components/datadog/kubernetesagentparams/params.go
Set the Pulumi dependency between fakeintake and agent to avoid flakiness in test
It changes a bit the effect of `WithPulumiResourceOptions` to make sure we do not override  Pulumi dependencies added by `WithFakeintake`
Motivation
----------
=> Fix(e2e): Set dependencies correctly to reduce test flakiness

components/datadog/agent/kubernetes_helm.go
This check reduces the refresh period of the sbom and container image checks
All k8s scenarios
Motivation
----------
=> [CONTINT-3776] Change refresh period of the SBOM and container image checks

.pre-commit-config.yaml, components/datadog/apps/cpustress/k8s.go, components/datadog/apps/dogstatsd/k8s.go, components/datadog/apps/mutatedbyadmissioncontroller/k8s.go, components/datadog/apps/nginx/k8s.go, components/datadog/apps/prometheus/k8s.go, components/datadog/apps/redis/k8s.go, components/datadog/apps/tracegen/k8s.go, components/datadog/dogstatsd-standalone/k8s.go, components/kubernetes/component.go
* Return `pulumi.ComponentResource` from k8s deployment app definitions
eks, kind
Motivation
----------
We are adding custom workloads to Kind provider in datadog-agent side, we need a common type for the deployment functions to allow adding custom apps to the deployment through a `WithWorkloadApp` in https://github.com/DataDog/datadog-agent/pull/23632
=> [apps] use common signature for k8s apps

components/datadog/agent/host.go, components/datadog/agentparams/params.go
The framework implicitly adds an api key to the agent config.
This PR adds an option to disable that behavior, leaving the user responsible for adding the api key by itself.
Agent E2E tests.
The default behavior is unchanged.
Motivation
----------
Testing various features around the secret refresh of the API key requires having a dynamic API key. 
=> [ASCII-1318] Add `WithSkipAPIKeyInAgentConfig` option

components/datadog/agent/kubernetes_helm.go
Create a `priorityClass` for the agent.
* `aws/eks`
* `aws/kindvm`
Motivation
----------
In the `datadog-agent` repository, the `TestEKSSuite` suite is currently flaky and fails to complete the pulumi stack creation from time to time with following error:
```
resource "urn:pulumi:ci-30352959-4670-eks-cluster::e2eci::pulumi:providers:kubernetes$dd:apps$kubernetes:apps/v1:Deployment::dogstatsd-uds-8125" was successfully created, but the Kubernetes API server reported that it failed to fully initialize or become live: 'dogstatsd-uds' timed out waiting to be Ready
```
It turned out that the `dogstatsd-uds` pod remain in `ContainerCreating` forever:
```
NOMINATED NODE   READINESS GATES …
```
=> [CONTINT-3935] Create a priorityClass for the agent

components/datadog/apps/tracegen/k8s.go
Fix `DD_TRACE_AGENT_URL` value in the k8s definition of tracegen
APM scenario on k8s + UDS
Motivation
----------
Bug fix
=> Fix DD_TRACE_AGENT_URL in the k8s UDS scenario

Dockerfile
Increase verbosity at `pulumi plugin install` command, to improve investigation experience when a plugin is not installed
None
Motivation
----------
A plugin whom go dependency is in `go.mod` is not installed automatically with the runner, the error was hidden in default pulumi plugin install output, this PR helps further investigations 
=> [dockerfile] increase verbosity in pulumi plugin install command

scenarios/aws/microVMs/config/config.go, scenarios/aws/microVMs/microvms/run.go
This PR adds a configuration option to select if provisioning microvms is required.
Motivation
----------
When testing new images, it can be useful to turn provisioning off to reduce wait time in case of boot failures.
=> Only provision microvms if required

.github/workflows/auto-bump-datadog-agent.yml
This PR add a new github action workflow to automatically creates the test-infra bump PR on datadog-agent when the PR is merged
Example auto bump PR: https://github.com/DataDog/datadog-agent/pull/23989
Thanks @julien-lebot for the invoke task bumping test-infra on datadog-agent side 🙇 
Motivation
----------
I tried to use the action to create a PR that can be modified by the user while being automatically updated by the action when new changes are added to the test-infra PR. But it does not work since the action by design always force push to the created branch
=> CI(auto-bump): Automatically create test-infra bump PR on datadog-agent

components/datadog/agent/host_linuxos.go, components/datadog/agent/host_windowsos.go, components/datadog/agentparams/params.go, components/datadog/agentparams/params_test.go, components/datadog/agentparams/version.go
Change the default version of the datadog-agent package used from latest stable to latest nightly.
Users running e2e tests locally prefer to have a version of the agent closer to their changes. Latest stable can be quite different from the latest main version of the agent. Latest nightly is closer to the current main state
Motivation
----------
=> Use latest nightly version of the agent instead of stable as default

components/datadog/agent/kubernetes_helm.go
This PR enables host sbom collection in k8s
aws/eks aws/kind
Motivation
----------
We recently discovered agent panics following a dependency bump when host sbom was enabled.
=> Enable host sbom collection in k8s

components/datadog/apps/dogstatsd/images/dogstatsd/go.mod, components/datadog/apps/dogstatsd/images/dogstatsd/go.sum
This PR replaces the dogstasd version to run with https://github.com/DataDog/datadog-go/pull/304.
It fixes origin detection on Amazon Linux ECS Optimized
all using dogstatsd
Motivation
----------
From my test, the containerid is now retrieved properly. I used a modified dogstatsd app that prints the content of the message:
```
[ec2-user@ip-10-1-56-42 ~]$ k -n workload-dogstatsd logs dogstatsd-udp-origin-detection-85b7dd9944-flk4c
2024/03/18 11:39:50 page.views:1|c|c:27b8312e67ae6bf568fdd350d44009785d07916bd3d115fb9f8d0fb6fba313c5
[ec2-user@ip-10-1-56-42 ~]$ k -n workload-dogstatsd get pod dogstatsd-udp-origin-detection-85b7dd9944-flk4c -o yaml | grep -i …
```
=> [CONTINT-3937] Replace Dogstatsd library version to work with amazon linux

components/datadog/apps/nginx/k8s.go
* In the `spec` of `HorizontalPodAutoscaler`, use `Value` instead of `AverageValue` because the query in the `DatadogMetric` is already computing an average (`avg:` operator at the beginning of the query).
As a result, the total number of TPS was wrongly divided twice by the number of pods (once by datadog because of the `avg` operator in the query and once [by the HPA](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/#algorithm-details) itself)
* Reduce the [stabilization windows](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/#stabilization-window) because:
* We want the HPA to be as reactive as possible in the context of e2e to detect scale up and scale down events as fast as possible …
=> Fix HPA settings to make them more reactive

.github/workflows/docker-publish.yml, components/datadog/apps/netflow-generator/images/netflow-generator/Dockerfile
Add netflow-generator workload app.
This is simply a repackaging of networkstatic/nflow-generator so we can pull the image from our own registry to avoid any Docker Hub rate limits.  It will initially only be used in a docker environment by a new ndm/netflow new-e2e test.
Motivation
----------
=> Add netflow-generator workload app.

.github/workflows/docker-publish.yml
Bump cosign to 2.2.3
None
Motivation
----------
A recent change in cosign caused our signature action to fail on main, we bump to v2.2.3 as suggested by https://blog.sigstore.dev/tuf-root-update/
=> [github] bump cosign to 2.2.3

components/datadog/updater/install_script.sh
Add default config to avoid permanent crashes of datadog-agent and datadog-updater units
E2E that use agent configuration + real api keys are left to the datadog installer
=> [updater] Add default config

components/datadog/agent/kubernetes_helm.go, components/datadog/apps/mutatedbyadmissioncontroller/k8s.go, scenarios/aws/eks/run.go, scenarios/aws/kindvm/run.go, scenarios/azure/aks/run.go
This PR configures APM lib injection in a specific namespace. It also creates a couple of deployments in that namespace. One specifies the library in an annotation and the other one doesn't and relies on language detection instead.
=> [components/datadog] Add deployments with APM instrumentation

scenarios/aws/microVMs/microvms/provision.go
Ensures that the `/etc/docker` folder exists before trying to write the config file.
Only microvms.
Motivation
----------
Fixing errors where the folder not existing caused setup to fail.
Validated in pipeline https://gitlab.ddbuild.io/DataDog/datadog-agent/-/pipelines/31535952
=> [KMT] Ensure docker config folder exists

components/datadog/updater/install.go, components/datadog/updater/install_script.sh
This PR adds basic support for RPM for updater tests
All remote updater scenarios, which can now run on RHEL derivatives
Motivation
----------
=> Add basic RPM support to the updater tests

scenarios/aws/microVMs/microvms/resources/distro/domain-arm64.xsl
Motivation
----------
Amazon linux 2023 arm64 VMs require ACPI to boot.
=> Enable ACPI for arm64 VMs

components/datadog/agent/kubernetes_helm.go
Increase the `ec2_metadata_timeout` agents setting.
* `aws/eks`
* `aws/kindvm`
Motivation
----------
[Some flaky tests are still failing because of missing `kube_cluster_name` tag](https://gitlab.ddbuild.io/DataDog/datadog-agent/-/jobs/479757337).
This is follow-up of #741 which attempted to fix the issue for the cluster-agent.
But it seems that [the node agents experience the same issue](https://dddev.datadoghq.com/logs?query=host%3Ai-06bc4e6e7a15a1247%20service%3Aagent%20container_id%3A8017478f98eb20da7ffdbc5dd3285c72f5f1146b60790e11c38f16decf0fd733%20filename%3A0.log%20&agg_q=host&agg_q_source=base&cols=matches%2Cvolume%2Ccontainer_name%2Cmessage&context_event=AY6v2j-MAACBcC4e9nUYQgAN&event …
=> Increase `ec2_metadata_timeout` to avoid timeouts causing flakiness

components/datadog/updater/install_script.sh
Renames the `u7` pattern from updater repo to `i7` since we're renaming to tool `installer`
Motivation
----------
=> rename installer repos pattern from u7 to i7

scenarios/aws/microVMs/microvms/domain.go
This PR adds vcpu and memory configured for a VM to the resource generating its volume overlay. This allows us to create multiple versions of the same VM varying either the vcpu or memory.
Motivation
----------
=> Fix varying VMs over vcpu and memory

components/datadog/updater/install_script.sh
- fix1: gpg is not installed by default on debian, this installs gpg first before calling it (gnupg is the package), this allows debian testing
- fix2: move the arch rewrite hack only on debian case, this allows redhat arm testing
```
invoke create-vm -i -o=debian --install-updater --pipeline-id=31757018  --no-verify
invoke create-vm -i -o=ubuntu --install-updater --pipeline-id=31757018  --no-verify  --architecture=arm64
invoke create-vm -i -o=centos --install-updater --pipeline-id=31757018 --no-verify
invoke create-vm -i -o=redhat --install-updater --pipeline-id=31757018 --no-verify  --architecture=arm64
```
=> Allow installer debian test

components/datadog/updater/install_script.sh
**NB** The install script was flaky as it would work on reused hosts, I messed up destroying + spawning new VMs in the previous PR  https://github.com/DataDog/test-infra-definitions/pull/752
Changes
- remove unused lines from the script to simplify
- add a non empty api key to avoid trace-agent crashing
- debian arch override early
- set key ring at the right time
- cleanup datadog-updater
Testing
```
invoke create-vm -i -o=debian --install-updater --pipeline-id=31792911 --architecture=arm64  --no-verify
invoke create-vm -i -o=debian --install-updater --pipeline-id=31792911 --no-verify
```
=> Fix installer install script + cleanup

components/datadog/apps/dogstatsd/k8s.go
This PR renames the container name for the new dogstatsd workload.
All k8s scenarios
Motivation
----------
It will be much easier to test. Indeed, all other workloads use `dogstatsd` as container name so in the datadog-agent code base we can reuse more of the code
=> Rename container name for dogstatsd workload

components/datadog/updater/install_script.sh
-y is only available in rug compatibility mode, which we don't enable. Switch to '-n' for '--non-interactive' which is always available
Fix an incorrect change introduced in #765 
Motivation
----------
=> updater: fix zypper non-interactive mode arguments

components/datadog/agent/host.go, components/datadog/agentparams/filepermissions/permissions.go, components/datadog/agentparams/filepermissions/permissions_nix.go, components/datadog/agentparams/params.go, go.mod, go.sum
Add a way to specify permissions when creating a file. Only on Unix for now but will follow up for Windows permissions 
Example PR: https://github.com/DataDog/datadog-agent/pull/24723
Any scenarios that needs to set specific permissions to a file. 
Motivation
----------
Currently to test secret feature, we need to do the following:
1. UpdateEnv without the Agent config
2. Give permissions to the secret script
3. UpdateEnv with the Agent config
In the first UpdateEnv, we can add the secret script file but we cannot give it the right permissions. So if we set `secret_backend_command` directly the Agent won't be able to start and the first UpdateEnv will fail.
=> Add WithFileWithPermissions to create files with predefined permissions

components/datadog/apps/mutatedbyadmissioncontroller/k8s.go
Avoid DockerHub rate limit on images already synced from DockerHub `/library`.
Motivation
----------
=> Use public ecr until we have good support of private mirror

components/kubernetes/kind-cluster.yaml
The system-probe container needs access to the host's `proc` filesystem for some modules to work properly (CWS).
This PR updates the kind node configuration to mount the host `/proc` into the container so that it can be further propagated to the system-probe container.
Motivation
----------
=> [kind] mount host proc into kind node

.gitlab-ci.yml, repository.datadog.yaml
Disable gitlab pipeline on mergequeue
None
Motivation
----------
The mergequeue default configuration expects a gitlab pipeline. Currently we on gitlab we build the runner image and test it, which is not required on the mergequeue. Let's skip it using a custom mergequeue definition
=> [ci] disable gitlab pipeline on mergequeue

components/datadog/updater/install_script.sh
Adds default installer config when none is set
new-e2e-installer
Motivation
----------
Trace agent can't start without the `api_key` field set
=> fix(installer): Add default config

components/datadog/agentparams/filepermissions/permissions_win.go
Equivalent of https://github.com/DataDog/test-infra-definitions/pull/762 for Windows
Any scenarios that needs to set specific permissions to a file. See [usage example](https://github.com/DataDog/datadog-agent/pull/24829/files)
Motivation
----------
ASCII-1491
Currently to test secret feature, we need to do the following:
1. UpdateEnv without the Agent config
2. Give permissions to the secret script
3. UpdateEnv with the Agent config
In the first UpdateEnv, we can add the secret script file but we cannot give it the right permissions. So if we set secret_backend_command directly the Agent won't be able to start and the first UpdateEnv will fail.
I started to work on structures containing ACE …
=> Add WindowsPermissions structure that can be used with WithFileWithPermissions

common/utils/yaml.go
Fixes the `utils.MergeYAML` function which was unmarshalling `oldValuesYamlContent` into the wrong variable.
Motivation
----------
=> fix utils.MergeYaml function unmarshalling yaml data into the wrong variable 

.github/CODEOWNERS
Updated `.github/CODEOWNERS` file chaning the ownership of test apps owned by @DataDog/agent-metrics-logs 
None.
Motivation
----------
Speed up development.
None.
=> Updating CODEOWNERS with AML owned apps

components/datadog/agent/kubernetes_helm.go
Increase the CPU limit of the agents.
* `aws/eks`
* `aws/kind`
Motivation
----------
#791 Introduced CPU and memory resources requests and limits for the agent based on their nominal resource consumption.
Since then, we observe some restarts of the cluster checks runners from time to time.
This is because they are consuming much more CPU at their startup than in average.
So, let’s increase the CPU requests and limits of all the agents so that they are not starved at startup.
=> Increase the CPU limit of the agents to avoid starvation at startup

components/docker/docker.go
Remove `DeleteBeforeReplace` that should not be needed, as `docker-compose up` must handle updates. This is a try to fix APM test that run `UpdateEnv` to update environment variables between two tests.
cf ADXT-226
Motivation
----------
=> Let docker-compose up handle the diff instead of forcing down on each change

components/datadog/agent/ecs.go, components/datadog/agent/ecsFargate.go, components/datadog/agent/kubernetes_helm.go
Fix the collection of agent telemetry data (metrics under `datadog.agent`)
* `aws/ecs`
* `aws/eks`
* `aws/kind`
Motivation
----------
Agent telemetry is currently not working.
We would need it to diagnose some cases of test failure.
=> Fix the collection of agent telemetry

components/datadog/agent/kubernetes_helm.go, tasks/kind.py
Increase the CPU and memory resources allocated to the agent.
* `aws/eks`
* `aws/kind`
Motivation
----------
Despite #799, we still have some instabilities due to agent restarting because they are starved.
We need to increase the resources allocated to the agent a little bit more.
=> Increase the CPU and memory limits of the agents to avoid starvation

components/docker/compose.go, components/docker/docker.go
Modify the `docker-compose` command to include a hash of the content manifest as an environment variable.
This is a workaround to stop using `Triggers` that will create a replacement (`docker-compose down` + `docker-compose up`) to avoid some flakiness we have when this happen. We now let `docker-compose` handle the update.
docker
Motivation
----------
Fix flakiness
=> Remove triggers to not force a replace on manifest change

common/config/environment.go, scenarios/aws/ec2/vm.go, tasks/config.py, tasks/doc.py, tasks/vm.py
Add a flag to create VM to let user configure the SSH user they want to use to connect to an instance. 
This can be useful when working with AMI that are not the ones we provide OOTB.
Motivation
----------
=> Make SSH user configurable

.github/workflows/lint.yml, tasks/config.py
Enforce formatting python file with ruff. It's already part of the pre-commit hooks
Motivation
----------
Same as https://github.com/DataDog/datadog-agent/pull/25359 :oopsy:
=> Enforce formatting python files with ruff

components/datadog/agent/kubernetes_helm.go, components/datadog/apps/nginx/k8s.go, components/datadog/apps/redis/k8s.go, resources/aws/eks/eniConfig.go, resources/aws/eks/nodeGroups.go, scenarios/aws/eks/run.go, scenarios/aws/kindvm/run.go, scenarios/azure/aks/run.go
Migrate Windows nodes from unmanaged to managed EKS node groups since it's been supported for some months.
This PR also fixes deployment sequence on EKS:
```
nodes -> agent -> workloads requiring CRDs
-> workloads not requiring CRDs
```
EKS
Motivation
----------
Align Windows nodes on Linux nodes
Getting rid of unmanaged node groups as not required anymore.
=> Move EKS Windows nodes to managed nodegroups

.github/workflows/lint.yml
Use the main requirements file to run the Python linters
Motivation
----------
We moved the dependencies to the main file https://github.com/DataDog/datadog-agent-buildimages/pull/585
=> Use the main requirements file to run the Python linters

tasks/ci.py
Fix auto bump PR message. When a PR is closed it will now write a comment with the link to the PR that should replace the closed PR
Motivation
----------
=> Fix message for auto close

components/command/filemanager.go, components/command/osCommand.go, components/command/runner.go, components/command/unixOSCommand.go, components/command/windowsOSCommand.go
Add the ability to transfer files to system folders copying it to `/tmp` and then copying it to the right destination using `sudo`. 
Note that this is a bit less efficient, it's not great but it works
All linux ones that copy files.
Motivation
----------
- Address https://datadoghq.atlassian.net/wiki/spaces/AW/pages/3659661423/Known+E2E+issues+idiosyncrasy#Permission-denied-during-SFTP-operations
- Part 1 of https://datadoghq.atlassian.net/browse/ADXT-228
- In a follow-up PR I'll address the encoding issue by creating a local file and using scp to send it instead of using `stdin`
=> Add the ability to transfer files to system folders

components/kubernetes/kind.go, resources/local/environment.go
Create a new `local` environment that implements `config.Env`.
It can be useful to create provider that are made to be used locally
Local scenarios
Motivation
----------
=> Add a local environment that implements config.Env interface

components/datadog/updater/install_script.sh
Replaces i7 testing repository by a7
Requires https://github.com/DataDog/datadog-agent/pull/25811
Installer ones
Motivation
----------
See https://github.com/DataDog/datadog-agent/pull/25811
=> fix(installer): Use a7 instead of i7

components/command/filemanager.go, components/command/osCommand.go, components/command/runner.go, components/command/unixOSCommand.go, components/command/windowsOSCommand.go, components/datadog/agent/host.go, components/docker/component.go, components/kubernetes/kind.go
Use CopyFile in the CopyInlineFile to avoid encoding issues
All the scenarios since they all use the `CopyInlineFile` to at least create the Agent config remotely.
Motivation
----------
We currently use commands in order to create a file from a string. This approach causes some issues with the encoding sometimes. To avoid them, we first create a temporary file locally that we then copy using Pulumi to avoid altering the content. 
CopyFile can now [transfer files to system folders](https://github.com/DataDog/test-infra-definitions/pull/830) so this should not be a problem.
In the CopyInlineFile, I first get the content of the StringInput through the ApplyT …
=> Use CopyFile in the CopyInlineFile to avoid encoding issues

.github/workflows/docker-publish.yml, components/datadog/apps/netflow-generator/images/netflow-generator/Dockerfile
Following [this PR](https://github.com/DataDog/datadog-agent/pull/26066) this image has became useless, we can remove it
Motivation
----------
=> [NDM][NDMII-2815] remove useless image

components/command/filemanager.go, components/command/unixOSCommand.go
Use the full path in the resource name to avoid conflicts
Most of them since they use copy files
Motivation
----------
We currently use the filename, which is a problem since some tests might create several files with the same name but in different folders. For instance [here](https://github.com/DataDog/datadog-agent/blob/main/test/new-e2e/tests/agent-subcommands/flare/flare_nix_test.go#L56)
Locally with two files called file but in different folders:
```
+   │  ├─ command:remote:CopyFile  remote-aws-vm-copy-/tmp/file                                                             created (1s)        
+   │  ├─ command:remote:CopyFile …
```
=> Use the full path in the resource name to avoid conflicts

components/datadog/agent/host_linuxos.go, components/datadog/agent/host_windowsos.go, components/datadog/agentparams/params.go, components/datadog/agentparams/params_test.go, components/datadog/updater/install_script.sh
Same as https://github.com/DataDog/test-infra-definitions/pull/845 but without breaking everything this time. 
The `pipeline-` is ONLY in the struct, not everywhere like I originally did.
Motivation
----------
=> Remove `pipeline-` from the `pipelineID` parameter

components/command/unixOSCommand.go
Use `DeleteBeforeReplace` when moving files
Motivation
----------
Currently when we create a file that does not exist remotely, we:
1. Backup the file existing file (if any), 
2. Move the file
When we try to replace a file that already exists we use a `replace`, which runs the `deleteCommand`, which brings back the backup file after moving the new file to the location. So in the end we get the exact same content for this file.
=> Use `DeleteBeforeReplace` when moving files in `CopyFile`

tasks/ci.py
Update the workflow opening bump PRs to show PR range with commit list + changes rather than just changes.
| Before | After |
|--------|--------|
| ![image](https://github.com/DataDog/test-infra-definitions/assets/23154723/fa3f35e0-6d17-481f-93b3-e401563cad4f) | ![image](https://github.com/DataDog/test-infra-definitions/assets/23154723/9681f34b-3933-4a20-9672-7ece963fd8d4) |
Motivation
----------
It's just better 😄
=> [Auto-bump PR] Use commit range with list rather than just changes

components/command/unixOSCommand.go, components/datadog/agent/host.go
1. Restart the Agent after the config files are replaced, adding the `Host` as a dependency
2. Use `ReplaceOnChanges` when moving files
Mostly those using `UpdateEnv`
Motivation
----------
If we do not add the Host as a dependency (coming from the `opts`) so the Host will wait for the file to be moved to be done, and the Agent in turn will wait for the Host to be done
Tested locally with: 
- `aws-vault exec sso-agent-sandbox-account-admin -- deva -e new-e2e-tests.run --targets ./tests/process --run TestLinuxTestSuite/TestProcessDiscoveryCheck`
```
--- PASS: TestLinuxTestSuite (373.21s)
--- PASS: TestLinuxTestSuite/TestProcessDiscoveryCheck (37.73s)
PASS
ok …
```
=> Restart the Agent after the config files are replaced

components/datadog/agent/docker.go
Pass dependencies to the agent docker compose command
docker
Motivation
----------
updateEnv on docker compose is currently broken by this
=> [docker] pass dependencies to docker compose command

.gitlab-ci.yml
Increase resources requirements for integration-testing job on Gitlab, using values in pair with [datadog-agent's e2e.yml](https://github.com/DataDog/datadog-agent/blob/main/.gitlab/e2e/e2e.yml#L100-L102)
None
Motivation
----------
[Last execution](https://gitlab.ddbuild.io/DataDog/test-infra-definitions/-/jobs/545159821) failed on main as it was killed because of an [out of memory](https://app.datadoghq.com/notebook/8634161/ci-oom-by-runner?range=5400000&tpl_var_pod_name=runner-sz8g9p6z-project-3345-concurrent-0-nudldpbl&start=1718628294000&live=false) 😢 
=> [gitlab] increase k8s runners resources for integration-testing job

resources/aws/environment.go
We have some user still using `sandbox` to create VMs.
We do not maintain load balancer for fakeintake on sandbox so let's not call the code to randomly select one
Motivation
----------
=> Do not break sandbox where we do not have load balancers

.github/CODEOWNERS, .github/dependabot.yml, .github/workflows/docker-publish.yml, components/datadog/apps/cws/images/cws-centos7/Dockerfile
This PR migrates this image used in the CI of the agent from https://github.com/paulcacheux/cws-buildimages/blob/main/Dockerfile.cws-centos7 to a datadog owned repository.
Motivation
----------
The end goal is to use this image in KMT CWS tests.
=> [CWS] migrate `cws-centos7` image

components/os/linux.go, components/os/linux_descriptors.go, components/os/linux_servicemanagers.go, scenarios/aws/ec2/os_resolver.go
Adds AmazonLinux2018 VM. That VM runs on SysVInit and not systemd, which is useful to test in E2Es as we are supposed to test it.
Installer tests for now, maybe more if users chose to use that VM :)
Motivation
----------
Testing installer + injector on SysVInit scenarii in E2Es
Image: https://us-east-1.console.aws.amazon.com/ec2/home?region=us-east-1#ImageDetails:imageId=ami-07541a4f680f1ba8e
=> upgrade(VMs): Add AmazonLinux2018 types

go.mod, go.sum, integration-tests/invoke_test.go
Rollback `pulumi-aws` dependency
All
Motivation
----------
The bump is breaking the `fakeintake` deployment on [e2e tests](https://github.com/DataDog/datadog-agent/pull/27159) 
Added `fakeintake` deployment to integration tests. They will run longer, but will early catch such issues
=> rollback pulumi-aws to v6.25.0

scenarios/aws/ec2/os_resolver.go
use hardcoded AMI for CentOS 7, using the custom Datadog AMI
VM
Motivation
----------
incident-28477
CentOS 7 is EOL, using a custom image with the correct mirrorlist
=> [centos] use custom CentOS 7 AMI

components/datadog/agent/kubernetes.go, components/datadog/agent/kubernetes_helm.go, components/datadog/kubernetesagentparams/params.go
Add an option to disable dual shipping on Kubernetes tests.
Most of the time using dual shipping is fine but for some specific tests (process ones for example) it can be an issue if the agent take into account the response from the backend
Motivation
----------
=> Give an option to disable dual shipping

resources/aws/ecs/client.go, scenarios/aws/fakeintake/fakeintake.go
Pass the aws profile to the AWS ECS Client we use to get the fakeintake lb-less URL
All scenarios using fakeintake without LB, locally
Motivation
----------
As we introduced the profile in the pulumi aws provider, we don't need anymore to wrap our local calls to invoke tasks with `aws-vault exec ...`. We missed passing the profile to the AWS ECS Client.
=> [fakeintake] set the profile

resources/aws/environment.go
Preserve already authenticated environments, otherwise we get: 
```
Error: A Profile was specified along with the environment variables "AWS_ACCESS_KEY_ID" and "AWS_SECRET_ACCESS_KEY". The Profile is now used instead of the environment variable credentials.
```
If we wrap the command in an already authenticated session
Motivation
----------
https://github.com/DataDog/test-infra-definitions/pull/917#discussion_r1661043033
=> Preserve already authenticated environments

.gitlab-ci.yml, integration-tests/config.go, integration-tests/invoke_test.go, integration-tests/testfixture/config.yaml
This PR refactors the integration test to allow running it locally and in parallel. It increases the CI resources to avoid OOM during the test. 
None
Motivation
----------
This allows to reduce the `test-infra-definitions` pipeline time by half, from ~40 min to ~20 min
=> increase integration-tests job resources to run it in parallel

.pre-commit-config.yaml, pyproject.toml
Move the `vulture` config to the `pyproject.toml` file to make it compatible with IDEs
Motivation
----------
Same as https://github.com/DataDog/datadog-agent/pull/26916
=> Move the `vulture` config to the `pyproject.toml` file

scenarios/aws/microVMs/microvms/resources/amd64/domain.xsl, scenarios/aws/microVMs/microvms/resources/arm64/domain.xsl, scenarios/aws/microVMs/microvms/resources/distro/domain-amd64.xsl, scenarios/aws/microVMs/microvms/resources/distro/domain-arm64.xsl
This PR enables autoballooning with automatic deflation in KMT VMs. 
microVMs
Motivation
----------
Reduce memory usage of the VMs, reducing the chances of out of memory errors.
Validated [in the agent](https://gitlab.ddbuild.io/DataDog/datadog-agent/-/pipelines?ref=guillermo.julian/kmt-autoballoon), and checked in manual stacks and CI that minimum free memory goes from ~2GB in the worst case to ~10GB with these changes.
This PR also adds indentation to the XSL files.
=> Enable autoballooning in KMT instances

scenarios/aws/microVMs/microvms/files/oom_kill.yaml, scenarios/aws/microVMs/microvms/files/system-probe.yaml, scenarios/aws/microVMs/microvms/run.go
This PR enables the OOM killer integration in the KMT microVMs, so that we can monitor OOM kills due to memory pressure in CI.
microVMs
Motivation
----------
Improved visibility into the instances used for CI
Validated in https://gitlab.ddbuild.io/DataDog/datadog-agent/-/pipelines/38356928
=> Enable oom_kill integration in microVMs agent

.gitignore, .gitlab-ci.yml, .vscode/settings.json, dist/Pulumi.yaml, integration-tests/invoke_test.go, tasks/deploy.py, tasks/tool.py
* Build `main.go` pulumi program before running integration tests
None
Motivation
----------
Running pulumi on the CI requires big runners, both in e2e tests in `datadog-agent` and here when calling invoke tasks to create remote instances, in `integration_tests`. 
@AliDatadog  few months ago noticed how the high mem consumption in e2e tests is requested at compile time. This happens both when running e2e tests in `datadog-agent` and when running integration_tests in test-infra-definitions. 
[I recently added](https://github.com/DataDog/test-infra-definitions/pull/916) `fakeintake` to `integration_tests` as a `pulumi-aws` bump broke its usage in `datadog-agent` e2e tests. This further …
=> [gitlab] pre-build pulumi go program

components/datadog/agentparams/params.go
Add missing backend endpoints override for fakeintake.
Motivation
----------
The `diagnose` e2e test is failing for those two endpoints because the test actually reaches the real backend instead of the fakeintake.
=> [ASCII-1996] Add missing fakeintake config override

scenarios/aws/microVMs/microvms/run.go
This PR specifies the automatic shutdown time with the user data script, which runs on boot.
Motivation
----------
In some cases the the setup scenario can fail after the instance is launched but before the automatic shutdown is scheduled. This causes KMT to leak instances.
=> Schedule shutdown with user data script

.gitlab-ci.yml, README.md, components/datadog/dockeragentparams/params.go, integration-tests/invoke_test.go, resources/azure/compute/vm.go, resources/azure/environment.go, resources/azure/environmentDefaults.go, scenarios/azure/compute/vm.go, tasks/__init__.py, tasks/aws.py, tasks/az.py, tasks/config.py, tasks/deploy.py, tasks/setup.py, tasks/tool.py, tasks/vm.py
- Add two new tasks `az.create-vm` and `az.destroy-vm` to create VMs with the Agent in Azure. They are currently very basic and do not have all the parameters the AWS counterpart has but we'll add them in future PRs to keep this PR readable. 
- This is limited to Linux for now
- Update the `setup` task to include the new parameter for Azure. We have also a key parameter for AWS thsat could be merged in a follow-up PR
- Deprecate the `create-vm` and `destroy-vm` tasks in favour of `aws.create-vm` and `aws.destroy-vm`. The old commands still work. they print a deprecation message and redirect to the new version
- Add an integration test for Azure with all the requirements to run it from the CI
- We currently use the `deploy` function as is, where …
=> Add two tasks to create and destroy VM stacks in Azure

tasks/__init__.py, tasks/aks.py, tasks/aws/__init__.py, tasks/aws/docker.py, tasks/aws/ecs.py, tasks/aws/eks.py, tasks/aws/installer.py, tasks/aws/kind.py, tasks/aws/vm.py, tasks/azure/__init__.py, tasks/azure/aks.py, tasks/azure/vm.py, tasks/deploy.py, tasks/docker.py, tasks/ecs.py, tasks/eks.py, tasks/installer.py, tasks/kind.py, tasks/vm.py
Migrate all the commands that are provider-specific to a specific package:
- `create-vm` and `destroy-vm` to `aws.create-vm` and `aws.destroy-vm`
- `create-docker` and `destroy-docker` to `aws.create-docker` and `aws.destroy-docker`
- `create-kind` and `destroy-kind` to `aws.create-kind` and `aws.destroy-kind`
- `create-ecs` and `destroy-ecs` to `aws.create-ecs` and `aws.destroy-ecs`
- `create-eks` and `destroy-eks` to `aws.create-eks` and `aws.destroy-eks`
- `create-installer-lab` and `destroy-installer-lab` to `aws.create-installer-lab` and `aws.destroy-installer-lab`
- `create-aks` and `destroy-aks` to `az.create-aks` and `aws.destroy-aks`
Old commands are deprecated and not removed (yet). They will print a warning and redirect to the new …
=> Move the aws tasks into the aws package

scenarios/aws/fakeintake/fakeintake.go, scenarios/aws/fakeintake/params.go
Add a flag that allow user to enable fakeintake forwarding payloads to dddev.
In a second time we could make it the default behavior
Motivation
----------
=> Add a flag to enable dddev-forwarding

.gitlab-ci.yml, integration-tests/invoke_test.go, integration-tests/testfixture/config.yaml, resources/azure/environmentDefaults.go
Enable integration tests for Azure in the CI
- The app was created in https://github.com/DataDog/cloud-inventory/pull/20422 and https://github.com/DataDog/cloud-inventory/pull/20461 with the help of the #cloudops team.
- The secret was manually created by the cloudops team. I added an alert for the expiration, which is in 2 years
Motivation
----------
I'll store the secret in the Agent Platform 1password vault
=> Enable integration tests for Azure in the CI

Dockerfile
Install the Python dependencies directly in the docker image. It also fix the issues we had [here](https://gitlab.ddbuild.io/DataDog/test-infra-definitions/-/jobs/581470803) because of the way the dependencies are resolved.
None
Motivation
----------
We faced some issues related to building `pyperclip` in the `integration-testing` job, which is running later. Installing the dependencies in the Docker image saves us some time to debug issues on that front
=> Install the Python dependency directly in the docker image

tasks/setup.py
Add check at setup time to ensure az and aws cli are installed
None
Motivation
----------
I did not have az cli installed, don't think it comes by default on our laptops. Better to warn contributors inline.
=> [task] return error if aws or az cli are not installed

tasks/setup.py
Improve handling of RSA keys in `inv setup.debug` 
Fix `ssh-keygen` output parsing, loop over each line, add additional format.
Add check to ensure `privateKeyPath` and `publicKeyPath` match.
N/A
Motivation
----------
RSA keys are required to decrypt Windows/RDP credentials, so the output from `inv setup.debug` should make sense for them.
In `setup.debug` helper, the `in_ssh_agent` method was not looping over the output from `ssh-add -l`, so it was only comparing the fingerprint to the first key in the ssh agent.
It doesn't seem possible to match RSA public keys to their AWS counterparts. The SHA1 fingerprint output by `ssh-keygen` does not match the …
=> Improve handling of RSA keys in setup.debug

tasks/aws/deploy.py, tasks/aws/docker.py, tasks/aws/ecs.py, tasks/aws/eks.py, tasks/aws/installer.py, tasks/aws/kind.py, tasks/aws/vm.py, tasks/azure/vm.py, tasks/deploy.py
Extract AWS-specific parts from the common deploy function
Motivation
----------
We now support Azure and it would be better to stop doing all these steps that are specific to AWS when spinning up resources on Azure
=> Extract AWS-specific parts from the common deploy function

components/datadog/agent/kubernetes_helm.go, components/datadog/apps/nginx/k8s.go
[CONTP-258](https://datadoghq.atlassian.net/browse/CONTP-258) 
Add namespaceLabelsAsTags and namespaceAnnotationsAsTags to k8s config
k8s provider in kindvm
Motivation
----------
We don’t have any e2e test that uses “namespace labels as tags” and “namespace annotations as tags”.
It’d be good to add a simple test to notice if we accidentally break these features. 
Both configs are supported in [helm charts](https://github.com/DataDog/helm-charts/blob/main/charts/datadog/templates/_components-common-env.yaml#L41-L47).
inv create-kind
[CONTP-258]: https://datadoghq.atlassian.net/browse/CONTP-258?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIj …
=> [CONTP-258] add namespace labels and annotations

components/datadog/agent/kubernetes_helm.go
We need the new `KubernetesAgent` component to be parent of all the resources created in it, otherwise the creation of these resource will not be waited before creating the workload. This should fix it by removing the `pulumi.Parent` that were changing the parent to 
Motivation
----------
=> Try to fix depdency issue with Helm refactor

resources/azure/environment.go
Azure's counterpart of https://github.com/DataDog/test-infra-definitions/pull/917. I know this is a hack but:
- We can not easily use OIDC because we can't set the parameters in a public repo
- I tried `NewInteractiveBrowserCredential` from [the azure SDK](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/azidentity#NewInteractiveBrowserCredential) to get the token. Unfortunately I can't use it with the pulumi's SDK: https://github.com/pulumi/pulumi-azure-native/issues/565
The idea is to automatically run `az login` if needed so users don't have to wrap their commands on their side. 
Azure scenarios only! We currently don't have any 
Motivation
----------
Avoid asking people to …
=> Automatically log in Azure if needed

tasks/aws/common.py
Set ubuntu as default OS family for AWS
Motivation
----------
It used to be the default but we changed it by mistake
=> Set ubuntu as default OS family for AWS

tasks/setup.py
Adds `'C:\\Program Files (x86)\\Pulumi'` to the process env if pulumi is not found on the path.
Motivation
----------
Previously had `'C:\\Program Files (x86)\\Pulumi\\bin'` but an update seems to have moved it, or maybe I was just wrong the first time. get-pulumi [install.ps1](https://github.com/pulumi/get.pulumi.com/blob/0e87dd6fd35abfc22dd0bfc0db1cfe8b0b4df421/dist/install.ps1#L58) still has `bin` in the path so idk what happened.
=> add another pulumi install dir for windows

components/datadog/apps/cws/images/cws-centos7/Dockerfile, components/datadog/apps/cws/images/cws-centos7/vault.repo.aarch64, components/datadog/apps/cws/images/cws-centos7/vault.repo.x86_64
This PR fixes the build of the `cws-centos7` image. The default centos 7 repository is not there anymore (because of EOL status) so we are moving to the vault repository.
Motivation
----------
=> cws-centos7: move to vault repository

.github/workflows/build.yml, .github/workflows/docker-publish.yml, .github/workflows/lint.yml
Reset workflow permissions to validate we can enable Read-only default permissions at repository level to provide a strong baseline protection measure
Github workflows
Motivation
----------
Github token permissions should follow the [least privilege principle](https://datadoghq.atlassian.net/wiki/x/TIVE6Q)
[Jira](https://datadoghq.atlassian.net/browse/ACIX-407?atlOrigin=eyJpIjoiMDU2M2QxNTM0NTgzNGUwZTg3NDc1YjIwZmJlMzk4NTciLCJwIjoiaiJ9)
=> feat(github): Force default permissions of GITHUB_TOKEN

scenarios/aws/microVMs/microvms/resources/distro/domain-arm64.xsl
Fixes the XSL template for local arm64 microVMs. In #933 it was changed, adding another template matcher for the `/domain/devices` path. Apparently, this overwrites previous matchers silently, and the result is that the command-line options for QEMU are not applied, which caused VMs to not boot properly.
Motivation
----------
=> Fix microVMs template overwriting

components/datadog/agent/kubernetes_helm.go, components/datadog/agent/kubernetes_helm_utils.go, components/datadog/apps/nginx/k8s.go
- Modifies helm installation of the agent to set `kubernetes_resources_labels_as_tags` and `kubernetes_resources_annotations_as_tags` on the agents.
- Add some labels and annotations to nginx workload.
- Kind
- AKS
- EKS
Motivation
----------
- E2E test the feature implemented in [this](https://github.com/DataDog/datadog-agent/pull/27369) PR.
=> Adds environment variables to the agents in helm to prepare for e2e-testing generic tagging

scenarios/azure/fakeintake/fakeintake.go, scenarios/azure/fakeintake/params.go
Add parameters to the fakeintake component on Azure
Azure ones only
Motivation
----------
- The imageUrl is a parameter on the AWS side too 
- We might add more in the future
- [We use it](https://github.com/DataDog/datadog-agent/blob/3923572cabe0f924fb81947a993dffa8a328ddd3/test/new-e2e/pkg/environments/aws/host/host.go#L121-L127) to avoid deploying the fakeintake in AWS tests and I'd like to do the same for consistency
=> Add parameters to the fakeintake component on Azure

tasks/config.py, tasks/setup.py, tasks/tool.py
Add ability to create or import an AWS key during `inv setup`, or through new invoke tests `inv setup.aws-create-keypair` and `inv setup.aws-import-keypair`, and update the config.
setup
Motivation
----------
easier setup and key rotation
example new keypair
```
$ inv setup --config-path /tmp/test-config
Pulumi is up to date: v3.129.0
Logged in to LAPTOP-J4KNN9ON as brandenclark (file://~)
🤖 Let's configure your environment for e2e tests! Press ctrl+c to stop me
Which aws account do you want to create instances on? Default [agent-sandbox], available [agent-sandbox|sandbox|tse-playground]:
Do you want to create a new key pair? [Y/N] Default [N]: Y
🔑 Key pair …
```
=> Add AWS key create/import to setup task

tasks/setup.py
fix fingerprint parsing bug (was chopping off first byte)
Match imported RSA keys by calculating public key MD5 from RSA private key 
Allow `AWS_PROFILE` as an alternative to `AWS_VAULT`
Skip `ssh-agent` assertions on Windows, since pulumi doesn't support it
troubleshooting
Motivation
----------
https://datadoghq.atlassian.net/browse/WINA-980
run with
```
inv setup.debug
```
=> Improvements to `setup.debug` task

resources/aws/ecs/fargateService.go
Set `PidMode` to `task` on ECS Fargate task with Agent
ecs
Motivation
----------
This is the [official documentation's value](https://docs.datadoghq.com/integrations/ecs_fargate/?tab=webui#process-collection) 
=> [ecs] set pidmode by default to task on fargate

scenarios/aws/fakeintake/params.go, scenarios/azure/fakeintake/params.go
Forward payloads received by the fakeintake to `dddev` by default
aws.*, azure.*
Motivation
----------
Forwarding payloads helps with investigations in case of test failures, it allows ensuring the agent sent all expected payloads after the fakeintake is removed
Tested on 4 pipelines on `datadog-agent` through one [dev pipeline](https://gitlab.ddbuild.io/DataDog/datadog-agent/-/pipelines/43243501) and one [flakes finder pipeline](https://gitlab.ddbuild.io/DataDog/datadog-agent/-/pipelines/43254782)
=> [fakeintake] enable payloads forwarding

common/utils/yaml.go, components/datadog/agent/host.go, components/datadog/agentparams/params.go
Add `WithTags` option to the host agent deployment. This PRs also handles configuration merges as deep merges, rather than string concatenations 
VM
Motivation
----------
I want to tag all payloads by the stack name to help finding them in `dddev` when they are forwarded. This helps configuring the stack name from the deployment caller 
=> [agent/host] add WithTags option

common/config/environment.go
Stop printing errors if no extraEnvVars are provided
Motivation
----------
I always get this annoying warning when it's not defined: 
```
pulumi:pulumi:Stack (dd-florent-clarret-aws-vm):
warning: Invalid extraEnvVar format: 
```
=> Stop printing errors if no extraEnvVars are provided

Dockerfile
Remove Dockerfile entrypoint that is not needed. With that we will no longer need to override the entrypoint each time we use the image
Motivation
----------
=> Remove entrypoint that is not useful

scenarios/aws/microVMs/microvms/files/datadog.yaml
Launch statsd in datadog-agent running on the host metal instance.
microvms scenario
Motivation
----------
Write custom collectors to emit metrics to the backend.
https://github.com/DataDog/datadog-agent/pull/29099
=> Launch statsd in datadog-agent

README.md, integration-tests/testfixture/config.yaml, scenarios/gcp/compute/run/vm_run.go, tasks/__init__.py, tasks/config.py, tasks/gcp/__init__.py, tasks/gcp/common.py, tasks/gcp/doc.py, tasks/gcp/vm.py, tasks/setup.py
Add the tasks to run VMs on GCP
- `inv gcp.create-vm`
- `inv gcp.destroy-vm`
They work the same way Azure and AWS commands work
Motivation
----------
GCP is now available
To make it work, you need to log in manually for now:
- Run `gcloud auth application-default login`
- or with a service account `export GOOGLE_CREDENTIALS=<path-to-credentials.json>`
=> Add the tasks to run VMs on GCP

.gitlab-ci.yml
Configure the CI to run tests on GCP
Motivation
----------
We're adding support for GCP
- https://www.pulumi.com/registry/packages/gcp/service-account/
- I manually created the secret the same way the other credentials are configured
=> Configure the CI to run tests on GCP

common/utils/yaml_test.go
Add unit tests to the MergeYAML function
Motivation
----------
I fixed a bug in this function in https://github.com/DataDog/test-infra-definitions/pull/1067 and promised a unit test, so here it is
=> Add unit tests to the MergeYAML function

Dockerfile
Remove pyyaml 5.4.1 from the docker image
Motivation
----------
We don't use pyyaml 5.4.1 anymore and there's no need to build it with this hack anymore. We now use [6.0.2](https://github.com/DataDog/test-infra-definitions/blob/main/requirements.txt#L3) which pins cython https://github.com/yaml/pyyaml/blob/main/CHANGES#L16
=> Remove pyyaml 5.4.1 from the docker image

scenarios/aws/fakeintake/fakeintake.go
Add logs when we fail waiting for healthy fakeintake on ECS without load balancer
VM
Motivation
----------
#incident-30445
[ADXT-572](https://datadoghq.atlassian.net/browse/ADXT-572)
[ADXT-574
](https://datadoghq.atlassian.net/browse/ADXT-575)[ADXT-575](https://datadoghq.atlassian.net/browse/ADXT-575)
We had a [bunch of errors](https://gitlab.ddbuild.io/DataDog/datadog-agent/-/jobs/633325738) related to unhealthy fakeintake tasks yesterday, adding more logs to make sure the fakeintake is healthy
[ADXT-572]: https://datadoghq.atlassian.net/browse/ADXT-572?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ADXT-575]: …
=> [aws][fakeintake] log on fakeintake errors while waiting for a healthy task 

resources/aws/ecs/fargateService.go
Use public ecr image instead of Dockerhub image.
Motivation
----------
I saw some Dockerhub rate limit error on fakeintake task when we observe high fakeintake timeout failures. This is a test to see if it could be the cause of the timeouts
=> Use a public ecr image for aws fluent bit

resources/gcp/environment.go, resources/gcp/environmentDefaults.go
Differentiate regions and zones in the GCP config
Motivation
----------
We currently mix zones and regions in our config
https://cloud.google.com/compute/docs/regions-zones
=> Differentiate regions and zones in the GCP config

resources/aws/ecs/fargateService.go
Remove `task` pid mode for windows fargate tasks
ECS
Motivation
----------
This is breaking the creation of Windows tasks
=> [fargate] revert task pid mode on windows tasks

go.mod
Failing to run on mac M1 invoke commands with the error```error: failed to discover plugin requirements: determining go version: exit status 1```
Fixed by setting a version from which the toolchain can be installed
[link to Go issue
](https://github.com/golang/go/issues/65568)
=> Update go.mod - fix command executions on darwin+arm

tasks/config.py, tasks/setup.py
Add a step in the setup to make sure `gke-gcloud-auth-plugin` is installed. This is required to run creation of GKE cluster
It also fixes default account for GKE that should be `agent-sandbox`
Motivation
----------
=> [ADXT-514] Setup for GCP

scenarios/aws/ec2/vm.go
Reset password and configure it to a random string at init time
EC2 on Windows
Motivation
----------
EC2 configures Windows hosts with a random password. The password is base64 encrypted with the public SSH key, to decrypt it we would need to first decrypt the private SSH key that is passphrase protected on our laptops, then decrypt the key. As this has multiple potential points of failure, and it would require storing the private key password somewhere accessible, it is quicker to reset the password through SSH once we are connected to the VM, at init time. 
This allows for any code creating a `NewVM` on Windows to have a proper, accessible password in the `RemoteHost` output.
It is safe to …
=> [ec2] reset password on Windows VMs

components/datadog/agent/docker_image.go
This PR changes the default OTel Agent image from `gcr.io/datadoghq/agent:7-ot-beta` to `datadog/agent-dev:nightly-ot-beta-main`.
Local e2e test runs for OTel Agent tests.
Motivation
----------
Since the OTel Agent is currently in beta, we need more frequent builds to test with locally.
=> Update default OTel Agent image to nightly build

resources/gcp/compute/vm.go
Limit the maximum number of characters for VM resource on Azure to 63, otherwise it fails.
Add a tags to VM instances that is required to have then accessing the NAT Gateway. With that we should be able to run e2e tests from datadog-agent CI
Motivation
----------
=> Limit to 63 character for resource name on GCP and add NAT tag

Dockerfile
Remove a capability from the installed `vault`, see [this issue](https://github.com/hashicorp/vault/issues/10924) for more details
n/a
Motivation
----------
Vault migration
- Test on the current test-infra version [here](https://gitlab.ddbuild.io/DataDog/datadog-agent/-/jobs/666473217)
- Test on the built version [here](https://gitlab.ddbuild.io/DataDog/datadog-agent/-/jobs/666614728)
=> fix(vault) Remove the capability preventing usage of vault

resources/aws/environment.go, resources/aws/environmentDefaults.go, scenarios/aws/eks/run.go
It allows our roles to access clusters that are created in the CI. By default only the role that created the cluster can access it. This is a bit blocking when you want to inspect clusters created by the CI. With that change `account-admin` role will always get full access to the EKS cluster and `read-only` will be able to view resources inside the cluster.
It also "repair" the console so that we can see the resources directly in the `Resources` panel on the EKS page
Motivation
----------
=> Update EKS config map to allow account-admin and read-only SSO roles

scenarios/aws/microVMs/microvms/files/download-vm-images.py, scenarios/aws/microVMs/microvms/libvirt_fs.go, scenarios/aws/microVMs/microvms/volume.go
Modifies the download process of VM images by adding a Python script that performs the download based on a JSON file with instructions:
1. It first checks the checksum before downloading the image. This allows us to avoid downloads of existing images, but also force a re-download if the image is corrupt.
2. Once the script checks which images need to be downloaded, it will do so with `curl`.
3. After the download, the 	checksum is checked to ensure the image is not corrupted.
microVMs
Motivation
----------
The purpose of these changes is to make retries more consistent and correct.
Tested in https://github.com/DataDog/datadog-agent/pull/29472 - pipeline …
=> kmt: validate downloaded images

components/datadog/agent/host_windowsos.go
Reverts DataDog/test-infra-definitions#824 because the feature is still flaky
See WINA-1014 for more details
=> Revert "Revert "Make restart-service more robust to avoid weird test flakiness""

components/datadog/agent/ecs.go, components/datadog/agent/helm/kubernetes_agent.go, components/datadog/agent/kubernetes_helm.go, components/datadog/kubernetesagentparams/params.go, resources/gcp/environment.go, resources/gcp/environmentDefaults.go, resources/gcp/gke/cluster.go, scenarios/gcp/gke/cluster.go, scenarios/gcp/gke/run.go, tasks/gcp/gke.py
This PR adds a flag and a configmap parameter to use Autopilot on GKE. As a lot of features are not authorized by GKE the default Helm values enable fewer things by default.
It is likely to not work with any custom image as Datadog is granted some exception on Autopilot for its stable images. We'll probably need to request an exception to be able to deploy images built in the pipeline. 
Motivation
----------
=> Add support for Autopilot

components/datadog/agent/ecsFargate.go, tasks/aws/ecs.py
Adds an environment variable config to agents running on Fargate to enable process collection. Tasks are required to have `pidMode: task` set for process collection to work, which was done in https://github.com/DataDog/test-infra-definitions/pull/1063
Also adds a fix to make the ECS cluster connection string display correctly after creating an ECS cluster with the invoke task.
Reference: https://github.com/DataDog/test-infra-definitions/pull/979
ECS Fargate
Motivation
----------
Enable process collection on ECS Fargate
=> [ecs] Enable process collection on Fargate

components/datadog/agent/kubernetes_helm.go, resources/gcp/environment.go
Activate service account in the CI and prompt for gcloud auth login when running locally. Otherwise the connection to GKE cluster cannot be made
Motivation
----------
=> Fix GKE authentication in CI

common/config/environment.go, components/datadog/agent/host_linuxos.go, components/datadog/agent/host_windowsos.go, components/datadog/agentparams/params.go, components/datadog/agentparams/params_test.go
Add the possibility to run tests with an Agent 6 pipeline artefact. I basically add a parameter that will be passed alongside the `pipeline_id` so we can know where to fetch the artefacts to run the tests
All the scenarios in the Agent 6 branch of the agent repository and the people willing to run tests on Agent 6
Motivation
----------
The version 7 is hardcoded is some places. We'll need to modify this to be able to run the tests on Agent 6 artefacts
To use it we will also need to do [this](https://github.com/DataDog/datadog-agent/pull/30172) during the test-infra-definitions bump. We will also need to set the the `E2E_MAJOR_VERSION` …
=> Add the possibility to run tests with an Agent 6 pipeline artefacts

scenarios/aws/ecs/args.go
Set a missing parameter for ECS
ECS
Motivation
----------
We forgot it in https://github.com/DataDog/test-infra-definitions/pull/1193 and it breaks the ECS tests on the Agent side when we try to bump the version of test-infra
=> Set a missing parameter for ECS

components/os/scripts/setup-ssh.ps1
Install SSH on Windows Azure and AWS instances through the MSI
Windows
Motivation
----------
Ensure compatibility across Windows versions, as `Add-WindowsCapability` installs different version depending on the windows version (Windows Server 2019 vs 2022)
Suggested by @clarkb7 
Tested with:
- Windows Server 2019 ECS
- Windows latest
- Azure latest
=> [windows] install ssh through msi

components/os/debian_disable_upgrades.go, components/os/scripts/debian-disable-unattended-upgrades.sh, components/os/windows_setup_ssh.go, resources/azure/compute/vm.go, scenarios/aws/ec2/os_win.go, scenarios/aws/ec2/vm.go
Disable apt unattended upgrades at startup through userdata
aws debian and ubuntu
Motivation
----------
[ADXT-686](https://datadoghq.atlassian.net/browse/ADXT-686)
[ADXT-686]: https://datadoghq.atlassian.net/browse/ADXT-686?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [vm] disable unattended upgrades on debian/ubuntu on EC2

scenarios/aws/ec2/vm.go
Separate userdata from default userdata with a newline
ec2
Motivation
----------
Custom Userdata is currently broken as it results in having the last line suffixed by the shebang comment
```
#!/bin/bash
<custom userdata>#!/bin/bash
<default userdata>
```
This was introduced in ubuntu with https://github.com/DataDog/test-infra-definitions/pull/1207, breaking on e2e pre test
Tested this fix locally, the test now passes
=> 🐛[ec2] separate userdata scripts with new line

components/datadog/apps/cpustress/ecs.go, components/datadog/apps/cpustress/ecsFargate.go
Adds a Fargate version of the stress-ng workload which will be used for e2e testing [here](https://github.com/DataDog/datadog-agent/pull/30282).
Motivation
----------
=> [PROCS-4402] Add stress-ng Fargate workload app

components/datadog/apps/tracegen/images/tracegen/main.go
Adds new flag (`--addspantags`) or ENV var (`TRACEGEN_ADDSPANTAGS=`) to tracegen to tell tracegen to add an arbitrary set of tags to all spans it emits.
None will be impacted at first. 
We will be editing the `new-e2e/test/apm/::runTracegenDocker()` function to add this flag for APM tracegen tests.
For those tests, we will add some `peer.*` tags and assert that the resulting stats payloads carry the new tags properly.
Motivation
----------
https://datadoghq.atlassian.net/browse/APMST-1371
=> Add "addspantags" tag to tracegen to optionally set additional tags on all spans emitted

components/datadog/apps/aspnetsample/ecs.go
Give enough CPU and memory to Windows to avoid datadog agent starvation.
* `aws/ecs`
Motivation
----------
Fix [incident-31678](https://app.datadoghq.com/incidents/31678).
[`TestECSSuite/Test00UpAndRunning/ECS_tasks_are_ready` e2e test is very flaky](https://app.datadoghq.com/ci/test-runs?query=test_level%3Atest%20%40test.service%3Adatadog-agent%20%40git.branch%3Amain%20%40test.suite%3A%22github.com%2FDataDog%2Fdatadog-agent%2Ftest%2Fnew-e2e%2Ftests%2Fcontainers%22%20%40test.name%3ATestECSSuite%2FTest00UpAndRunning%2FECS_tasks_are_ready&agg_m=count&agg_m_source=base&agg_t=count&citest_explorer_sort=time%2Cdesc&currentTab=overview&eventStack=AgAAAZK0uvuw2-LLvgA …
=> Give enough CPU and memory to Windows

.gitlab-ci.yml
Update link and context of GOOGLE_CREDENTIALS variable
None
Motivation
----------
The former link was not mentioning `GOOGLE_CREDENTIALS` variable, which is a pulumi defined variable, see https://github.com/pulumi/pulumi/blob/master/pkg/authhelpers/gcpauth.go#L43-L55
=> [gitlab] update link and context of GOOGLE_CREDENTIALS variable

components/os/linux_descriptors.go, scenarios/aws/ec2/os_resolver.go
Change the Redhat AMIs query to be more resilient to descriptor changes. 
aws ec2 on redhat
Motivation
----------
redhat changed the inner version id on AMIs, breaking tests running on redhat as the old query was not matching any AMI. Using the [official Redhat support suggestion](https://access.redhat.com/solutions/15356) querying by `RHEL-<version>*` on owner redhat 
=> [aws][ec2] query redhat AMIs by version

components/os/linux_descriptors.go, scenarios/aws/ec2/os_resolver.go
* Update query for Fedora AMIs
* Bump Fedora default version to 40
EC2 on Fedora
Motivation
----------
The query was not returning any AMI, and version 37 does not exist anymore on AWS
=> [aws][ec2] update fedora ami query

tasks/ci.py
Skip PR not based on main when closing old bumps
None
Motivation
----------
The auto bumper closed [a backport PR](https://github.com/DataDog/datadog-agent/pull/30804)
Tested the base reference locally
=> [tasks] avoid closing test-infra bump PR not based on main

resources/aws/ec2/vm.go, scenarios/aws/ec2/vm.go, scenarios/aws/ec2/vmargs.go
This PR adds the possibility to enable/disable IMDSv1 when creating an ec2 instance.
It adds the HttpToken setting for metadata option for ec2 instance. If http tokens are required then every call to IMDSv1 will fail since only IMDSv2 requires http token to perform.
This parameter force the usage of IMDSv2 or the usage of the OS Hostname instead of the instance ID
Motivation
----------
This will help IMDSv2 tests before the transition between IMDSv1 and IMDSv2
=> [aws][ec2] add  support for imds2 in ec2 resource

.gitlab-ci.yml, resources/gcp/environment.go
`GOOGLE_CREDENTIALS` env var setup is not enough to have gcloud CLI working. We need to execute another command to enable service-account authentication for the CLI.
We need the CLI because the Pulumi Kubernetes provder rely on gcloud CLI to get authentication token for GKE cluster
Motivation
----------
=> Simplify authentication with GOOGLE_APPLICATION_CREDENTIALS env var

components/datadog/kubernetesagentparams/params.go, components/kubernetes/kind.go, scenarios/aws/kindvm/run.go
Naming was a mess on kind. Furthermore there is a trick on kind because the agent cannot determine alone the name of the cluster. A new flag allows us to pass the cluster name to the agent from the Kubernetes cluster output so it remains coherent
Motivation
----------
=> Handle naming for kind the same way as for EKS

components/datadog/agent/kubernetes_helm.go, components/datadog/apps/dogstatsd/images/dogstatsd/main.go, components/datadog/apps/dogstatsd/k8s.go
This PR enables `originDetectionUnified` and implement the External Data only E2E test.
This test was made with a different image using the same code.
All Kubernetes scenarios.
Motivation
----------
This is needed to effectively tests the newest solution for Origin Detection.
=> feat(origin detection): make unified setting as default and implement external-data E2E test

components/datadog/apps/dogstatsd/images/dogstatsd/main.go
Fix the missing `series` tag in the for the `dogstatsd-udp-external-data-only` workload.
All Kubernetes scenarions.
Motivation
----------
=> fix(dogstatsd-external-data-only): fix missing tag

scenarios/aws/microVMs/microvms/run.go
unattended-upgrades has been removed from the underlying AMI by this PR: https://github.com/DataDog/ami-builder/pull/204
microvms
Motivation
----------
=> Remove of unattended-upgrades no longer required

scenarios/aws/kindvm/run.go
Fixes workloads that depends on the Datadog Cluster Agent Admission Controller being ready.
Kind scenario.
Motivation
----------
Needed to have E2E tests depending on Admission Controller features.
=> fix(kind): fix workloads with admission controller dependency

scenarios/aws/eks/run.go, scenarios/aws/kindvm/run.go, scenarios/azure/aks/run.go, scenarios/gcp/gke/run.go
Deactivate client associated to the dogstatsd standalone
---------------------------------
eks, aks, kindvm, gke
Motivation
----------
In the Agent 6 context, we don't build the dogstatsd standalone. As a consequence we need to deactivate it and the associated clients must not be started. See errors in [this job](https://gitlab.ddbuild.io/DataDog/datadog-agent/-/jobs/709085841)
```
* the Kubernetes API server reported that "workload-dogstatsd-standalone/dogstatsd-uds" failed to fully initialize or become live: 'dogstatsd-uds' timed out waiting to be Ready
```
=> feat(dogstatsd): Deactivate client associated to the dogstatsd standalone

scenarios/aws/eks/run.go, scenarios/aws/kindvm/run.go, scenarios/azure/aks/run.go, scenarios/gcp/gke/run.go
Fix the use of `utils.PulumiDependsOn(k8sAgentComponent)` for all fake app components.
All the kubernetes-based ones.
Motivation
----------
Current situation is… random.
And it causes flakiness in the tests.
* All `nginx.K8sAppDefinition(…)` and `redis.K8sAppDefinition(…)` must have `dependsOnDDAgent /* for DDM */`.
* All `dogstatsd.K8sAppDefinition(…)` and `mutatedbyadmissioncontroller.K8sAppDefinition(…)` must have `dependsOnDDAgent /* for admission */`.
* All others `*.K8sAppDefinition(…)` must have no `dependsOnDDAgent`.
=> Sanitize the dependencies between K8s fake app pulumi components and the agent

components/component.go, components/remote/component.go, scenarios/aws/ec2/vm.go, scenarios/azure/compute/vm.go, scenarios/gcp/compute/vm.go
Add a CloudProvider identifier on Host component. So we can know where the component is living. Which can be useful on datadog-agent side when dealing with multi-cloud resources
Motivation
----------
=> Add a field containing a cloud provider identifier on remote Host

go.mod, go.sum, resources/azure/aks/cluster.go
When creating AKS cluster we get the following error 
```
Code="OnlySupportedOnUserAssignedMSICluster" Message="System-assigned managed identity not supported for custom resource /subscriptions/9972cab2-9e99-419b-a683-86bfa77b3df1/resourceGroups/MC_dd-agent-sandbox_kevin-fairise-test-aks-4-aks_westus2/providers/Microsoft.Network/routeTables/aks-agentpool-11552782-routetable. Please use user-assigned managed identity."
```
This PR should fix the issue by using a user assigned managed entity to the cluster
Motivation
----------
=> Use UserAssigned Identity for AKS cluster

scenarios/aws/eks/run.go, scenarios/aws/kindvm/run.go, scenarios/azure/aks/run.go, scenarios/gcp/gke/run.go
Reverts DataDog/test-infra-definitions#1261
This is currently breaking two e2e tests on `datadog-agent`
=> Revert "Sanitize the dependencies between K8s fake app pulumi components and the agent"

common/config/environment.go, common/utils/docker.go, common/utils/docker_test.go, components/datadog/agent/docker.go, components/datadog/dockeragentparams/params.go, resources/aws/environment.go, resources/azure/environment.go, resources/gcp/environment.go, resources/hyperv/environment.go, resources/local/environment.go
Added a check to make sure [JMX image](https://docs.datadoghq.com/integrations/java/?tab=docker) of the Agent is deployed by adding a new function called `InternalRegistryFullImagePathExists` that allows me to use a computed Docker image path. This means that tests that don't care about the JMX image won't have to rely on that job in the gitlab pipeline and we check the the image for the given test.
Also added a check on ECR to make sure we don't check for none ECR images + a unit test for parsing Docker image tags.
Docker end to end test, particularly the one created for JMXFetch [here](https://github.com/DataDog/datadog-agent/pull/31320). I've temporarily bumped the version of …
=> Updating docker image checks to make sure JMX image available and used for pipelines

resources/local/podman/vm.go
When executing `inv localpodman.create-vm`, it was possible to obtain a timeout on vault with ddtool hook.
Replaced the config by a custom empty config.
> [!NOTE]
> Do we want to be able to customize the config? Maybe it is better to provide an argument to replace by a custom config
Motivation
----------
=> Fix podman/docker config calling ddtool

.github/dependabot.yml
Group together aws-sdk and pulumi-azure-native-sdk dependencies
None
Motivation
----------
Prevent pulumi plugins mismatch
=> group aws and azure native dependencies

components/datadog/apps/dogstatsd/images/dogstatsd/go.mod, components/datadog/apps/dogstatsd/images/dogstatsd/go.sum
Update the `datadog-go` lib now that `v5.6.0` has been released: https://github.com/DataDog/datadog-go/releases/tag/v5.6.0.
Motivation
----------
Get rid of `replace` statement in `go.mod`.
It also fixes an issue where container tags are missing from dogstatsd metrics because the library fails to identify the container: 
=> Update `datadog-go` lib in `dogstatsd` app

scenarios/aws/eks/run.go, scenarios/aws/kindvm/run.go
Add an explicit dependency between the pulumi resource that creates the VPA CRD and the ones that create VPA CR.
* `aws/eks`
* `aws/kind`
Motivation
----------
Avoid possible race conditions where pulumi would try to create a VPA resource before the definition, leading to [errors](https://gitlab.ddbuild.io/DataDog/datadog-agent/-/jobs/737239415#L1495) like:
```
Diagnostics:
kubernetes:autoscaling.k8s.io/v1beta2:VerticalPodAutoscaler (redis):
error: creation of resource "urn:pulumi:ci-737239415-4670-orch-kind-cluster::e2eci::pulumi:providers:kubernetes$dd:apps$kubernetes:autoscaling.k8s.io/v1beta2:VerticalPodAutoscaler::redis" with kind autoscaling.k8s.io/v1beta2/VerticalPodAutoscaler failed …
```
=> Fix a missing dependency between VPA CRD and CR

.gitlab-ci.yml, tasks/ci.py
* Add manual job to trigger a bump of test-infra-definitions in `datadog-agent` from dev branches
* Sync and tidy all go modules in `datadog-agent` 
None
Motivation
----------
We often want to check that changes here do not break or fix tests in `datadog-agent`, this should reduce the manual operations to do this
Syncing and tidying all go modules as now `datadog-agent` uses go workspace, thus a bump in `test/new-e2e` might bump deps in other `datadog-agent` modules
Requires https://github.com/DataDog/datadog-agent/pull/32245
=> [gitlab] add manual trigger for bump in datadog-agent

tasks/aws/deploy.py
Adds defaultPrivateKeyPath to pulumi environment.  
On windows caused errors running `inv aws.create-vm`. Could not connect via ssh to provision and setup the VM with the agent.
Motivation
----------
Fixes above problem
=> Update deploy to copy private key path to pulumi env

common/config/environment.go, components/datadog/agent/docker.go, components/datadog/dockeragentparams/params.go, scenarios/aws/ec2/vm_run.go
Add option to request FIPS-flavored agent image
New e2e JMXFetch tests (TBD) using FIPS JMX agent images
Motivation
----------
=> AMLII-2213 Add FIPS agent image option

scenarios/aws/ec2/vmargs.go, scenarios/azure/compute/vmargs.go
Use architecture defined in `osDesc` on `WithOS` option
azure, aws VMs
Motivation
----------
ADXT-585. Current behaviour was unexpected, the `osDesc` contains a definition for architecture that defaults to amd64, we should not override it
=> [aws|azure] do not override osDesc architecture in WithOS

components/datadog/apps/dda/datadogagent.go
Fix the `image.pullSecrets` configuration when creating a new DDA resource with the NewDDAWithOperator component. `image.pullSecrets` should be a list of secret names, not a map.
aws/KindVM
Motivation
----------
bugfix
=> Fix image.pullSecrets configuration for NewDDAWithOperator

components/kubernetes/kind_versions.go
Add kubernetes/kind versions:
* k8s v1.32 / kind v0.26.0
* k8s v1.31 / kind v0.26.0
* k8s v1.30 / kind v0.26.0
* k8s v1.18 / kind v0.17.0
* k8s v1.17 / kind v0.17.0
* k8s v1.16 / kind v0.15.0
N/A
Motivation
----------
E2E tests for kubernetes clusters with either legacy or latest k8s versions and be better able to catch breaking changes
=> Add more k8s versions

components/datadog/agent/kubernetes_helm.go
This PR fixes a flakiness in e2e test (See [here](https://app.datadoghq.com/ci/test-runs?query=test_level%3Atest%20%40test.name%3A%22TestEKSSuite%2FTestAdmissionControllerWithAutoDetectedLanguage%22%20%40test.suite%3A%22github.com%2FDataDog%2Fdatadog-agent%2Ftest%2Fnew-e2e%2Ftests%2Fcontainers%22%20%40git.branch%3Amain%20%40test.service%3Adatadog-agent%20%40test.status%3Afail&agg_m=count&agg_m_source=base&agg_t=count&currentTab=overview&eventStack=&fromUser=true&graphType=flamegraph&index=citest&spanViewType=logs&start=1733229830363&end=1735821830363&paused=false)).
Language detection client runs in the core agent, and periodically sends detected languages to the cluster agent. 
When the cluster agent receives a detected language, it patches the …
=> [CONTP-547] reduce language detection refresh period to 1 minute

components/datadog/apps/jmxfetch/images/jmx-test-app/run.sh
Expose ssl configuration for jmx test app.
agent-metrics-logs/jmxfetch tests.
Motivation
----------
Test jmxfetch with encrypted jmx connection.
Since jmx and the registry use the same port, they must have matching ssl configuration to avoid 'port already in use' errors.
=> Expose ssl configuration

common/config/environment.go, scenarios/aws/ec2/vm_run.go, scenarios/aws/microVMs/microvms/run.go, scenarios/azure/compute/run/vm_run.go, scenarios/gcp/compute/run/vm_run.go, scenarios/local/podman/run/vm_run.go, tasks/aks.py, tasks/aws/deploy.py, tasks/aws/docker.py, tasks/aws/ecs.py, tasks/aws/eks.py, tasks/aws/installer.py, tasks/aws/kind.py, tasks/aws/vm.py, tasks/azure/aks.py, tasks/azure/vm.py, tasks/deploy.py, tasks/doc.py, tasks/gcp/gke.py, tasks/gcp/vm.py, tasks/localpodman/vm.py, tasks/vm.py
This adds an option to chose the agent flavor following this [PR](https://github.com/DataDog/test-infra-definitions/pull/1286).
```sh
inv aws.create-vm --agent-flavor datadog-fips-agent --pipeline-id 52797187
```
Motivation
----------
=> [ADXT-814] Add `agent-flavor` option to `inv create-vm`

tasks/tool.py
If the know host was already added, it made the program crash (known host introduced [here](https://github.com/DataDog/test-infra-definitions/commit/4372e330fe39826b544454dadc3fdefc19374db3))
Motivation
----------
=> Fixed ssh-keyscan error

tasks/aws/vm.py, tasks/azure/vm.py, tasks/gcp/vm.py, tasks/localpodman/vm.py, tasks/tool.py
The `clean_know_hosts` option is now enabled by default but created an error without any stack trace when doing a destroy.
The host couldn't be found after the destroy.
Fixed this
Motivation
----------
=> Fixed inv destroy issues with clean know host

common/config/environment.go, components/datadog/dockeragentparams/params.go, tasks/aws/deploy.py, tasks/aws/docker.py, tasks/deploy.py, tasks/doc.py
This allows configuring the agent for docker by passing custom environment variables.
**Example**:
```sh
inv aws.create-docker --agent-env=DD_LOG_LEVEL=error,HELLO=world
```
Motivation
----------
=> [ADXT-84] Add agent environment arg to create vm (docker)

tasks/aws/ecs.py
The pulumi output doesn't contain the `-cluster` suffix.
Motivation
----------
=> Fixed wrong output name for ecs

components/datadog/apps/redis/docker-compose.yaml, components/datadog/apps/redis/docker.go, components/datadog/dockeragentparams/params.go
Add a `docker-compose.yaml` file for the `redis` workload to be able to use it in the docker scenarios.
Motivation
----------
Used by DataDog/datadog-agent#32895.
=> [CONTINT-4520] Port the legacy integration docker e2e tests

scenarios/aws/microVMs/microvms/run.go
This PR fixes the userdata script being executed on the host VM, as it was not configuring the automatic shutdown properly.
MicroVMs scenario.
Motivation
----------
Stop long-running instances from not shutting down automatically.
Validated by booting a host with the microvms runner and checking with `cat /run/systemd/shutdown/scheduled` that the shutdown is properly scheduled.
=> Fix automatic shutdown in microVMs

common/namer/namer.go, common/namer/namer_test.go
We observe some weird `Already exists` error on job that create a lot of fakeintake in the same job. Let's see if increasing the length of the hash when truncating resource name can help
Motivation
----------
=> Increase hash lengh to avoid collisions

scenarios/aws/microVMs/microvms/libvirt.go, scenarios/aws/microVMs/microvms/network.go, scenarios/aws/microVMs/microvms/network_test.go
This PR adds ARP table querying as an additional source to listen for DHCP leases. In some cases we've seen that the `dhcpd_leases` file contains hardware identifiers that are not MAC addresses  (see [RFC 2132](https://www.rfc-editor.org/rfc/rfc2132#section-9), section 9.14, where it's specified that DHCP client IDs might not always be Ethernet addresses) which means we cannot extract the MAC address for the new VM from there. The ARP table should have information in those cases, as we do have a DHCP lease and the IP-MAC assignment should be present in the table.
microvms
Motivation
----------
Tested locally in macOS by launching a KMT local instance.
=> microvms: Use ARP to resolve DHCP leases in macOS

components/datadog/agent/docker.go, components/datadog/agent/helm/kubernetes_agent.go, components/datadog/agent/host.go, components/datadog/agent/kubernetes.go
Expose information about wether FIPS should be enabled or not in the agent.
Since several method are available to enable FIPS, through environment variable or using `WithFIPS` flag, we do not have any way to know if FIPS is enabled or not in tests.
With that the Agent should contains an input indicating if FIPS is supposed to be enabled
Motivation
----------
=> Add info about wether FIPS should be enabled or not in Agent components

Dockerfile
Motivation
----------
Rectify this oversight as is also happening here: https://github.com/DataDog/datadog-agent-buildimages/pull/762
=> Ensure deva does not install dependencies dynamically

components/datadog/agent/docker_image.go
Updates the docker tag when using agent 6.
Related to https://github.com/DataDog/datadog-agent/pull/33991.
Motivation
----------
=> [ADXT-901] Agent image tag updated given major agent version

components/os/linux_descriptors.go
Expose Ubuntu 2404 but still use 2204 as default because it breaks a lot of test otherwise
Motivation
----------
=> Revert default to ubuntu22

components/datadog/agent/kubernetes_helm.go
Enable collection of `customresourcedefinitions` and `apiservices` in `kubernetes_state_core` check.
`aws/eks`
`aws/kind`
Motivation
----------
These resources are collected by default in the operator. This change brings us closer to mimic-ing customer environments to allow us to catch any regressions quicker. 
Tested this update, and ensured current e2e tests pass: https://gitlab.ddbuild.io/DataDog/datadog-agent/-/pipelines/55468209
=> Enable collection of CRDs/apiservices in KSM config

components/os/scripts/apt-disable-unattended-upgrades.sh
Update user data script to remove systemd unit that can trigger updates of apt, picking lock and introducing flakiness
Motivation
----------
=> Improve disable-unattended-upgrade script to also disable apt daily upgrade

components/os/scripts/apt-disable-unattended-upgrades.sh
Make sure user script does not fail provisioning if automatic updates are already disabled or the script is not relevant for the platform
Motivation
----------
=> Disabling automatic update should not fail provisioning if it has no effect

scenarios/aws/microVMs/microvms/network.go, scenarios/aws/microVMs/microvms/network_test.go
fixes parsing of MAC addresses during KMT
`aws/microVMs`
Motivation
----------
`invalid MAC address 1:0:5e:0:0:fb, cannot parse fb: strconv.ParseInt: parsing "fb": value out of range`
=> need to parse MAC parts as uint8

components/kubernetes/kind.go, components/kubernetes/kind_versions.go, components/kubernetes/nvidia/nvidia.go, components/kubernetes/nvidia/nvkind-config-template.yml, components/kubernetes/nvidia/options.go
This PR adds code to support Kubernetes Kind clusters with GPU support. Due to the patches required for these clusters, we use the `nvkind` tool provided by NVIDIA. Some of the existing code for kind cluster creation is separated into new functions/exported to enable code sharing.
Should not have impact on existing scenarios.
Motivation
----------
Implement e2e tests of the GPU monitoring feature.
=> Add support for NVIDIA nvkind cluster

components/kubernetes/nvidia/nvidia.go, components/kubernetes/nvidia/nvkind-config-template.yml
This PR fixes the nvkind cluster creation code to ensure they have visibility into the host procfs, necessary for the agent to see processes in the host root procfs.
Motivation
----------
=> Fix procfs in nvkind clusters

components/command/filemanager.go, components/command/osCommand.go, components/command/runner.go, components/command/unixOSCommand.go, components/command/windowsOSCommand.go, components/datadog/agent/host.go
This reverts commit 9bbbec2
Partially revert a change that was made to use `CopyToRemote` instead of `CopyFile` because it does not support well copying a file when it is not determined at plan time. Let's use `CopyToRemote` only for uploading package file, we know it works there.
I'll open a discussion with pulumi-command maintainer to check if it is something that they are aware of
Motivation
----------
=> Do not use CopyToRemote everywhere

components/datadog/agentparams/msi/install_params.go
This PR introduce an option to set a custom installation path for host-based Windows installation.
Motivation
----------
This will be useful for edge-cases where the Agent rely on assets stored in the Agent install directory. 
=> add custom install path as Windows install Agent option

scenarios/aws/microVMs/microvms/network.go
Ignores ARP entries with `(incomplete)` for MAC address
`aws/microVMs`
Motivation
----------
log spam
=> prevent incomplete MAC address from spamming logs

components/os/scripts/apt-disable-unattended-upgrades.sh
Adds extra commands to ensure unattended-upgrades processes get killed.
Most of the scenarios run the cloud init script.
Motivation
----------
Reduce flakiness due to unattended-upgrades lingering.
=> Ensure unattended-upgrade processes are getting killed

components/os/scripts/apt-disable-unattended-upgrades.sh
Remove all DPKG/APT locks when the init-script finishes
Motivation
----------
Avoid unattended-upgrades causing CI failures
=> Remove all apt/dpkg locks in cloud-init script

components/os/scripts/apt-disable-unattended-upgrades.sh
Fix the removal of unattended-upgrades by purging _after_ removing the locks in case they're taken
Motivation
----------
=> Fix apt-get unattended-upgrades removal

components/datadog/agent/kubernetes_helm.go, components/datadog/apps/etcd/k8s.go, scenarios/aws/eks/run.go, scenarios/aws/kindvm/run.go, scenarios/azure/aks/run.go, scenarios/gcp/gke/run.go
Adds an etcd pod that stores a Datadog check configuration for testing purposes. This setup uses a basic OpenMetrics check and is intended to validate that Autodiscovery works correctly when etcd is used as a configuration provider.
=> [components/datadog] Add etcd with config check

components/datadog/agentparams/params.go
Before that PR, using local package would override the flavor, both should be compatible.
Instead we put local package in `defaultVersion` argument. That way the version is given by:
- a special version
- local package path
- pipeline id
In that order of priority
Motivation
----------
=> Specifying local package folder with a given flavor should work

.gitlab-ci.yml
Use a new task defined in https://github.com/DataDog/datadog-agent/pull/36163 to push signed commits when creating the auto-bump PR.
Tested with [this pipeline](https://gitlab.ddbuild.io/DataDog/test-infra-definitions/-/jobs/898989580) and signed commit was properly created [here](https://github.com/DataDog/datadog-agent/commit/56fdb74b654133fe30bd7d193117bb63b7a387c3)
PR creation
Motivation
----------
https://datadoghq.atlassian.net/browse/ACIX-515
=> feat(autobump): Push signed commits on auto-bump PR

tasks/vm.py
Updates `inv rdp-vm` task to fetch the password from the stack output instead of from AWS
Motivation
----------
fix invoke task since password is set in stack now in https://github.com/DataDog/test-infra-definitions/pull/1124
=> get password from stack output

components/kubernetes/vpa/vpa.go
Update the VPA CRD to expose the `v1` version as defined in [the upstream definition](https://github.com/kubernetes/autoscaler/blob/6d1a1514af4406bb967ae6f50e9589f7d41f9af8/vertical-pod-autoscaler/deploy/vpa-v1-crd-gen.yaml). This version was first added in VPA version 0.7.0, released 6 years ago.
new-e2e-containers
Motivation
----------
Needed for [this PR](https://github.com/DataDog/datadog-agent/pull/36222) to fix broken VPA metrics in the KSM check after VPA version 1.3.0 was released. More details in that PR.
This change has been tested in another datadog-agent branch and is [confirmed working](https://gitlab.ddbuild.io/DataDog/datadog-agent/-/jobs/913835 …
=> Update VPA CRD to expose version v1

components/datadog/agent/package.go
Picking the first artifact can lead to unexpected artifact installed in the CI, let's avoid that.
Also ignore upgrade-test msi packages that are exposed by the agent CI
Motivation
----------
=> Fail if several pacakge are found for the test

scenarios/aws/ec2/vm.go
Checks that the binary for the ecr credentials helper is not present before trying to install it.
Motivation
----------
Some AMIs have the binary installed, without using the package manager. If we always try to install it the provisioning fails.
=> Check binary for ECR credentials helper

components/datadog/apps/dogstatsd/docker-compose.yaml, components/datadog/apps/dogstatsd/docker.go, components/datadog/apps/dogstatsd/ecs.go, components/datadog/apps/dogstatsd/eksFargate.go, components/datadog/apps/dogstatsd/k8s.go, components/datadog/apps/jmxfetch/docker-compose.yaml, components/datadog/apps/jmxfetch/docker.go, components/datadog/apps/logger/docker-compose.yaml, components/datadog/apps/logger/docker.go, components/datadog/apps/logger/k8s.go, components/datadog/apps/mutatedbyadmissioncontroller/k8s.go, components/datadog/apps/nginx/ecs.go, components/datadog/apps/nginx/ecsFargate.go, components/datadog/apps/nginx/k8s.go, components/datadog/apps/npm-tools/ecs.go, components/datadog/apps/npm-tools/k8s.go, components/datadog/apps/prometheus/ecs.go, components/datadog/apps/prometheus/k8s.go, components/datadog/apps/redis/docker-compose.yaml, components/datadog/apps/redis/docker.go, components/datadog/apps/redis/ecs.go, components/datadog/apps/redis/ecsFargate.go, components/datadog/apps/redis/k8s.go, components/datadog/apps/tracegen/ecs.go, components/datadog/apps/tracegen/k8s.go, components/datadog/apps/version.go, components/kubernetes/istio/istio.go
Use pinned version of the test apps docker images.
All.
Motivation
----------
We need to control when a change done in a test app docker image is used by the `datadog-agent` CI.
With the floating `main` tag, a change merged in `test-infra-definitions` was immediately used by all the branches and PRs of `datadog-agent` without any “bump” PR.
=> Use pinned version of the test apps docker images

components/datadog/agent/kubernetes.go, resources/aws/ec2/asg.go
Fix the following [`golangci-lint` errors](https://github.com/DataDog/test-infra-definitions/actions/runs/14979841357/job/42081959557?pr=1522):
```
Error: components/datadog/agent/kubernetes.go:38:1: File is not properly formatted (gofmt)
FIPSEnabled pulumi.BoolOutput `pulumi:"fipsEnabled"`
^
Error: resources/aws/ec2/asg.go:16:11: redefines-builtin-id: redefinition of the built-in function min (revive)
desired, min, max int,
^
```
Motivation
----------
Those errors are failing the CI of PRs that are not touching those files like #1522 for ex.
=> Fix `golangci-lint` errors

components/datadog/apps/nginx/k8s.go
A follow up for recent feature in 7.60: https://github.com/DataDog/datadog-agent/pull/29984
which allows user to configure the cardinality of check instance via annotation check config.
This PR set nginx check cardinality to high.
New test metric "nginx.net.connections" will be added https://github.com/DataDog/datadog-agent/pull/35995
for testing additional tags like container id, name etc. 
Motivation
----------
=> [CONTP-437] Add check_cardinality to nginx

.github/workflows/lint.yml, tasks/deploy.py
Remove usage of the `requirements.txt` from buildimages (see https://github.com/DataDog/datadog-agent-buildimages/pull/841).
Install directly the only required dependencies for the linter task.
None
Motivation
----------
[Job is currently broken](https://app.datadoghq.com/ci/pipeline-executions?query=ci_level%3Ajob%20%40git.repository.name%3A%22DataDog%2Ftest-infra-definitions%22%20%40git.branch%3Amain%20%40ci.job.name%3Alint-python&agg_m=count&agg_m_source=base&agg_t=count&colorBy=meta%5B%27ci.job.name%27%5D&colorByAttr=meta%5B%27ci.job.name%27%5D&currentTab=trace&fromUser=false&graphType=flamegraph&index=cipipeline&spanViewType=metadata&start=1747315189287&end=1747401589287&paused=false) …
=> fix(ci): Do not use the deprecated requirements from buildimages

components/datadog/apps/version.go
Bump the version of the test apps to `v0.0.3`.
* `aws/docker`
* `aws/eks`
* `aws/kind`
Motivation
----------
Several `dependabot` :dependabot: PRs have been merged since `v0.0.2`.
* #1528 
* #1502 
* #1532
* #1421 
* #1420 
* #1419 
* #1418
In order to take all those changes into account, we need a new tag for the test apps docker images.
=> Bump version to v0.0.3

.github/workflows/docker-publish.yml, components/datadog/apps/s3-proxy-nginx/images/s3-proxy-nginx/Dockerfile, components/datadog/apps/s3-proxy-nginx/images/s3-proxy-nginx/nginx.conf
Create a nginx image to redirect `install(testing).datad0g.com.internal-dda-testing.com` to their respective S3 buckets.
The goal is to be able to fetch these buckets without going through Cloudfront
https://datadoghq.atlassian.net/wiki/x/RoLc9g
Motivation
----------
=> Add s3 proxy image for install buckets

resources/azure/compute/vm.go
When generating a host password for Windows-based tests, disallow the use of `<`, `>` and `&`.
Hopefully none: we are only limiting the set of possible passwords and not adding any new behavior.
Otherwise, all scenarios that run Windows VMs: only `azure` at this time. 
Motivation
----------
When showing the host password in the Gitlab CI logs, it gets JSON-encoded using `json.Marshal`. As [the docs](https://pkg.go.dev/encoding/json#Marshal) mention, this method URL-encodes the three characters `<`, `>` and `&` to make the JSON safe to embed in HTML.
This means that any passwords containing these characters will be shown encoded in the CI logs, making them impossible to directly copy-paste. To …
=> [ACIX-864] Prevent use of some chars in host password for clearer log output in CI

scenarios/aws/ec2/vm.go
Follow-up to ad2bfe2 (PR #1557), doing the same thing but also for AWS - I missed it in the original PR.
Below the original PR's description:
When generating a host password for Windows-based tests, disallow the use of `<`, `>` and `&`.
Hopefully none: we are only limiting the set of possible passwords and not adding any new behavior.
Otherwise, all scenarios that run Windows VMs: ~~only `azure` at this time.~~ **`azure` and `aws`**
Motivation
----------
When showing the host password in the Gitlab CI logs, it gets JSON-encoded using `json.Marshal`. As [the docs](https://pkg.go.dev/encoding/json#Marshal) mention, this method URL-encodes the three characters `<`, `>` and `&` to make the JSON …
=> [ACIX-864] [Follow-up] Prevent use of some chars in host password for clearer log output in CI

scenarios/aws/microVMs/microvms/provision.go
This PR adds support for pushing `CI_COMMIT_SHA` to KMT microVMs, this is something we want to use in CWS tests.
Motivation
----------
=> kmt: allow ssh env CI_COMMIT_SHA

scenarios/aws/microVMs/config/config.go, scenarios/aws/microVMs/microvms/domain.go, scenarios/aws/microVMs/microvms/resources/distro/domain-amd64.xsl, scenarios/aws/microVMs/microvms/run.go
This PR allows launching a GDB server attached to the guest VM upon user's request.
Motivation
----------
=> Allow user to setup GDB server with QEMU

components/datadog/agent/kubernetes_helm.go
Set cluster agent replicas to 2 so that k8s cluster has one leader dca and one follower dca pod.
k8s_test.go
eks_test.go
Motivation
----------
Cluster agent leader election test has been added to E2E test in[PR](https://github.com/DataDog/datadog-agent/pull/35612)
Test run is [here](https://github.com/DataDog/datadog-agent/pull/35991)
=> Set cluster-agent replicas to 2

resources/gcp/gke/cluster.go
Authorize private GKE cluster API to be queried from ddbuild VPN IPs
Motivation
----------
=> [ACIX-924] Authorize ddbuild VPN private IPs

components/datadog/agent/package.go
Re-does https://github.com/DataDog/test-infra-definitions/pull/1601.
> Prepare test-infra-definition for a change that will provide a basic build artifact isolation on Windows, where the packages are now located in a pipeline-$CI_PIPELINE_ID directory
But it does so in a way that is safe to merge before https://github.com/DataDog/datadog-agent/pull/38219 gets merged, by looking for the pipeline ID named subfolder first and falling back to the currently acceptable behavior otherwise.
Motivation
----------
#incident-39868
Tested [here](https://gitlab.ddbuild.io/DataDog/datadog-agent/-/pipelines/70022339) against main and …
=> Try to find Windows packages on a pipeline-ID specific folder before common folder

.gitlab-ci.yml
- Use more recent version of images
- Install the awscli at runtime
None
Motivation
----------
https://datadoghq.atlassian.net/browse/CONTSEC-1634
We need to install awscli to prevent dockerhub rate limiting.
As we are using images from the `datadog/images` repo we can workaround with runtime installation. I will check if we can update these images to have the cli installed as we have the same need in buildimages
=> fix(build): Use more recent image and install awscli at runtime

tasks/setup.py
This PR intends to resolve a quoting issue when running `dda inv setup` command.
When a user is setting up E2E environment with command `dda inv setup` or `inv setup` on Windows platform.
Motivation
----------
On Microsoft Windows, command `inv setup` would fail.
=> correct quoting for Windows platform

.github/workflows/build.yml, .gitlab-ci.yml, Dockerfile
This fixes issues we have for the `build` github action.
There is a nil pointer exception which is fixed with orchestrion `v1.4.0`.
Motivation
----------
Cf this [thread](https://dd.slack.com/archives/C02DW5ZH1EF/p1752666719370799).
=> Bump orchestrion to 1.4.0

components/datadog/apps/gpu/images/cuda-basic/cuda-basic.cu
adds graceful termination of the cuda-basic app only upon receiving an external signal
gpu e2e tests
Motivation
----------
avoid race conditions when the workload finishes too fast
a PR in the e2e tests in datadog-agent repo will follow
=> [GPUM]: wait for external signal to finish cuda-basic app

components/datadog/apps/gpu/images/cuda-basic/cuda-basic.cu
revert the original [PR](https://github.com/DataDog/test-infra-definitions/pull/1625)
Motivation
----------
e2e gpu tests started to fail on main in datadog-agent repo
=> revert [GPUM]: wait for external signal to finish cuda-basic

Dockerfile
See title.
Motivation
----------
`dda` periodically checks for updates and displays its changelog if a new version is found - this is useful when running interactively with a developer but useless in CI. Moreover it can cause some strange issues as the changelog is sometimes pushed in the `stdout` of the command you are trying to run, and can pollute its output.
#incident-41159
=> Disable automatic update check for `dda` in the runner image

Dockerfile
Pins the `dda` version used in the runner image instead of pulling it dynamically _at build time (!)_ using `curl` from `datadog-agent-buildimages`
N/A
Motivation
----------
This makes it a lot easier to find out and control which version of `dda` is included in the runner image, at the cost of having possible desyncs. This seems like a good idea after [incident-41159](https://app.datadoghq.com/incidents/41159), [41173](https://app.datadoghq.com/incidents/41173) and [41126](https://app.datadoghq.com/incidents/41126).
`dda` version mismatches with the rest of the buildimages are probably not that big of a deal for the e2e tests - the only thing we really need …
=> refactor(runner): Pin `dda` version instead of pulling from `datadog-agent-buildimages`

README.md
Adds quick start examples for both GKE Standard and GKE Autopilot clusters in the README.md file.
Motivation
----------
Currently the README.md file is lacking documentation for GKE environments.
=> Adding in Quickstart for GKE Standard and GKE Autopilot

Dockerfile
This adds auth-anywhere that is used to get tokens to interact with the agent ci API / the stack cleaner. It is currently installed on the fly which isn't great.
Motivation
----------
=> Add auth anywhere to the image

components/datadog/agent/host_linuxos.go
When targeting a test artifact from a specific pipeline in `datadog-agent`, use the testing keys to verify the metadata signatures of apttesting.datad0g.com and yumtesting.datad0g.com.
Needed after the merge of https://github.com/DataDog/datadog-agent/pull/36943, which makes the `datadog-agent` pipeline sign testing repositories with a dedicated set of testing keys.
Local runs of E2E tests, which need to download artifacts from the testing repositories. CI runs were not affected because they use the local Gitlab pipeline artifact.
Motivation
----------
Fix local use cases.
n/a
=> Target testing keys directory when downloading artifacts from {apt,yum}testing.datad0g.com

components/datadog/agent/kubernetes_helm.go
Runs the KSM check as a cluster check in the CLC runner.
Any scenario deploying the agent with Helm.
Motivation
----------
Updates to e2e tests in datadog-agent should be done in the same PR bumping test-infra in datadog-agent
These tests are already updated in [this](https://github.com/DataDog/datadog-agent/pull/39245) PR.
=> [CONTP-898] configure KSM check to run as clustercheck in clc runners

README.md, components/datadog/apps/cpustress/openshift.go, components/datadog/apps/dogstatsd/openshift.go, components/datadog/apps/tracegen/openshift.go, scenarios/gcp/openshiftvm/run.go, tasks/gcp/openshift.py
This PR enables deploying test workloads on an OpenShift cluster. In this PR Redis, Prometheus, CPUStress, Tracegen, Dogstatsd are deployed.
This change impacts `gcp\openshiftvm`
Motivation
----------
Previously, deploying test workloads was disabled.
I've had to make additional changes for test workloads because of OpenShift's SCCs. All changes are outlined in this [documentation](https://docs.google.com/document/d/1Ea_gBRH5q8La99PZIgcPa4ALWZD9Oaf22PFdOAY_udg/edit?tab=t.0)
=> Deploying Test Workloads onto OpenShift cluster

Dockerfile
We need codecov to upload coverage result for our e2e tests.
Let's add it in the image to avoid downloading it at runtime
Motivation
----------
=> [ACIX-851] Install codecov in e2e runner image

components/datadog/agent/host_linuxos.go
Use the public keys in `apttesting.datad0g.com/test-keys` to verify signatures of test packages and repositories.
This place contains new testing keys that can be used by both the existing and new Gitlab runners in `datadog-agent`.
Installs from the apttesting.datad0g.com / yumtestingdatad0g.com repositories.
Motivation
----------
Unblock Gitlab runner migration in `datadog-agent`.
n/a
=> Target v2 testing keys directory when downloading artifacts from {apt,yum}testing.datad0g.com

components/datadog/agent/kubernetes_helm.go
This PR enables autoscaling in k8s cluster for e2e test including local failover workload store.
e2e test change : https://github.com/DataDog/datadog-agent/pull/40132
Motivation
----------
=> [CONTP-675] Enable autoscaling in cluster-agent for k8s test

components/datadog/agent/kubernetes_helm.go
Prevent the activation of autoscaling in FIPS mode
Kubernetes
Motivation
----------
Autoscaling requires remote-config. 
```
Error: Remote config is disabled or failed to initialize, remote config is a required dependency for autoscaling
```
This error is [raised](https://gitlab.ddbuild.io/DataDog/datadog-agent/-/jobs/1106410256) on the FIPS downstream pipeline, and remote-config [is not available on FIPS agent](https://github.com/DataDog/datadog-agent/blob/main/.gitlab/e2e/e2e.yml#L579-L580). As consequence since we integrated [this update](https://github.com/DataDog/test-infra-definitions/commit/afa021e5ea491da8b5970cb739ed819f47d0a394) in the `datadog-agent` repository [all the FIPS …
=> fix(FIPS): Prevent autoscaling in FIPS mode

scenarios/aws/ec2/vm.go, scenarios/aws/ec2/vmargs.go
Add an option to pass pulumi option to the VM component
Goal is to be able to add an extra dependency between fakeintake and VM to protect us from an issue where the fakeintake is released while the agent is still running on the host. It leads to a situation where the fakintake IP can be reused in a later test and the old agent sends data to a fakeintake that is used in a new tests, which lead to weird falkiness
https://datadoghq.atlassian.net/jira/software/c/projects/ACIX/boards/6169/backlog?selectedIssue=ACIX-1005
Motivation
----------
=> [ACIX-1005] Add a VM option to pass Pulumi resource options

components/datadog/apps/version.go
Bump version after image rebuilt. Needed to have [this](https://github.com/DataDog/test-infra-definitions/pull/1687) change applied
Motivation
----------
=> Bump apps version to v0.0.4

common/config/environment.go, scenarios/aws/ec2/vm_run.go, scenarios/aws/ecs/run.go, scenarios/aws/eks/run.go, scenarios/aws/fakeintake/fakeintake.go, scenarios/aws/fakeintake/params.go, scenarios/aws/kindvm/run.go, scenarios/azure/aks/run.go, scenarios/azure/fakeintake/fakeintake.go, scenarios/azure/fakeintake/params.go, scenarios/gcp/fakeintake/fakeintake.go, scenarios/gcp/fakeintake/params.go, scenarios/gcp/gke/run.go, scenarios/gcp/openshiftvm/run.go
Add necessary code to pass option to start fakeintake server:
- `ddagent:fakeintakeStoreType` to select the store tyep (sql or memory)
- `ddagent:fakeintakeRetentionPeriod` to select the data retention period
The `fakeintakeRetentionPeriod` is useful for the coming end2end tests to ensure we store the data we want to test long enough for the test to run and prevent having the scenario where the test runs and the data we request has been cleaned-up.
Added the argument parsing for all scenarios that use the fakeintake and allows it to be configured.
- aws
- azure
- gcp
Motivation
----------
- For end2end tests on the agent we have a check that runs every 30 minutes.
- the fakeintake has a …
=> CONTINT-4687 - add fakeintake options

components/os/linux_disable_upgrades.go, components/os/scripts/ssh-allow-sftp-root.sh, scenarios/aws/ec2/vm.go
This PR allows to open SFTP connection as the root user for the EC2 instances used in E2E tests.
E2E tests using an AWS EC2 instance, with either Unixes or Windows (no-op here, since the client user is aldready `Administrator`) OS.
Motivation
----------
With [[AGENTRUN-609] Apply stricter permissions to log folder](https://github.com/DataDog/datadog-agent/pull/40257), which aims to strengthen permissions for the Agent's log files, E2E may still require to validate that an action performed has taken effect by reading the content of the Agent's logs. This PR provides the needed infrastructure to open privileged SFTP session.
- It seems trivial to escalate from …
=> Allow SFTP connection for the root user

resources/aws/platforms.go
A test on deploy pipeline is broken due to that, we use an amd64 image so we need to provide one as well.
[Example error](https://gitlab.ddbuild.io/DataDog/datadog-agent/-/jobs/1151592168).
Motivation
----------
=> Provide AMI for macos x86_64

components/datadog/apps/version.go
Bump version after image rebuilt to incorporate https://github.com/DataDog/test-infra-definitions/pull/1699 in the datadog-agent e2e tests
Motivation
----------
=> Bump apps version to v0.0.5
