DataDog/test-infra-definitions

- aws/ec2/ec2/asg.go
- aws/ec2/ec2/vm.go
- aws/ec2/ec2/vmtemplate.go
- aws/ecs/ecs/capacityProviders.go
- aws/ecs/ecs/cluster.go
- aws/ecs/ecs/fargateService.go
- aws/ecs/ecs/nodeGroups.go
- aws/ecs/ecs/run.go
- aws/eks/eks/nodeGroups.go
- aws/eks/eks/nodeRole.go
- aws/eks/eks/run.go
- aws/environment.go
- aws/scenarios/docker-vm/main.go
- aws/scenarios/vm/main.go
- command/docker.go
- command/filemanager.go
- command/package.go
- command/runner.go
- command/utils.go
- common/config/environment.go
- common/namer.go
- common/utils/file.go
- common/utils/hash.go
- datadog/agent/ecs.go
- datadog/agent/host.go
Introduce namer to ease object naming and consistency
All
Motivation
----------
Code quality
> Introduce namer to ease object naming and consistency

- aws/ec2/ec2/vm.go
- aws/eks/eks/nodeGroups.go
- aws/eks/eks/run.go
- aws/scenarios/dockerVM/dockerVM/run.go
- command/docker.go
- command/filemanager.go
- command/package.go
- command/runner.go
- command/utils.go
- datadog/agent/docker.go
- datadog/agent/host.go
- go.mod
- go.sum
Use triggers to restart the Agent whenever the configuration is modified
Docker
Motivation
----------
> Use triggers to restart the Agent whenever the configuration is modified

- command/docker.go
- command/filemanager.go
- command/runner.go
- common/utils/file.go
Use `stdin` instead of args to copy inline content to avoid size limitation.
All
Motivation
----------
> Use stdin to copy inline content

- aws/ec2/ec2/vm.go
- aws/scenarios/vm/vm/run.go
- command/docker.go
- common/utils/pulumi.go
- kubernetes/kind-cluster.yaml
- kubernetes/kind.go
Implement Kind installation
None
Motivation
----------
> Implement Kind installation

- aws/ec2/ec2/asg.go
- aws/ec2/ec2/vmtemplate.go
- aws/ecs/ecs/capacityProviders.go
- aws/ecs/ecs/cluster.go
- aws/ecs/ecs/fargateService.go
- aws/ecs/ecs/run.go
- datadog/agent/ecs.go
Align naming of ECS components
ECS
Motivation
----------
> Align naming of ECS components

- .github/workflows/build.yml
Add a github action to build the code.
Motivation
----------
> Add github action to build the code

- aws/eks/eks/nodeGroups.go
- aws/eks/eks/nodeRole.go
- aws/eks/eks/run.go
- common/namer.go
> Align EKS naming

- aws/ecs/ecs/run.go
Fix ECS SSM Parameter name
Motivation
----------
> Fix SSM parameter name in ECS

- .gitignore
Add `.vscode` and `.DS_Store` to `.gitignore`.
Motivation
----------
> Ignore VSCode and MACOS files

- command/filemanager.go
Add function to copy folder in FileManager
Motivation
----------
> Add function to copy folder in FileManager

- aws/eks/eks/nodeGroups.go
- aws/eks/eks/role.go
- aws/eks/eks/run.go
- aws/iam/role.go
> Fix Windows support for EKS

- aws/environment.go
- aws/scenarios/vm/ec2VM/ec2VM.go
- aws/scenarios/vm/os/windows.go
- common/agentinstall/install.go
- common/agentinstall/params.go
- common/os/macos.go
- common/os/os.go
- common/os/unix.go
- common/os/windows.go
- common/vm/vm.go
Add support for Windows OS on AWS.
Motivation
----------
> Add support for Windows OS on AWS

- aws/scenarios/microVMs/microvms/resources/arm64/domain.xls
Fixes domain xml for arm64 microVMs
micro-vm scenario
Motivation
----------
> Fix arm64 domain xml

- .github/CODEOWNERS
> Make ebpf-platform as owners for microvms scenario

- aws/ec2/ec2/vm.go
- aws/environment.go
- aws/environmentDefaults.go
This PR adds a configuration option for setting the `InstanceInitiatedShutdownBehavior` attribute of an ec2 VM.
Motivation
----------
> Add config option for setting the default shutdown behavior of ec2 VM

- aws/scenarios/microVMs/config/config.go
- aws/scenarios/microVMs/microvms/libvirt.go
- aws/scenarios/microVMs/microvms/libvirt_fs.go
- aws/scenarios/microVMs/microvms/provision.go
- aws/scenarios/microVMs/microvms/resources/amd64.go
- aws/scenarios/microVMs/microvms/run.go
- aws/scenarios/microVMs/sample-vm-config.json
This PR adds config options to the `microVMs` scenario for passing an ami id, selecting whether provisioning should be done, and setting the working directory.
This impacts the `microVMs` scenario only.
Motivation
----------
> Add config options for selecting pre-provisioned AMI

- aws/environmentDefaults.go
> Add AWS Agent QA

- common/config/environment.go
- common/utils/connection.go
- common/vm/vm.go
- datadog/agent/install.go
This PR adds the data needed by the client in `datadog-agent` to interact with a `VM` and with an `Agent`.
Motivation
----------
> Add deserializer for client in datadog-agent

- aws/environment.go
Allow authentication with metadata in CI.
Motivation
----------
> Allow usage of metadata API for auth on AWS

- .github/workflows/lint.yml
- .gitlab-ci.yml
- aws/ecs/fargateService.go
- aws/ecs/nodeGroups.go
- aws/scenarios/dockerVM/run.go
- aws/scenarios/ecs/run.go
- aws/scenarios/eks/run.go
- aws/scenarios/microVMs/microvms/provision.go
- aws/scenarios/microVMs/microvms/resources/default.go
- aws/scenarios/microVMs/microvms/run.go
- azure/aks/cluster.go
- azure/scenarios/aks/run.go
- azure/scenarios/vm/run.go
- command/docker.go
- command/utils.go
- common/os/windows.go
- common/vm/vm.go
- main.go
- registry/scenarios.go
- registry/scenarios/import.go
> Remove registration for scenarios replace by hardcoded list in registry

- aws/scenarios/vm/ec2VM/ec2VM.go
- aws/scenarios/vm/ec2VM/params.go
- azure/compute/vm/params.go
- common/vm/params.go
- datadog/agent/install.go
- datadog/agent/params.go
This PRs add several small improvements:
- Export agent.Params
- WithOS doesn't require architecture
- Remove unused keypair field
> Small api improvements

- common/utils/docker.go
- datadog/agent/docker.go
- datadog/agent/docker/agentParams.go
- datadog/agent/ecs.go
- datadog/agent/ecsFargate.go
- datadog/agent/helm.go
- helm/helm.go
> Support custom image in ECS and Kubernetes

- aws/scenarios/microVMs/microvms/resources/distro.go
Adds the firmware and the nvram backing store for the firmware for arm64 micro-vms.
Motivation
----------
> Add firmware for arm64 vms

- command/docker.go
- command/unixOSCommand.go
- command/windowsOSCommand.go
Fix dockervm scenario setup, pass whoami command output to usermod command
Also fixing commands being initialised even when base command was `nil`
dockerVM
Motivation
----------
> [docker] 🐛  fix whoami using command output

- tasks/vm.py
> [invoke] fix vm debug option

- tasks/deploy.py
- tasks/vm.py
Go through keypair validation only when required in config
Motivation
----------
> [invoke] 🐛 check keypair only when required in config

- Dockerfile
This PR adds the xsltproc dependency which is used by pulumi-libvirt to modify resource xmls.
Motivation
----------
> Add dependencies used by microvm scenario.

- aws/scenarios/microVMs/microvms/domain.go
- aws/scenarios/microVMs/microvms/libvirt.go
- aws/scenarios/microVMs/microvms/libvirt_fs.go
- aws/scenarios/microVMs/microvms/resources/amd64.go
- aws/scenarios/microVMs/microvms/resources/arm64.go
- aws/scenarios/microVMs/microvms/resources/default.go
- aws/scenarios/microVMs/microvms/resources/default/pool_local.xls
- aws/scenarios/microVMs/microvms/resources/default/volume_local.xls
- aws/scenarios/microVMs/microvms/resources/distro.go
- aws/scenarios/microVMs/microvms/resources/resources.go
- aws/scenarios/microVMs/sample-vm-config.json
Launch microvms locally on linux machines.
Motivation
----------
> Add support to launch local microvms

- requirements.txt
Fix requirements.txt by adding pydantic to the list. pydantic is used in `tasks/config.py`
> Fix requirements.txt by adding pydantic to the list

- aws/environment.go
- common/config/environment.go
Move more configmap keys to public, so other repos can use them to assign parameters of the configmap
Motivation
----------
> [environment] public configmap variables

- .gitignore
- .test_infra_config.yaml.example
- tasks/config.py
- tasks/deploy.py
- tasks/destroy.py
Add example of profile config, used in documentation
This PR also updates tasks to the new profile format
```
stackParams:
ddinfra:
"aws/defaultKeyPairName": ""
"aws/defaultPublicKeyPath": ""
"foo": "a_variable"
configParams:
aws:
keyPairName: ""
publicKeyPath: ""
agent:
apiKey: "xxxxxxxx"
options:
checkKeyPair: False
```
Motivation
----------
Help developers rump up and setup their environment
> [invoke] add profile example

- tasks/config.py
Properly type stack params type in config file
VM
Motivation
----------
Fix broken `inv create-vm` task
> [inv] properly type stack params

- aws/scenarios/dockerVM/run.go
- aws/scenarios/vm/ec2VM/params.go
- aws/scenarios/vm/run.go
- common/config/environment.go
- tasks/docker.py
This PR fix `inv create.vm` and `inv create.docker`
Motivation
----------
> Handle InfraOSFamily inside ec2 params

- aws/environmentDefaults.go
> Add agent-sandbox and fakeintake clusters

- aws/scenarios/eks/run.go
- aws/scenarios/kindvm/run.go
- aws/scenarios/microVMs/microvms/run.go
- aws/scenarios/vm/ec2VM/ec2VM.go
- azure/compute/vm/azurevm.go
- command/runner.go
- common/vm/vm.go
- datadog/agent/helm.go
- helm/helm.go
- kubernetes/kind-cluster.yaml
- kubernetes/kind.go
- registry/scenarios.go
Finish Kind cluster code (Kubernetes In Docker, https://kind.sigs.k8s.io/), notably patching Kubeconfig to be reachable from VM IP.
Add a dedicated scenario named `kindvm`
Motivation
----------
> Finish Kind cluster on VM

- aws/scenarios/microVMs/microvms/domain.go
- aws/scenarios/microVMs/microvms/libvirt.go
- aws/scenarios/microVMs/sample-vm-config.json
This PR makes the ip and domain mapping deterministic.
Motivation
----------
> Make ip <-> domain mapping deterministic

- tasks/setup.py
Properly convert path to string
None
Motivation
----------
> [inv] fix default public key path

- .gitignore
Ignore venv in git status
Motivation
----------
Local installation of dependencies
> Ignore python venv for local installation of requirements

- components/datadog/agent/install.go
- components/datadog/agent/params.go
- scenarios/aws/vm/ec2VM/params.go
- tasks/destroy.py
Improve the documentation for `agent.Params` and `ec2Vm.Params` used by https://github.com/DataDog/datadog-agent/pull/17301.
> Improve Params doc

- tasks/destroy.py
Improve `destroy-XX` tasks. Calling `inv create-vm` and then  `inv destroy-vm` destroys correctly the vm (Before the name of the stack was not correctly recognise).
> Improve destroy task

- README.md
Add instructions on invoke tasks
None
Motivation
----------
> [readme] update with inv tasks instructions

- Dockerfile
Update go version to match agent
Motivation
----------
> Update go version to match agent

- README.md
- tasks/deploy.py
- tasks/destroy.py
Migrate from `sandbox` to `agent-sandbox` account to create ephemeral environments
All
Motivation
----------
`agent-sandbox` is ready and full configured, with additional clean up job running daily to remove any leftover instance
> [invoke] migrate to agent-sandbox

- README.md
- tasks/deploy.py
- tasks/destroy.py
Fix main on migration to agent-sandbox
Motivation
----------
> really migrate to agent-sandbox

- tasks/setup.py
- tasks/tool.py
Use winget to install pulumi on Windows
setup
Motivation
----------
> windows setup support

- common/config/environment.go
- resources/aws/environmentDefaults.go
> Fix missing SG on new tenants, upgrade to k8s 1.26

- scenarios/aws/microVMs/microvms/libvirt.go
- scenarios/aws/microVMs/microvms/network.go
This PR adds some iptable rules to host of the micro-vms, to allow communication with NFS server.
Motivation
----------
Implement filesystem sharing between host and guest amazon linux 2 VMs, since amazon linux is not compiled with 9P support.
> Setup NFS share

- Dockerfile
> Attempt to fix `main` branch by sticking on `bullseye` instead of `bookworm`.

- resources/aws/environment.go
- resources/aws/environmentDefaults.go
- scenarios/aws/eks/run.go
> Fix EKS ingress on agent-qa from CI

- Dockerfile
> Downgrade to Python 3.10 for compatibility with invoke 1.x

- components/vm/params.go
- resources/azure/compute/azureparams/params.go
- scenarios/aws/vm/ec2params/params.go
- scenarios/aws/vm/ec2vm/ec2VM.go
- scenarios/aws/vm/run.go
This PR adds methods to inject exiting environment into EC2 VM.
> Inject existing AWS environment into EC2 VM.

- resources/aws/environment.go
- resources/azure/environment.go
> Export all cloud environment variables

- tasks/deploy.py
It automatically creates the pulumi stack in the invoke task if it didn't exist already.
This is invoke task only so none.
Motivation
----------
Reducing the need for user interaction when using the invoke task.
I am writing a script which uses the invoke task to spawn multiple VM (each in their own stack) and I currently have to validate the creation of each stack manually.
Listing the stacks and checking the names is the best way I could find to check if the stack exists without any side effect (`pulumi stack select` has the side effect of selecting the stack).
> [invoke-task] Automatically create the pulumi stack

- scenarios/aws/microVMs/microvms/run.go
Fix bug introduced in #206 
The bug resulted in the creation of a new AWS environment for every instance created.
Motivation
----------
> Create AWS environment once

- Dockerfile
> Fix override of AWS CLI due to datadog-agent repo requirements.txt

- tasks/deploy.py
- tasks/destroy.py
- tasks/docker.py
- tasks/ecs.py
- tasks/eks.py
- tasks/tool.py
- tasks/vm.py
The wrap function is not returning the proper wrapping string, we were using 2 different ways to launch a process, unified both to use invoke context run.
All
Motivation
----------
Fix bug in invoke task introduced in https://github.com/DataDog/test-infra-definitions/pull/211
> 🐛 Fix bug in invoke task

- tasks/tool.py
Fix typo in sso account name that prevents usage of some tasks
At least destroy-vm
Motivation
----------
> Removed trailing dash on account name

- scenarios/aws/microVMs/vmconfig/config.go
> Make json tag for VMSet images consistent

- scenarios/aws/vm/ec2os/os.go
- scenarios/aws/vm/ec2os/rockyLinux.go
- scenarios/aws/vm/run.go
- tasks/tool.py
Add support for RockyLinux
VM
Motivation
----------
Rocky Linux is one of the agent supported OS, this will help agent devs QAing on Rocky Linux
> [vm] add support for rocky linux

- common/namer/namer.go
Fix a bug in `(Namer) WithPrefix` where calling `WithPrefix` on the same parent namer twice may make the first child namer use the prefix of the second one.
Use a local variable to cache a computation which was done twice.
Motivation
----------
Bug.
> Follow up #240: AETT-186 Ensure `namer.DisplayName` doesn’t generate a name exceeding a maximum

- .github/workflows/lint.yml
- pyproject.toml
- setup.cfg
- tasks/__init__.py
- tasks/config.py
- tasks/deploy.py
- tasks/destroy.py
- tasks/doc.py
- tasks/docker.py
- tasks/ecs.py
- tasks/eks.py
- tasks/setup.py
- tasks/tool.py
- tasks/vm.py
Add same python linters as datadog-agent
N/A
Motivation
----------
> Add same linters as datadog-agent

- components/command/unixOSCommand.go
Fix the CreateDirectory pulumi delete action. 
Motivation
----------
> Fix the CreateDirectory pulumi delete action

- components/vm/vm.go
Add a namer to VMs to uniquely name vms resources, such as connections. Connection is used to name the "wait for ready" command, that is currently preventing creating multiple VMs on the same stack. 
VM
Motivation
----------
This is needed to support multiple VMs on one single stack, enabling for example network testing where one VM runs the Agent and one VM runs a network server
> [vm] add vm namer to name vm resources with an unique name

- README.md
update readme doc
use sso-agent-sandbox-account-admin
Motivation
----------
> Update README.md use sso-agent-sandbox-account-admin

- tasks/setup.py
- tasks/tool.py
Linux setup install pulumi
inv setup
Motivation
----------
> Linux setup install pulumi

- requirements.txt
- tasks/config.py
Bump pydantic to 2.3.0, fixing new errors
None
Motivation
----------
> [python] bump pydantic to 2.3.0

- components/datadog/agentparams/params.go
to hook https://process.datadoghq.com/api/v1/connections
Motivation
----------
> fake process and process-events intake

- resources/aws/environmentDefaults.go
> Set default instance to medium

- components/command/filemanager.go
- components/datadog/agent/install.go
Simplify file manager API by removing the need to set a resource name
Motivation
----------
Have a simpler API
> Simplify FileManager API:

- integration-tests/invoke_test.go
- tasks/doc.py
- tasks/docker.py
- tasks/ecs.py
- tasks/eks.py
- tasks/tool.py
- tasks/vm.py
Add some desktop notification once the stack is created.
User now needs to press a key before the connection command is copied to clipboard, to avoid unexpected things in the clipboard
Motivation
----------
Nice to have notification when the stack can take a long time to create
I created the notification on MacOS. I did not implement it for Linux and Windows since I am not able to test anything without a Linux or Windows system with a desktop
> Add notification after stack is created: MacOS, copy to clipboard now requires to press a key

- components/datadog/apps/fakeintake/fargateFakeintakeService.go
- scenarios/aws/fakeintake.go
- scenarios/aws/fakeintake/fakeintakeparams/params.go
- scenarios/aws/vm/run.go
Expose option to be able to disable Load Balancer from tests
Motivation
----------
> Add FakeIntakeParams to be able to disable LB from datadog-agent tests

- scenarios/aws/microVMs/microvms/domain.go
- scenarios/aws/microVMs/microvms/libvirt.go
- scenarios/aws/microVMs/microvms/resources/amd64.go
- scenarios/aws/microVMs/microvms/resources/arm64.go
- scenarios/aws/microVMs/microvms/resources/default.go
- scenarios/aws/microVMs/microvms/resources/distro.go
- scenarios/aws/microVMs/microvms/resources/resources.go
- scenarios/aws/microVMs/vmconfig/config.go
This PR adds config option to use a file for console output.
Motivation
----------
Debug VM startup issues in the CI.
> Add new console type.

- scenarios/aws/microVMs/microvms/libvirt.go
Fixes some linting issues that somehow got into `main`.
Motivation
----------
> fix microvm lint issue

- scenarios/aws/microVMs/microvms/libvirt_fs.go
This PR checks all downloaded volumes to see if they are compressed with xz. If so, we extract them.
Associated PR in ami-builder to build compressed VM images: https://github.com/DataDog/ami-builder/pull/122
Motivation
----------
> Extract volume if xz compressed

- components/datadog/apps/fakeintake/fargateFakeintakeService.go
- scenarios/aws/fakeintake/fakeintakeparams/params.go
Add a `WithImageURL` parameter for the fakeintake.
Fakeintake
Motivation
----------
Being able to use a different fakeintake image when testing.
> Add fakeintake WithImageURL parameter

- tasks/deploy.py
- tasks/ecs.py
- tasks/eks.py
Add `install_workload` for ECS (was already present for EKS)
Motivation
----------
> [invoke] Add install_workload to ECS

- components/datadog/apps/fakeintake/fargateFakeintakeService.go
We had an issue where two fakeintake service where created when we want to create a fakeintake withtout load balancer. This PR solves this issue as well a refactoring a little bit the fakeintake service creation
Motivation
----------
> Fix 2 fakeintakes creation when not using load balancers

- README.md
- tasks/tool.py
Use the `notify-send` utility to implement the notify function for Linux.
Motivation
----------
> Implement notification for the Linux platform

- scenarios/aws/microVMs/microvms/domain.go
- scenarios/aws/microVMs/microvms/libvirt_fs.go
- scenarios/aws/microVMs/vmconfig/config.go
- scenarios/aws/microVMs/vmconfig/load.go
This PR allows users to specify list of tags for VMSets. This allows a user to provide unique list of identifier to differentiate vmsets.
Motivation
----------
> Allow list of tags for each vmset

- resources/hyperv/environment.go
- resources/hyperv/vm.go
- resources/hyperv/windows.go
- scenarios/hyperv/vm.go
Add scaffolding for spawning HyperV VMs on Windows using local command (not working, requires implementation).
Motivation
----------
> Add scaffolding of HyperV VMs using local Command

- scenarios/aws/microVMs/microvms/run.go
This PR reorders the initialization commands run inside the micro-vms.
Motivation
----------
There were occasional failures of commands running after sshd reload. 
> Reload sshd daemon in the VM at the end

- components/datadog/agent/ecsFargate.go
> Fix a format string vulnerability

- components/datadog/agent/ecsFargate.go
- components/datadog/apps/nginx/ecs.go
- components/datadog/apps/nginx/ecsFargate.go
- components/datadog/apps/redis/ecs.go
- components/datadog/apps/redis/ecsFargate.go
- resources/aws/ecs/fargateService.go
- scenarios/aws/ecs/run.go
Add Redis and NGinx workloads for Fargate
ECS Fargate
Motivation
----------
Needed for ECS Fargate E2E tests
> [Fargate] Add Redis and NGinx workloads

- scenarios/aws/ec2/vm_run.go
I've sneaked in a mistake when signing all my commits on this PR https://github.com/DataDog/test-infra-definitions/pull/535
Fixing it
> Fix scenario ec2 vm run

- scenarios/aws/microVMs/microvms/domain.go
- scenarios/aws/microVMs/microvms/libvirt.go
Motivation
----------
We want to leave CPU 0 for system related tasks.
> Do not pin VM CPU to host CPU 0

- scenarios/aws/ec2/vm.go
Code was merged in between merge of https://github.com/DataDog/test-infra-definitions/pull/591
Motivation
----------
> Fix merge conflict between last PRs

- resources/aws/environment.go
> Fix incorrect param name used for instance profile

- components/datadog/apps/npm-tools/images/go-httpbin/Dockerfile
- components/datadog/apps/npm-tools/images/npm-tools/Dockerfile
Add new Docker images in ghcr.io for NPM e2e tests
Motivation
----------
> [NPM] teste2e go-httpbin and npm-tools Docker images

- integration-tests/invoke_test.go
- tasks/config.py
- tasks/deploy.py
- tasks/setup.py
Add support for parsing log level and lot to stderr to local config file
Tasks
Motivation
----------
Tasks are currently broken when local config contains pulumi params
> [setup] add pulumi params to config

- .github/dependabot.yml
- .github/workflows/docker-publish.yml
Add npm docker images apps
Motivation
----------
linked to this [PR](https://github.com/DataDog/datadog-agent/pull/22769)
> [NPM] add npm docker images apps

- .github/jwt.sh
- .gitlab-ci.yml
- Dockerfile
Generate `GITHUB_TOKEN` from Github App
None
Motivation
----------
We're getting constantly rate limited by github when building the runner image, as we don't use authenticated requests.
> [gitlab] get github_token from app

- components/datadog/agent/ecs.go
- components/datadog/ecsagentparams/params.go
Enable NPM in the agent for ECS deployment
Motivation
----------
> [ECS] enable NPM in the agent

- components/datadog/apps/npm-tools/ecs.go
ECS workload used by NPM tests
Motivation
----------
> [ECS] workload ECS for NPM tests

- components/datadog/agent/ecs.go
- components/datadog/ecsagentparams/params.go
ECS add parameter WithNetworkMode when deploying the daemon agent.
Motivation
----------
> [ECS] add parameter WithNetworkMode 

- components/datadog/apps/tracegen/images/tracegen/main.go
This PR updates the tracegen app to resolve DD_AGENT_HOST for ECS
aws/ecs in a future PR
Motivation
----------
We need to resolve `DD_AGENT_HOST` for ECS. We can't modify the entrypoint as the image doesn't have curl.
> Update tracegen to resolve DD_AGENT_HOST

- components/datadog/agent/host_linuxos.go
Fix the retry I added on install script download for installation made on CI pipelines.
Fix for PR: https://github.com/DataDog/test-infra-definitions/pull/558
Motivation
----------
> Fix retry on agent install for pipelines

- components/datadog/apps/tracegen/images/tracegen/main.go
> Use a network call to retrieve DD_AGENT_HOST

- components/datadog/dockeragentparams/params.go
This PR modifies the fakeintake url that is used in the docker scenario. This is because the fakeintake now uses https.
aws/dockervm
Motivation
----------
Fix e2e test.
> fix fakeintake url on docker scenario

- scenarios/aws/microVMs/microvms/libvirt_fs.go
Add retry option to curl
Motivation
----------
> Retry vm image download with curl if it fails

- components/datadog/agent/host_linuxos.go
- components/docker/docker.go
- components/kubernetes/kind.go
Reverts DataDog/test-infra-definitions#665
There are errors on datadog-agent
> Revert "Add silent, show-error, fail and retries to curl commands"

- Dockerfile
- components/datadog/agent/host_linuxos.go
- components/docker/docker.go
- components/kubernetes/kind.go
- integration-tests/invoke_test.go
- tasks/docker.py
Reverts DataDog/test-infra-definitions#668 adding tests for the docker environment
> Revert "Revert "Add silent, show-error, fail and retries to curl commands""

- .github/workflows/docker-publish.yml
- components/datadog/apps/logger/images/logger/Dockerfile
- components/datadog/apps/logger/images/logger/go.mod
- components/datadog/apps/logger/images/logger/main.go
- components/datadog/apps/logger/k8s.go
Adds a "logger" datadog for use in e2e tests in the agent.
Motivation
----------
Needed for e2e tests in the agent.
> Initial commit for logger app

- scenarios/aws/microVMs/microvms/resources/distro.go
FIx lint-go
Motivation
----------
> Fix lint-go

- Dockerfile
Add pulumi time resource
Co-authored-by: julien-lebot <julien.lebot@datadoghq.com>
(cherry picked from commit ddba83b18cf206c2ff047aaea65bdc04218f012d)
Motivation
----------
> Re-add pulumi time

- requirements.txt
- tasks/__init__.py
- tasks/deploy.py
- tasks/doc.py
- tasks/pipeline.py
- tasks/tool.py
- tasks/vm.py
This is a follow-up PR to https://github.com/DataDog/datadog-agent/pull/23581.
It prints a detailed error if the pipeline is outdated as images from pipelines expire after 24h.
`create-vm` task
Motivation
----------
> [create-vm-verify-pipeline] Added pipeline verification to deploy

- components/datadog/apps/npm-tools/k8s.go
Add npm-tools k8s workload
Motivation
----------
> [NPM] add npm-tools k8s workload

- .github/workflows/auto-bump-datadog-agent.yml
The auto-bump is not working as intendent since it runs on pull_request close event, and it does not take the commit on main branch
Motivation
----------
> CI(auto-bump): Try to fix auto bump

- .github/workflows/auto-bump-datadog-agent.yml
Remove `if` condition that was always skipping execution on main
Motivation
----------
> Job is now executed on every main PR

- .github/workflows/auto-bump-datadog-agent.yml
> Fix(auto-bump): THE auto-bump fix

- .github/workflows/docker-publish.yml
> [github] skip prompt on cosign

- .github/workflows/docker-publish.yml
- components/datadog/apps/jmxfetch/docker-compose.yaml
- components/datadog/apps/jmxfetch/docker.go
- components/datadog/apps/jmxfetch/images/jmx-test-app/Dockerfile
- components/datadog/apps/jmxfetch/images/jmx-test-app/SimpleApp.java
- components/datadog/apps/jmxfetch/images/jmx-test-app/run.sh
Adds a simple Java app to allow testing JMXFetch
None at the moment.
Motivation
----------
It would be good to have an end to end test for JMXFetch.
> Adding a Simple Java app to allow testing JMXFetch with the Agent

- components/kubernetes/istio/istio.go
Add Istio support for kubernetes
deploying via helm charts and optional setup of testing application and gateway routing example
Motivation
----------
> Istio component

- components/datadog/updater/install_script.sh
updater package is being renamed datadog-installer, supporting both until migration is completed
> prepare updater rename

- components/datadog/updater/install_script.sh
This PR addresses the specificities of installing on suse
Installer tests when running on SUSE
Motivation
----------
> installer: fix installing on SUSE

- components/datadog/updater/install_script.sh
Fixes refreshing suse repo without a terminal attached
Motivation
----------
> updater: fix suse repo refresh without a terminal

- scenarios/aws/fakeintake/fakeintake.go
This PR will switch the storage driver to sql for the fakeintake.
all
Motivation
----------
> [CONTINT-3920] use sql in the fakeintake

- components/datadog/updater/install_script.sh
This PR is the 3rd attempt at installing the installer on suse when no TTY is attached :')
Motivation
----------
> updater: force install script to import our GPG keys

- common/config/environment.go
- components/kubernetes/kind.go
- resources/aws/environment.go
- resources/aws/environmentDefaults.go
- resources/azure/environment.go
- resources/hyperv/environment.go
- scenarios/aws/kindvm/run.go
Update kind scenario to use `kindest/node` image from our private registry
Motivation
----------
> Use private registry kind image

- components/datadog/updater/install.go
- components/datadog/updater/install_script.sh
- scenarios/aws/installer/lab.go
Bootstrap agents on the installer lab hosts
* Installer lab
* VM creation with installer (should be a noop)
Motivation
----------
> [FA] Bootstrap agents on lab hosts

- common/utils/yaml.go
- components/datadog/agent/kubernetes.go
- components/datadog/kubernetesagentparams/params.go
#What does this PR do?
It implements the merge on our side waiting for https://github.com/pulumi/pulumi-kubernetes/pull/2963 to be merged upstream
Motivation
----------
> Temporary fix for Values YAML merge

- components/datadog/updater/install_script.sh
Fixes the installer VM provisioning by making sure that the `datadog-installer` `systemd` unit exists before restarting it. Whether the unit exists or not depends on user input.
new-e2e-installer
Motivation
----------
E2E passing when we bump test-infra-definition ref in the agent
> fix(installer): Check that unit exists before restarting it

- common/config/environment.go
- scenarios/aws/installer/lab.go
- tasks/doc.py
- tasks/installer.py
Add a `--site` for the installer lab
Installer scenario
Motivation
----------
> [FA] Add site for the installer lab

- components/datadog/updater/install.go
- components/datadog/updater/install_script.sh
- components/os/test.sh
- scenarios/aws/installer/lab.go
Change the VMs for the lab
Updater scenario
Motivation
----------
> [FA] Add more vms to lab

- components/datadog/agent/kubernetes_helm.go
Set explicit CPU and memory requests and limits to the agent
* `aws/eks`
* `aws/kind`
Motivation
----------
The `TestCPU` container e2e test is currenly flaky.
That’s because the `container.cpu.usage` metric has become shaky since the creation of the test that asserts it.
Here is the expected behavior of this metric:
See how the values are stable and stays inside the green ribbon.
And here is the current behavior of this metric:
See how the values are now sometimes above the expectation and sometimes below the expectation.
These erratic values can be the sign that the agent isn’t scrapping the values at the expected regular interval because it is CPU starved.
We need to set explicit CPU …
> Set explicit resources requests and limits to the agent

- components/datadog/apps/logger/images/logger/main.go
- components/datadog/apps/logger/images/logger/main_test.go
This fixes issues with the logger test app exiting if spun up before the Agent is ready to accept logs on TCP or UDP.
New logs end to end test for TCP and UDP logs.
Motivation
----------
Want to automate end to end tests for TCP/UDP before building a new feature.
None.
> Making the logger server more robust

- components/docker/docker.go
Reverts DataDog/test-infra-definitions#802
> Revert "Let docker-compose up handle the diff instead of forcing down on each change"

- components/docker/docker.go
Bump docker compose version we use.
Motivation
----------
> Bump docker compose version

- scenarios/aws/fakeintake/fakeintake.go
Add a line to log link to the fakeintake dashboard, can be useful to debug tests
Motivation
----------
> Log fakeintake dashboard link

- components/datadog/apps/logger/images/logger/Dockerfile
- components/datadog/apps/logger/images/logger/README.md
- components/datadog/apps/logger/images/logger/send-message.sh
Cleans up the Dockerfile used by the Logger app and adds a helper script to quickly get it to log messages.
Any that use the Logger app.
Motivation
----------
Makes it easier to get the app to log messages.
None.
> Updated Logger docker image to have a helpful posting script

- components/datadog/agent/kubernetes.go
Pass the DisableLogsContainerCollect to HelmInstallationArgs
Motivation
----------
> Use DisableLogsContainerCollectAll in HelmInstallationArgs

- components/command/filemanager.go
- components/command/osCommand.go
- components/command/runner.go
- components/command/unixOSCommand.go
- components/command/windowsOSCommand.go
- components/datadog/updater/install_script.sh
- components/docker/component.go
- components/kubernetes/kind.go
- resources/local/environment.go
> Use CopyFile in the CopyInlineFile to avoid encoding issues

- components/datadog/agent/kubernetes_helm.go
Fix quotes breaking things 
Motivation
----------
> Remove quote around use_ssl boolean

- scenarios/aws/installer/lab.go
Now use the install script to install the installer + datadog-agent
`invoke create-installer-lab --site "<SITE>"`
Motivation
----------
> [FA] Use install script in lab

- components/datadog/dockeragentparams/params.go
- components/datadog/dogstatsd-standalone/docker_image.go
Fix some typos
Motivation
----------
🤦 
https://github.com/DataDog/test-infra-definitions/pull/845
> Fix some typos

- components/datadog/agent/docker_image.go
- components/datadog/agent/host_linuxos.go
- components/datadog/agent/host_windowsos.go
- components/datadog/agentparams/params.go
- components/datadog/agentparams/params_test.go
- components/datadog/dockeragentparams/params.go
- components/datadog/dogstatsd-standalone/docker_image.go
- components/datadog/kubernetesagentparams/params.go
- components/datadog/updater/install_script.sh
- **Revert "Fix some typos (#871)"**
- **Revert "Store the pipeline ID directly in the pipelineId parameter (#845)"**
We found some issues and we'll investigate once the problem will be fixed in the agent
Motivation
----------
> Revert the `pipeline-` changes

- components/datadog/agentparams/params.go
- resources/aws/environment.go
- resources/aws/environmentDefaults.go
- scenarios/aws/fakeintake/fakeintake.go
Add the possibility to define several load balancer and to randomly select one to connect to the fakeintake.
It should allow us to overcome the 100 rules limit on LB
Motivation
----------
> Add multiple load balancer test-infra

- components/datadog/apps/cws/images/cws-centos7/Dockerfile
This PR reduces the size of `cws-centos7` by ~60MiB by doing a bit of yum clean post-install
Motivation
----------
> [CWS-2572] reduce the size of `cws-centos7` image

- tasks/config.py
Add a warning when `sandbox` account is used
Motivation
----------
> Deprecation warning for sandbox account

- components/datadog/agent/kubernetes_helm.go
Make the default Helm values overridable
Scenarios with agent installed with Helm
Motivation
----------
> [ADXT-360] [e2e] Refactor default helm values to make then overridable

- components/datadog/apps/cpustress/ecs.go
- components/datadog/apps/dogstatsd/ecs.go
- components/datadog/apps/nginx/ecs.go
- components/datadog/apps/nginx/ecsFargate.go
- components/datadog/apps/npm-tools/ecs.go
- components/datadog/apps/prometheus/ecs.go
- components/datadog/apps/redis/ecs.go
- components/datadog/apps/tracegen/ecs.go
- components/ecs/workload.go
Create a new Workload type to use with ECS Apps
Motivation
----------
> Extend Workload to ECS app

- components/datadog/agent/host_linuxos.go
Fail fast when the agent installation fails
Motivation
----------
> Fail fast when agent install fails

- Dockerfile
- scenarios/aws/ec2/os_resolver.go
Add CentOS 7 arm64 AMI
VM
Motivation
----------
We do have one AMI for arm64 CentOS 64, let's use it!
> [centos] add centos 7 arm64 AMI

- common/config/environment.go
- components/datadog/dockeragentparams/params.go
- components/datadog/kubernetesagentparams/params.go
- go.mod
- go.sum
- resources/aws/environment.go
- resources/azure/environment.go
- resources/hyperv/environment.go
- resources/local/environment.go
Before trying to install the agent we check if the image exists on the ECR, if not we fail early with an explicit error
Motivation
----------
> [ADXT-367] [e2e] Add explicit failure when the image is no longer available in the registry

- components/datadog/dockeragentparams/params.go
It sets the correct URL for the Logs Agent when Fake Intake used.
Any that run the Agent in Docker and are trying to send logs back to the Fake Intake.
Motivation
----------
I want some e2e tests to check a feature.
None.
> Fixing URL used to send logs in a container

- components/datadog/agent/helm/kubernetes_agent.go
- components/datadog/agent/kubernetes.go
- components/datadog/agent/kubernetes_object_ref.go
Small changes to Kubernetes Agent output to have Windows agent info, and to have a bit more convenient objects
Motivation
----------
> Update KubernetesAgentOutput to be a bit more convenient

- scenarios/aws/eks/run.go
Forward the AWS profile to the EKS cluster
EKS scenarios
Motivation
----------
Following https://github.com/DataDog/test-infra-definitions/pull/917 we do not need to explicitly wrap commands into `aws-vault` but it does not work for EKS because we need to forward it to the cluster, otherwise it's not taken into account and we get some `Unable to locate credentials. You can configure credentials by running "aws configure".` errors
- Tested uncommenting the redis and nginx apps because we have some flake issues with it
- I'll do the same thing in the Agent
> Forward the AWS profile to the EKS cluster

- components/datadog/agent/helm/kubernetes_agent.go
- components/datadog/kubernetesagentparams/params.go
Fix linter issue
Motivation
----------
> Fix linter :(

- .github/CODEOWNERS
- .github/workflows/docker-publish.yml
- components/datadog/apps/fips/images/fips-server/Dockerfile
- components/datadog/apps/fips/images/fips-server/gen_certs.sh
- components/datadog/apps/fips/images/fips-server/go.mod
- components/datadog/apps/fips/images/fips-server/run.sh
- components/datadog/apps/fips/images/fips-server/src/main.go
- components/datadog/apps/fips/images/fips-server/src/server.go
- components/datadog/apps/fips/images/fips-server/src/tls.go
It adds a Docker image that will help us testing FIPS encryption on the Agent
Motivation
----------
> Add Dockerfile for a fips server that will be used by e2e tests

- scenarios/aws/fakeintake/fakeintake.go
Using SQL has shown some flakiness with the Fakeintake. Let's disable it for now
Motivation
----------
> Use memory instead of SQL fakeintake

- tasks/aws/deploy.py
- tasks/aws/docker.py
- tasks/aws/ecs.py
- tasks/aws/eks.py
- tasks/aws/kind.py
- tasks/azure/aks.py
- tasks/azure/common.py
- tasks/deploy.py
- tasks/doc.py
Add parameters to configure the docker image to use in the invoke tasks
Motivation
----------
We would like to have the ability to use locally built Agent images to be used in e2e tests in the future. These images will be pushed to a registry so we need to provide the image path
https://datadoghq.atlassian.net/browse/ADXT-497
> Add parameters to configure the docker image to use in the invoke tasks

- common/utils/yaml.go
- components/datadog/agent/helm/kubernetes_agent.go
- components/datadog/agent/kubernetes_helm.go
- components/datadog/kubernetesagentparams/params.go
…
Build OTel config to have the fakeintake URL.
It also refactor a bit how we manage OTel configuration
Motivation
----------
> Improve management of Otel configuration and configure fakeintake in otel config

- components/datadog/apps/logger/images/logger/README.md
- components/datadog/apps/logger/images/logger/main.go
- components/datadog/apps/logger/images/logger/main_test.go
Adds ability to log to file from logger app.
Means AML can implement some more e2e tests for logs.
Motivation
----------
I'd like to log to a file.
> Adding ability to log to a file using logger app

- components/datadog/agent/helm/kubernetes_agent.go
Fix `WithoutDualShipping` flag that was not working properly
Motivation
----------
> Fix flag to disable dual shipping

- components/datadog/agent/docker_image.go
Fix OTel tag
Motivation
----------
> Correctly use otel-tag if otel agent is enabled

- tasks/setup.py
better notice message
N/A
Motivation
----------
> clarify rsa pubkey match notice

- common/config/environment.go
- components/datadog/agent/ecs.go
- components/datadog/agent/ecsFargate.go
- Add a new config entry point `DDAgentExtraEnvVars` to allow users to pass into environment variables
Motivation
----------
> add DDAgentExtraEnvVars

- tasks/setup.py
Add optional step to create basic SSO profiles in `~/.aws/config` for agent-sandbox
setup
Motivation
----------
simplify setup on platforms where macos laptop setup script can't be used
steps are skipped if profile name is found in `~/.aws/config`
confirm functionality with
```
AWS_PROFILE=exec-sso-agent-sandbox-account-admin aws s3 ls
```
Windows
```
$env:AWS_PROFILE='exec-sso-agent-sandbox-account-admin'; aws s3 ls
```
> add aws sso setup for agent-sandbox account

- components/datadog/agent/kubernetes_helm.go
Add config environment variable for logs
Motivation
----------
> Fix a small issue with log configuration when dual shipping is disabled

- components/datadog/agent/kubernetes_helm.go
See title.
- Kind
- AKS
- EKS
Motivation
----------
Clean up unnecessary env vars
> remove env var that was added by mistake

- components/datadog/apps/fips/images/fips-server/Dockerfile
- components/datadog/apps/fips/images/fips-server/go.mod
- components/datadog/apps/fips/images/fips-server/go.sum
Run go mod tidy on fips-server 
Motivation
----------
My IDE complains about it
> Run go mod tidy on fips-server

- resources/gcp/environment.go
Automatically log in GCP if needed
Motivation
----------
- Same as https://github.com/DataDog/test-infra-definitions/pull/961 but for GCP!
- Avoid having to manually run the `gcloud` command
> Automatically log in GCP if needed

- .gitignore
- registry/scenarios.go
- resources/gcp/environmentDefaults.go
- resources/gcp/gke/cluster.go
- scenarios/gcp/gke/cluster.go
- scenarios/gcp/gke/run.go
- tasks/gcp/__init__.py
- tasks/gcp/gke.py
- tasks/tool.py
Add support for GKE
None for now
Motivation
----------
Better GCP support
> Add support for GKE

- resources/aws/environmentDefaults.go
Fix wrong fakeintake ECS cluster name
Motivation
----------
> Fix agent sandbox fakeintake ecs

- scenarios/aws/ec2/vm.go
#incident-31096
Motivation
----------
> Do not put special characters in Winwdows random password

- scenarios/aws/ec2/vm.go
> Set at least one lower one upper and one numeric

- components/docker/component.go
Patch `daemon.json` config to not use the default `172.18.0.0/16` IP range that is conflicting with mudkip-f cluster ip range https://github.com/DataDog/k8s-platform-resources/blob/943d780e5db9eb0b6dae5d547732fe8622126df0/values/us1.ddbuild.io/mudkip-f-k8s/values.yaml
And that is now used to run Gitlab runners: https://github.com/DataDog/dd-source/pull/135523
More context #incident-31160
Motivation
----------
> Patch docker daemon to not use ddbuild runner IP range

- scenarios/aws/ec2/vm.go
Revert https://github.com/DataDog/test-infra-definitions/pull/1141 and wrap password in single quotes.
EC2 Windows 
Motivation
----------
Follow up to #incident-31096, keeps higher randomness of the password. This is not strictly required as having upper and lower case alpha chars plus at least one number is enough for Windows rules, this is more in case Microsoft updates their password requirements.
pulumi random's Special includes: `!@#$%&*()-_=+[]{}<>:?` == `-!#$%&()*:?@[]_{}+<=>`
windows accepted special chars include: `'-!"#$%&()*,./:;?@[]^_`{|}~+<=>`
Thus pulumi special chars are a subset of the accepted Windows special chars
I tested this change …
> [ec2][windows] wrap password in single quotes

- Dockerfile
Add vault in the test-infra-definition image
None
Motivation
----------
Have [these tests](https://gitlab.ddbuild.io/DataDog/datadog-agent/-/jobs/659673185) passing
> feat(dockerfile): Add vault for e2e tests

- components/ecs/component.go
- scenarios/aws/ecs/run.go
Create a new ECS cluster component.
Motivation
----------
> Create ECS Cluster component

- .pre-commit-config.yaml
- scenarios/aws/eks/args.go
- scenarios/aws/eks/cluster.go
- scenarios/aws/eks/run.go
- tasks/aws/eks.py
Create a component for creating an EKS cluster. With a simple API to begin with
Motivation
----------
> Create an EKS cluster ready to use component

- components/datadog/agent/kubernetes_helm.go
- resources/gcp/environment.go
- scenarios/gcp/gke/run.go
Set the correct Helm values when the Autopilot flag is passed.
Motivation
----------
> Include autopilot values when passing Autopilot flag

- scenarios/aws/ecs/args.go
- scenarios/aws/ecs/cluster.go
- scenarios/aws/ecs/run.go
Create a component for ECS that we can reuse in datadog-agent provisioner. To avoid code duplication
Motivation
----------
> Create a ready to use ECS componenent

- .github/CODEOWNERS
- .github/workflows/docker-publish.yml
- components/datadog/apps/otel/images/calendar-go/Dockerfile
Adds OTel calendar app for OTel e2e tests
Motivation
----------
> Add OTel calendar app

- scenarios/aws/ecs/cluster.go
Avoid changing cluster name to not break tests
Motivation
----------
> Do not change ECS name to avoid issue with existing tests

- tasks/setup.py
Fix an error that can happen during inv setup when importing a key pair
Motivation
----------
> [ADXT-573] Error in test-infra inv setup task

- resources/aws/environmentDefaults.go
Disable Fargate profile by default.
This is not used in any test for now, and this is a source of flakiness.
Motivation
----------
> Disable Fargate profile by default

- components/datadog/dockeragentparams/params.go
Add a Docker Environment variable to configure the endpoint that should be used to send service discovery payloads
Motivation
----------
> Add env var for service discovery url

- components/datadog/apps/otel/images/calendar-go/Dockerfile
Updates OTel calendar app version to include changes in https://github.com/DataDog/opentelemetry-examples/pull/134
E2E tests in tests/otel
Motivation
----------
> Bump version for OTel calendar app

- components/os/scripts/setup-ssh.ps1
- scenarios/aws/ec2/vm.go
Attempt to fix windows dev env 2019
AWS EC2 Windows
Motivation
----------
The Windows Dev Env 2019 is currently broken, I tried disabling user data and could repro there is an error when resetting the password. This does not explain why the ssh setup fails though
> [aws][ec2][userdata][win] set username within singke quotes

- scenarios/aws/kindvm/run.go
This reverts commit 2bb2cf73f2c9ee534d443e6f4fe1c0563d3f12cb.
> Revert "fix(kind): fix workloads with admission controller dependency"

- Dockerfile
Install orchestrion to support Test Visibility upload for Go
Motivation
----------
> Install orchestrion in runner image for Test Visibility

- tasks/localpodman/vm.py
The key was wrong, updated this
Motivation
----------
> Fixed local config using gcp key

- components/kubernetes/k8sapply/component.go
Add a generic kubernetes workload app component that applies a kubernetes yaml file. 
N/A
Motivation
----------
Make it easier to create kubernetes resources from yaml
> Add generic YAML k8sapply component

- components/datadog/apps/jmxfetch/images/jmx-test-app/run.sh
Fix missing whitespace in a condition that causes it to always fail.
Motivation
----------
> Fix whitespace

- components/datadog/agent/kubernetes_helm.go
- components/datadog/agentparams/params.go
- components/datadog/dockeragentparams/params.go
- components/datadog/fakeintake/component.go
- components/datadog/fakeintake/docker.go
- scenarios/aws/fakeintake/fakeintake.go
- scenarios/azure/fakeintake/fakeintake.go
- scenarios/gcp/fakeintake/fakeintake.go
Everything is in the title, used to be more convenient agent side.
Following the reviews of this [PR](https://github.com/DataDog/datadog-agent/pull/32777)
Motivation
----------
> [ADXT-769] fakeintake: Export all outputs

- tasks/aws/__init__.py
- tasks/aws/docker.py
- tasks/aws/kind.py
- tasks/aws/vm.py
- tasks/azure/vm.py
- tasks/gcp/vm.py
- tasks/localpodman/vm.py
- tasks/tool.py
Add a task to dump json information of an existing stack
aws/vm
Motivation
----------
Need it to improve the windows dev env task on `datadog-agent`
> [tasks] add aws.show-vm task

- Dockerfile
Motivation
----------
Continuation of https://github.com/DataDog/datadog-agent-buildimages/pull/741
> Remove the use of requirements files

- components/os/linux_descriptors.go
- scenarios/aws/ec2/os_resolver.go
> Use ubuntu24.04 as default for Ubuntu

- components/datadog/agent/host_windowsos.go
Set registry to FIPS when installing the FIPS flavor of the agent
Motivation
----------
> Add a command to set FIPS in registry when FIPS agent flavor

- components/os/scripts/apt-disable-unattended-upgrades.sh
Reverts DataDog/test-infra-definitions#1450
> Revert "Improve disable-unattended-upgrade script to also disable apt daily upgrade"

- components/datadog/agent/docker_image.go
- components/datadog/agent/kubernetes_helm.go
Add logic to use FIPS image for dca when FIPS is enabled
Motivation
----------
> Use FIPS image for dca

- Dockerfile
Motivation
----------
Allow use of the new dda naming in jobs
> Update dda developer tool

- resources/aws/environmentDefaults.go
Update listern ARN after it was updated
Motivation
----------
> Update ARN for the listener that was recreated

- components/os/linux_descriptors.go
Make ubuntu 2004 descriptors available as it works as is :)
Motivation
----------
> Add Ubuntu2004 descriptor

- resources/aws/environmentDefaults.go
Configure two new load balancers for agent-qa 
Motivation
----------
> Add two more load balancers on agent-qa

- components/os/scripts/apt-disable-unattended-upgrades.sh
Fix a typo in userdata script
Motivation
----------
> Fix horrible typo in userdata script

- components/datadog/agent/kubernetes_helm.go
Add orchestrator endpoint with fake intake url
Motivation
----------
> add orchestrator endpoint

- components/datadog/agent/package.go
Make sure we do not pick debug file in e2e tests
Motivation
----------
> Exclude also -dbg- files

- common/config/environment.go
- components/datadog/apps/nginx/k8s.go
- components/datadog/apps/redis/k8s.go
This should allow us to save 5k/month on extended support charges.
Motivation
----------
> Bump EKS version

- .pre-commit-config.yaml
- tasks/ci.py
Add a hook to prevent push on protected branch
None
Motivation
----------
Prevent errors
Code copied from [here](https://github.com/DataDog/datadog-agent/blob/main/tasks/git.py#L12-L30)
> feat(pre-commit): Add a hook to prevent push on protected branch

- components/datadog/agent/kubernetes_helm.go
* Use the dedicated Helm parameter introduced in DataDog/helm-charts#1883 to configure the custom resource metric collection of the KSM check.
* Use the dedicated Helm parameter introduced in DataDog/helm-charts#1886 to configure the KSM static tags.
* `aws/eks`
* `aws/kind`
Motivation
----------
Validate the user-facing way of configuring the KSM check.
> [CONTINT-4643] Use the dedicated Helm parameter to configure KSM check

- .gitlab-ci.yml
- resources/gcp/gke/cluster.go
Make GKE cluster private, but reachable from withtin VPC through AppGate
Motivation
----------
> Update network config for GKE cluster, to make it private behind appgate

- components/datadog/agent/k8ssidecar/auth.go
- components/datadog/agent/kubernetes_helm.go
- components/datadog/apps/dogstatsd/eksFargate.go
- components/datadog/apps/nginx/eksFargate.go
- components/datadog/apps/nginx/k8s.go
- components/datadog/apps/nginx/k8s/manifest.go
- components/datadog/apps/nginx/k8s/modifiers.go
- scenarios/aws/eks/run.go
Adds a new EKS Fargate deployment in order to test a new logging method https://github.com/DataDog/datadog-agent/pull/35190
AWS EKS
Motivation
----------
E2E test for a new logging feature.
I validated this infrastructure by updating the test-infra-definitions commit hash on https://github.com/DataDog/datadog-agent/pull/37834
> EKS Fargate kubelet API Logging Infrastructure

- resources/aws/environmentDefaults.go
#incident-41524
Update agent-qa networks resources after their recreation
Motivation
----------
> Update subnets for agent-qa

- scenarios/aws/eks/run.go
Make sure workloads are not deployed if we explicitly disabled the installation of the agent.
Motivation
----------
> Do not deploy workload if the agent is not installed

- integration-tests/invoke_test.go
This test is extremely flaky, let's remove it for now.
Created a follow-up card for us to investigate the issue
Motivation
----------
> Disable testInvokeKindOperator that is very flaky
